### ISSUE TITLE
Fried Egg has no recipe

### ISSUE THREAD

**Issue by H00d3dh3r0** [LunaPixelStudios/SteamPunk#1]
### Describe the Bug

The fried egg item from Farmer's Delight does not have a recipe to craft, it cannot be cooked in a furnace or stove/campfire either. So the only way to obtain a fried egg is through the Enigmatic Legacy Rings quest, which is a one time deal.

This means that food recipes which require the fried egg cannot be made either.

### Reproduction Steps

1. Put egg in crafting bench/Or in furnace
2. Absence of ability to convert into Fried Egg
3. Sad and Hungry player produced

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/21361500/3570b94e-398c-41b6-b372-efe7a7e8a5d1)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/21361500/dca1b9fd-f379-44c9-8286-80f4c4476513)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/21361500/cbb446ba-59f2-4f02-bb09-ea137cd689fc)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v3.5

### Optifine

No

### Other Mods

No, no mods were added or removed from the pack.

**Comment by SHXRKIIE** [comment]
Will fix next update
