### ISSUE TITLE
Request to remove apocalyptic fortress

### ISSUE THREAD

**Issue by Inteprise** [LunaPixelStudios/SteamPunk#10]
### Describe the Bug

They redo the fortresses and *replace* the vanilla wither skeletons so they can possible spawn with a bow that has flame. the issue is they almost never drop loot and most importantly wither skulls. Have tried with beheading axe with looting 3 and the amulet that gives +1 extra looting and nothing.

in this pack you need the skulls to summon the wither to get nether stars to use for crafting or using it to summon other bosses (bosses can be summoned with the skull as well)

so its a very big problem that they just dont drop anything. and if they do its very rarely their stone sword or bow.

also you barely find any blaze keys to actually open the locked loot chests or turn off the fortress beacons.

you can technically loot skulls from structures but its very rare and not sustainable at all, the catacomb has some with skeleton like mobs but they do not respawn and it is rare to find considering all the new biomes and such.

all in all if this mod was removed nothing much would be lost. there is other mods that revamp the fortress but doesnt create problems like this. The mod has not been updated since jan and that is for 1.19.3 as well so the only things in 1.19.2 is like 99% building blocks for the fortress.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v5HF

### Optifine

No

**Comment by SHXRKIIE** [comment]
In the modpack you get skulls from killing the Wither Knights from Bygone nether
