### ISSUE TITLE
Various Chest Issues

### ISSUE THREAD

**Issue by BabbleJug** [LunaPixelStudios/SteamPunk#101]
### Chest Issues

For the "Craft a Chest" quest, only a vanilla chest completes the quest, but due to the Woodworks mod, chests are crafted as wood-type variants, meaning the quest is only achievable in Survival mode without cheats by finding a pre-generated vanilla chest. Additionally, the "Craft a Chest" quest mentions Iron Chests, but this mod is not in the modpack. Another thing: inventory upgrades from the Sophisticated Storage mod do not work on Woodworks chests, meaning they will only work on vanilla chests (un-craftable) or barrels.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Fixed
