### ISSUE TITLE
Server Issue: Players unable to join server

### ISSUE THREAD

**Issue by Breach5254** [LunaPixelStudios/SteamPunk#102]
### Describe the Bug

Everytime a player tries to join, they are unable too and both the server and the player are told the authentication servers are down.

### Reproduction Steps

1.Open a server
2.Join the server
3.The bug is produced
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Authentication servers are down is a minecraft issue
