### ISSUE TITLE
Server wont start

### ISSUE THREAD

**Issue by DeDog103** [LunaPixelStudios/SteamPunk#103]
### Describe the Bug

The server wont start

### Reproduction Steps

1.download server pack
2.set up server
3.start server
...

### Crash Report or Log

https://paste.sparked.host/qodojifovi

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21

### Optifine

No

**Comment by SHXRKIEgg** [comment]
No issues here, try redownloading the serverpack
