### ISSUE TITLE
Steampunk (LPS)

### ISSUE THREAD

**Issue by Russianhamsterx** [LunaPixelStudios/SteamPunk#105]
### Describe the Bug

I'm writing in this issue maybe its something you guy have added into the mod pack that won't allow controller mods on them I've tried 3 different PCs even and everyone of them have the same issue.

When downloaded control mod it loads up normal no error codes nothing, when you push play in the on the launcher it prepares it and goes away and never comes back but the PC sees its there, I've had it sit for hours and it won't load to anything and when i go back to push play it state its "playing already you sure you want to continue" if needed I can add a video to you guys or if I'm doing something wrong let me know 

Thanks.

### Reproduction Steps

1.download controllable mod by MrCrayfish
2.launch the modpack and see what happens
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by SHXRKIEgg** [comment]
I assume there is an issue the mod is having with another, I might fix but not a priority
