### ISSUE TITLE
Goat Fur not a valid insulator

### ISSUE THREAD

**Issue by Armani2512** [LunaPixelStudios/SteamPunk#107]
### Describe the Bug

Goat Fur is unable to be used in the sewing table from Cold Sweat nor does goat fur clothing provide insulation despite it saying so in the quest book. I think the problem is they arent listed as valid insulators in the default config for Cold Sweat that comes with the modpack, as it works fine outside of the modpack when Im using just Cold Sweat and nothing else.

### Reproduction Steps

1. Download the modpack from curseforge
2. Attempt to apply goat fur to any armor (doesnt work but leather, hogskin and molt does)
3. Download and launch Cold Sweat by itself 
4. Attempt to apply goat fur to any armor (it works)
5. Additionally do the same with the Goat Fur clothing, notice similar results

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20 & v21

### Optifine

No

### Other Mods

Environmental Creepers (server side)

**Comment by Armani2512** [comment]
Also theres no way to see how much insulation a piece of armor has due to some other armor UI overriding it, so it makes temperature management pretty difficult to figure out

**Comment by SHXRKIEgg** [comment]
> Also theres no way to see how much insulation a piece of armor has due to some other armor UI overriding it, so it makes temperature management pretty difficult to figure out

I made fresh Configs and it doesnt let me use Goat fur, will see what i can do
