### ISSUE TITLE
Random Crashes on Linux when Reloading Texture packs / Joining server / Launching game

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [LunaPixelStudios/SteamPunk#108]
### Describe the Bug

Minecraft sometimes just crashes/Freezes when Reloading textures/reJoining a server/Launching the game

This issue only seems to exist on Linux

My specific Version:

Garuda Linux, Kernel version 6.7.0-zen3-1-zen

### Reproduction Steps

1. Launch the Game a few times on linux / Try joining the server more than once on linux/ Load a texture pack until it happens

### Crash Report or Log

https://pastebin.com/Q915sski

### Operating System

Garuda

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Update Graphic drivers

**Comment by DisruptionSystemsINC** [comment]
Graphics drivers are up to date, I am running the latest version of AMDGPU
