### ISSUE TITLE
 Thorium Ore texture issue

### ISSUE THREAD

**Issue by qwek1** [LunaPixelStudios/SteamPunk#109]
### Describe the Bug

 Thorium Ore has an issue with texture can be fixed with a resourcepack
 
 https://www.curseforge.com/minecraft/texture-packs/thorium-texture-fix

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![qqcer31qwv](https://github.com/LunaPixelStudios/SteamPunk/assets/133406949/2bd21c34-fd46-43c2-af4c-039fd729dc84)

### Operating System

w10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Will fix
