### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by ITShet** [LunaPixelStudios/SteamPunk#11]
### Describe the Bug

as the title suggests, keybinds are not working for many mod, like sophisticated storage. IDK if its a bug or conflicts between mobs, I tried changing to different keybinds but still not working.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v6 HF

### Optifine

No

**Comment by SHXRKIIE** [comment]
New Update coming soon fixing it
