### ISSUE TITLE
Presence Footsteps & Enlightend softlock crash

### ISSUE THREAD

**Issue by qwek1** [LunaPixelStudios/SteamPunk#111]
### Describe the Bug

The game crashes when Presence Footsteps generate entity sounds from Enlightend.

This has already been known for months with no Fix, https://github.com/PaintNinja/Presence-Footsteps-Forge/issues/26

### Reproduction Steps

1. spawn in the "Ensnare" entity
2.
3.
...

### Crash Report or Log

https://mclo.gs/gr4CkSA

### Operating System

windows11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Will fix

**Comment by Blugori** [comment]
Hi, could you share how you fixed it please ? I can't find a way to keep the mob spawning + footsteps.
