### ISSUE TITLE
Ender Dragon with abnormal amount of HP in Multiplayer Instances

### ISSUE THREAD

**Issue by qwek1** [LunaPixelStudios/SteamPunk#112]
### Describe the Bug

for some reason, the dragon just goes to 1M HP after the default 3k HP dragon dies or something
If you respawn another one, it can have 22k-1M HP and can spawn another dragon

### Reproduction Steps

1. respawn dragon a few times on a multiplayer server
2.
3.
...

### Operating System

windows10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Will fix

**Comment by jinkhya** [comment]
Hello, any ETA on this issue? Have you figured out what causes this so maybe I can fix it temporarily on our server before the next pack update?
Best regards,
Jin 
@SHXRKIEgg
