### ISSUE TITLE
Crash when opening game

### ISSUE THREAD

**Issue by CrypticCrowd613** [LunaPixelStudios/SteamPunk#115]
### Describe the Bug

[latest - Copy.log](https://github.com/LunaPixelStudios/SteamPunk/files/14058335/latest.-.Copy.log)

### Reproduction Steps

1. Launcher is opened through curseforge
2. Play button pressed
3. No menu was seen at all before the crash.
...

### Screenshots and Videos

No response

### Crash Report or Log

C:\Users\rsdga\curseforge\minecraft\Instances\SteamPunk [LPS]\logs\2024-01-25-6.log

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

None

**Comment by SHXRKIEgg** [comment]
Reinstall if still an issue try another launcher like ATLauncher
