### ISSUE TITLE
Server crushes when the urn falls to the ground

### ISSUE THREAD

**Issue by 5h5ong** [LunaPixelStudios/SteamPunk#116]
### Describe the Bug

The urn from Supplementaries in the Dungeon is falls to the ground and breaks, Server crashes immediately.

If i turn the server back on after that, will crash again with the same report.

### Reproduction Steps

1. Find Dungeon like this

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/29355285/ab2903a1-fb0e-4c69-b214-0e416f97fa5d)

2. Break support block(stairs) below the urn

3. Urn falls to the ground and breaks

4. Crash!

### Crash Report or Log

https://pastebin.com/RYsmJmr5

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
update the Supplementaries mod and its dependencies, and if issue persists then report it to the Supplementaries devs
