### ISSUE TITLE
Cant find Ponder Index in pause menu

### ISSUE THREAD

**Issue by Harpinder-Mangat** [LunaPixelStudios/SteamPunk#117]
### Describe the Bug

Cant find Ponder Index in pause menu. it looks like the engineering goggles

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Search Create in the Mods button
