### ISSUE TITLE
Moon Flying

### ISSUE THREAD

**Issue by Snowykambo** [LunaPixelStudios/SteamPunk#118]
### Describe the Bug

I arrived on the moon and then began to float indefinitely I had to turn on cheats just to be able to get around the dimension.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by chorbintime** [comment]
are you sure you were wearing the proper gear?

**Comment by Snowykambo** [comment]
I realized one of the charms I had on had a -25 gravity effect on it, after taking it off the issue was fixed
