### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by GehennaWhore** [LunaPixelStudios/SteamPunk#120]
### Describe the Bug

Game appears to load several times while launching without ever reaching the main menu before eventually crashing. I have tried reinstalling and several versions of the modpack all with the same result.

### Reproduction Steps

1. Launch game
2. Loading bar appears to fill and reset several times
3. Eventually will just crash
...

### Crash Report or Log

https://gist.github.com/GehennaWhore/f7c82ea72f663809c12b5bba47e4c448

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Can you see if reinstalling it fixes it?

**Comment by GehennaWhore** [comment]
Reinstalling does not fix it.

**Comment by NikitaTRyfoniuk** [comment]
> Can you see if reinstalling it fixes it?

I'm still having the same problem even after I reinstalled Minecraft, Java,  SteamPunk[LPS], CurseForge, drivers, Windows

**Comment by chorbintime** [comment]
please send the crash report in the crash reports folder

**Comment by GehennaWhore** [comment]
[crash-2024-02-01_07.43.08-fml.txt](https://github.com/LunaPixelStudios/SteamPunk/files/14154575/crash-2024-02-01_07.43.08-fml.txt)

**Comment by SHXRKIEgg** [comment]
Its a mod loading issue, so i guess its something to do with Linux or the launcher, not an issue we can really help with

**Comment by GehennaWhore** [comment]
Yeah, it works fine after disabling Paintings++. weird.
