### ISSUE TITLE
Rumbling and or noises 

### ISSUE THREAD

**Issue by DolloDM** [LunaPixelStudios/SteamPunk#122]
### Describe the Bug

There is a rumbling and or noises that keep making sounds in the back ground that won't stop and its ruining the game for me as the game when the music is playing or when i am just farming there is this rumbling noise or sound that happens every 25 seconds and I cant find what sound it is coming from  it isn't monster sounds or ambiance so i have to turn off everything just so it can stop.

### Reproduction Steps

1.Just play the game it happens eventually
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

43.3.5

### Optifine

No

**Comment by closed-captions** [comment]
can confirm. i'm hearing basalt delta ambience in the overworld

**Comment by SHXRKIEgg** [comment]
Duplicate #110
