### ISSUE TITLE
Quest book on server not Working

### ISSUE THREAD

**Issue by JLL612310** [LunaPixelStudios/SteamPunk#123]
### Describe the Bug

Error in game when accessing the questbook:
"Unable to open Quest GUI: no quest book data recieved from server!
-Check that FTB Quest and FTB Teams are installed on the server and that no server side errors were logged when you connected."

Please help!

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

steampunk

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Whos your serverhost and how did you set it up?

**Comment by chorbintime** [comment]
You probably forgot to install configs on your server
