### ISSUE TITLE
cold sweat insulation not appearing on armor

### ISSUE THREAD

**Issue by closed-captions** [LunaPixelStudios/SteamPunk#124]
### Describe the Bug

when insulation is applied to armor through the sewing table or is innately present on a piece of armor (hoglin, fur, leather), a row is added above the armor points but the level of insulation is not displayed. this doesn't seem to be a resource pack issue, as i disabled all of them and the issue still persisted.

### Reproduction Steps

1. place armor and insulation inside sewing table / observe hoglin, leather or fur armor
2. (optional) disable resource packs
3. see results

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/55032945/6a6973c8-b727-414c-a7b1-439e5cfdc76b)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/55032945/b6b554cc-b59b-44a0-969c-c4af8366d166)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/55032945/76e7dd57-ca88-4ab8-8884-95c1c425d2e4)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Its due to the Obscuria Mod, it something they need to fix
