### ISSUE TITLE
Mod suggestions

### ISSUE THREAD

**Issue by twothe** [LunaPixelStudios/SteamPunk#126]
First of all: thank you for the awesome modpack, friends and I are having a ton of fun with it.

However I came to notice that some in my eyes essential mods are missing. I would recommend the following mods:

1. Spark - Shows performance, tells you which mods cause lag, and is essential for any server to find lag sources.
2. Create Mechanical Extruder - Generates cobblestone and some other base stone items. As cobble is required for many things in create, people currently have to build vanilla cobblestone gens, and of course they build them on an industrial level, and with that cause an industrial level of lag. This can be fixed by generating the cobble without block updates via the Extruder.
3. In Control - Allows to regulate mob spawning. Essential for any server, otherwise most of the CPU power is wasted on mobs idling somewhere.
4. Inventory Hud+ - Allows to see inventory information wherever you want to, highly configurable. Allows to move the potion buff display, allows to see armor durability, and you can switch on and off whatever part you want.

**Comment by chorbintime** [comment]
Bad Mobs replaces the functionality of In Control, but we will look into the rest

**Comment by twothe** [comment]
Thank you!
I will have a look into the config file of Bad Mobs for my server then.
