### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by florian-bougeatre** [LunaPixelStudios/SteamPunk#127]
### Describe the Bug

The game crashes a lot with the same type of exception. To it crashed a lot around trains and tracks from Create, but I don't know yet if it is related.

### Reproduction Steps

Crashed when placing tracks, when driving a train, when breaking tracks, when using rollers...

### Crash Report or Log

https://gist.github.com/florian-bougeatre/eb52607c991858745ff74171c2b74616

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

No other mods, just changed 1 or 2 mod config file on the server.

**Comment by SHXRKIEgg** [comment]
See if removing Sound Physics Remastered fixes it
