### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by CantPin** [LunaPixelStudios/SteamPunk#13]
### Describe the Bug

I recently downloaded this modpack and I keep getting Exit Code 1 every time I launch the game through the launcher, I haven't customized the modlist in any way, just download and click play and I get the exit code 1 every time I try to launch the game. 

I have already update Java and JDK but still no way to launch the game, I keep getting this error code.

I tried to fix it through crash logs but I can't understand anything.

Sorry if my English is bad, its not my first language.

### Reproduction Steps

1. Install the modpack in Curseforge app.
2. Initiate the minecraft launcher.
3. Click Play.
4. Get Exit Code 1.

### Crash Report or Log

https://pastebin.com/UThJgqT8

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v7

### Optifine

No

### Other Mods

None.

**Comment by SHXRKIIE** [comment]
Can you try the modpack on ATLauncher and see if that fixes it?

**Comment by CantPin** [comment]
I will try that.

**Comment by CantPin** [comment]
Using ATLauncher to run the modpack seems to fix the issue. Thank you Shxrkiie.
