### ISSUE TITLE
Sophisticated Storage Limited Barrels texture bug when you try to storage any kind of block with Faithless resource pack on

### ISSUE THREAD

**Issue by Stillflex211** [LunaPixelStudios/SteamPunk#130]
### Describe the Bug

I was wanting to try using the limited barrels from sophisticated storage, where you can have dozens of stacks in asingular barrel for easy access, but then i tried to storage some blockc on it and it apeared like the block was overlapping with the barrel's space. This doesn't happen with any item that isn't a block or have a complex 3d model. The barrel still works, but the buggy texture really bothers me enough to not wanting to use it. It only happens with the Faithless.zip resource pack active, which is active by default when you download the modpack. And even without the faithless resource pack on, there are some blocks that just doesn't show on the barrel display, which is pretty annoying. I wanted to see if it can be fixed so i can use the barrels without needing to deactivate the resource pack, since it is visually marvelous!

### Reproduction Steps

1. Place any kind of limited barrel from Sophisticated Storage mod
2. Try to place a block on it's storage (a bucket also appears kinda weird)
...

### Screenshots and Videos

![imagem_2024-02-09_165801279](https://github.com/LunaPixelStudios/SteamPunk/assets/159569414/8b83838f-89d6-4d10-8a50-267d5ea632d2)

showcase with the Faithless resource pack on: https://www.youtube.com/watch?v=Y_xDTFXussU
Showcase with the Faithless resource pack off: https://www.youtube.com/watch?v=gOFkiTir6bQ

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v21.5

### Optifine

No

**Comment by EuclaidGalieane** [comment]
https://github.com/P3pp3rF1y/SophisticatedStorage/issues/332#issuecomment-1898320607

**Comment by chorbintime** [comment]
report it to the resourcepack creators
