### ISSUE TITLE
Structures missing parts

### ISSUE THREAD

**Issue by jmgwilson** [LunaPixelStudios/SteamPunk#131]
### Describe the Bug

A very large amount of structures I come across are missing parts of the building. This causes missing walls and massive holes.

### Reproduction Steps

This happens when generating any world.

### Screenshots and Videos

![example 1](https://github.com/LunaPixelStudios/SteamPunk/assets/39098959/2ecfdf34-de16-4a25-ac9d-454e466c8e36)
![example 2](https://github.com/LunaPixelStudios/SteamPunk/assets/39098959/5559509d-7f28-4e1b-8a62-f2ea79da49c5)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
These structures are from Pyrologer And Friends, due to how the mod they sometimes don't generate well. Remove it if you dont like it
