### ISSUE TITLE
Basalt Delta ambient noises playing in Overworld

### ISSUE THREAD

**Issue by JetPoweredGaming** [LunaPixelStudios/SteamPunk#132]
### Describe the Bug

Nearly constantly the game is playing ambient sounds in the overworld from the Basalt Delta biome like the geiger counter, explosions, etc.  Sound Physics Remastered mod seems to be related, when it is disabled the sounds stop. I have Enabled the "Evaluate Ambient Sounds" option in the config and it fixed the normal ambient sounds but it still plays the Basalt Delta noises

### Reproduction Steps

1. Sound physics remastered is enabled
2. Evaluate Ambient Sounds option is enabled
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/95190916/74fa05cc-5ea2-49fc-b97e-eb3117b6cadb)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v21.5

### Optifine

No

**Comment by JetPoweredGaming** [comment]
Temporary fix is to install the sound muffler mod
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler

**Comment by RCencelj** [comment]
Can confirm, this happens to me as well - It seems to happen regardless of the settings I change in the sound mod you mention. I even went about and deleted it from the mods folder and the issue persisted. Would you mind chiming in on which sounds exactly you're supposed to muffle with the extreme muffler? Thanks!

**Comment by JetPoweredGaming** [comment]
I ended up using a resource pack that someone made specifically to get rid of the basalt deltas sounds. The muter mod wasn't working right either. 
(Discord User: xEagle5x)
[no_basalt_delta_sounds_1.19.zip](https://github.com/LunaPixelStudios/SteamPunk/files/14275133/no_basalt_delta_sounds_1.19.zip)

**Comment by SHXRKIEgg** [comment]
Turning on the "evaluate ambient sounds" setting in Sound Physics config seems to have fixed the basalt ambience issue

**Comment by JetPoweredGaming** [comment]
That did not fix the issue for me and it's the same for others as well. Updating the mod didn't change anything either. Any idea why this audio is playing in the overworld to begin with?

**Comment by Tectonic4reaI** [comment]
this happens to me to

**Comment by RCencelj** [comment]
I'll also add that with the resource pack (I believe it's called) provided by JetPoweredGaming, I still get weird sounds playing (ghast shooting noise, placing stone noise, among others). It's much better with the resource pack, but these sounds still happen.
