### ISSUE TITLE
Something have weird name "most of in Aether"

### ISSUE THREAD

**Issue by LOL12322** [LunaPixelStudios/SteamPunk#133]
### Describe the Bug

I find something in aether have a weird name like block.aether.redux....... but it just skyroot crafting table

can you check this!

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/154892625/3f4edc3c-7441-4fba-a499-42813ad817ad)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/154892625/5f71dcd6-f9af-4c3c-8533-e96e5367eb0f)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Its just a name issue that isnt compatible with jade
