### ISSUE TITLE
Backpack & Chest upgrade bugs galore, server issues and self deleting bags

### ISSUE THREAD

**Issue by Tyrantosaurex** [LunaPixelStudios/SteamPunk#134]
### Describe the Bug

It appears this is something effecting both upgraded backpack and chest upgrades. Our server was having issues with allowing anyone but the initial player who connected first to connect, once all stack upgrades and other upgrades were removed from chests this connection issues has been resolved (for now). I'll update as more information arises.

**Issue 1:** When backpacks are ported to a new server sometimes contents are entirely lost (Moving over player data), this hasn't occurred when moving from previous versions to the current version and seems to only occur when moving from a server on the current version to another on the current version.

**Issue 2:** Back tanks disappear when placed

**Issue 3:** Some upgrades like auto-feeding cause players to not be able to connect to servers and eventually cause either the complete inability for that player to connect to the server as well as occasionally causing other players to lose the ability to connect entirely until a sever restart. (Upgrades for chests might need a look over for this as well).

**Issue 4:** When Issue 3 has been ran into worlds can no longer be loaded in single player.

### Reproduction Steps

1. Put auto feeding or tank upgrades on a backpack (And potentially other upgrades).
2. Actively have the backpack on you or placed (or attempted to place) in the world.
3. Perform the related reported issues.

Issue 1 and 2 have been replicated as per the [discord here](https://discord.com/channels/790272037578473512/996250521465790514/1206311688568307732)
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by SHXRKIEgg** [comment]
There seems to be some mod updates fixing this issue, will see when I can update the modpack

**Comment by chorbintime** [comment]
if the issue persists after modpack update, please report it to the mod developers
