### ISSUE TITLE
Shuriken's deflect attacks

### ISSUE THREAD

**Issue by RechargeableAA** [LunaPixelStudios/SteamPunk#135]
### Describe the Bug

holding right click with a shuriken in hand will negate damage, indefinitely since it has no durability. 

### Reproduction Steps

1.get shuriken
2.hold right click / use
3.substitute for unbreakable shield
...

### Crash Report or Log

none

### Operating System

win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

43.3.5

### Optifine

No

### Other Mods

~modpack

**Comment by chorbintime** [comment]
report it to the developers of the mod that adds the shuriken
