### ISSUE TITLE
Server insanely slow at generating new chunks

### ISSUE THREAD

**Issue by RawrOwO** [LunaPixelStudios/SteamPunk#137]
### Describe the Bug

We have a server that has run multiple large modpacks jut fine, but for some reason this one has trouble generating new chunks, even one player just running in a straight line is enough to cause immense lag and you have to stop often to wait for the chunks to load and the console gets flooded with errors.

### Screenshots and Videos

![obrázek_2024-02-13_223800611](https://github.com/LunaPixelStudios/SteamPunk/assets/159961661/419f9e47-133f-4727-a1fa-e905247f50ef)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by oSecret** [comment]
Same issue, doesn't matter if it's 1 person or 5 people generating new chunks it's just awful and hangs

**Comment by SHXRKIEgg** [comment]
Can you please give a spark profiler
/spark profiler --timeout 30 and send the link

**Comment by oSecret** [comment]
> Can you please give a spark profiler /spark profiler --timeout 30 and send the link

https://spark.lucko.me/K30dr35N3a

**Comment by RawrOwO** [comment]
https://spark.lucko.me/p8Rlj6hz4E

st 14. 2. 2024 v 7:21 odesílatel 丂廾闩尺长工㠪 ***@***.***> napsal:

**Comment by SHXRKIEgg** [comment]
Seems liek Iter RPG has an issue with generating procedure, you can try reverting the mod or removing it to see if that helps

**Comment by chorbintime** [comment]
report it to the developers of Iter RPG

**Comment by RawrOwO** [comment]
Removing Iter RPG did not fix the issue

pá 16. 2. 2024 v 4:54 odesílatel chorb ***@***.***> napsal:

**Comment by Quint0ne** [comment]
I've done a bit of research and testing and from what I can tell it seems to be  "Pyrologers and Friends." When removed a new chunks will load much faster than before. Although if loading chunks in a world that previously had the mod then the area around the old chunks will load a bit slower possibly due to the data of the removed mod being present but once loaded the beyond chunks will be much faster to load.

**Comment by RawrOwO** [comment]
Ive removed that mod as well and there has been 0 improvement in the chunk
gen.


ne 18. 2. 2024 v 9:34 odesílatel Quint0ne ***@***.***> napsal:

**Comment by jer-vo** [comment]
i have the same issue, tryed everything even when pre generating the chunks the server crashes
