### ISSUE TITLE
Huge FPS drop when using drills for mining blocks

### ISSUE THREAD

**Issue by RAREGUN** [LunaPixelStudios/SteamPunk#138]
### Describe the Bug

Huge FPS drop when using drills for mining blocks
Processor analogue of i9 9900k OC 5GHz

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/46169975/6499f7b1-e617-4b7d-8fad-1d11e1dbbb0a)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/46169975/5052aeb9-085d-461e-a79b-fe8c96aa42df)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v 21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Please run the /sparkc profiler start command ingame and do the laggy behavior for about 1 minute. Then, reply to this post with a link to the profiler

**Comment by RAREGUN** [comment]
> Please run the /sparkc profiler start command ingame and do the laggy behavior for about 1 minute. Then, reply to this post with a link to the profiler

https://spark.lucko.me/DaX2ipJl3t

**Comment by chorbintime** [comment]
Please try to clean up some disc space. It may be inhibiting your swap space, which would reduce your available RAM.

What CPU do you have? Can you try removing the Sound Physics Remastered mod, and see if that helps?

**Comment by RAREGUN** [comment]
> swap space
MUCH better without swap, thank you. Absolutely forgot about swap in my system, i have added 16Gb of ram in this month, no more swap needed.
P.S: Swap was on my second m2 PCI-E 3.0 SSD (RIP) 


> What CPU
QTJ0 5.0 GHz


> removing the Sound Physics Remastered

Doesn't change anything
