### ISSUE TITLE
Tetra Crossbow enchant problem

### ISSUE THREAD

**Issue by H3lping** [LunaPixelStudios/SteamPunk#14]
### Describe the Bug

When a tetra crossbow is enchanted with ceaseless (can shoot basic arrows without consuming ammunition) it does not work. will consume arrows in your inventory and won't reload without arrows

### Reproduction Steps

1. enchant tetra crossbow with ceaseless
2. reload with arrows in inventory
3. try and reload without arrows
...
Enchant

### Screenshots and Videos

![Screenshot 2023-09-04 113942](https://github.com/LunaPixelStudios/SteamPunk/assets/42731051/0fc299bf-cfcb-498b-b169-b7b2d72a630b)

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/42731051/cac7d790-52bf-4f0e-88d4-cb11e8f1fffd)

### Crash Report or Log

~

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v8.5 HF

### Optifine

No

### Other Mods

simplevoicechat

**Comment by SHXRKIIE** [comment]
I am working on v9 and I dont have this issue so I guess it will be fixed

**Comment by Berryliss** [comment]
hello, im playing on v21.5 and this issue is yet present, sorry for necroposting
