### ISSUE TITLE
Modpack version for server includes client mods

### ISSUE THREAD

**Issue by je-sendra** [LunaPixelStudios/SteamPunk#140]
### Describe the Bug

When downloading the "server" version of the modpack from Curseforge, some client-side mods will be downloaded, and the Forge server will crash when starting.

I have prepared a "server" version of the modpack myself, in case you want to see it.

I tried manually setting up a mc server outside of docker and error happened anyway.

### Reproduction Steps

1. Start itzg/minecraft-server docker image on AUTO_CURSEFORGE mode
2. It downloads the "server" version of the modpack
3. Forge server won't start
...

### Operating System

Docker (itzg/minecraft-server:latest)

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Latest atm (Jan 21, 2024) - 21.5

### Optifine

No

**Comment by Riewest** [comment]
Came here with the same issue.

Found a work around for the offending mods using the following environment variable that itzg/minecraft-server provides: 
  - https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods
  - CF_EXCLUDE_MODS="913587,506948,905450"
  
Mods that are being downloaded when they shouldn't be:
1. https://legacy.curseforge.com/minecraft/mc-mods/bocchium
2. https://legacy.curseforge.com/minecraft/mc-mods/jer-integration
3. https://legacy.curseforge.com/minecraft/mc-mods/ryoamiclights

**Comment by je-sendra** [comment]
@Riewest Oh, that's awesome, thank you. Had to change server mode to normal FORGE and specify versions manually since AUTO_CURSEFORGE would keep downloading the mod files.

**Comment by chorbintime** [comment]
the serverpack is tested to work on a normal Windows installation before being uploaded. If you are experiencing issues, that is not in our control
