### ISSUE TITLE
Torches emitting white particles don't drop when broken.

### ISSUE THREAD

**Issue by Tectonic4reaI** [LunaPixelStudios/SteamPunk#142]
### Describe the Bug

When I place a torch and right click it, it changes it's texture and starts emitting white particle. If you right click it again, it goes back to normal. When I break the torch while it is emitting white particles, it dissapears

### Reproduction Steps

1. Place a torch
2. Right click it
3. Break it

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V21.5

### Optifine

I used Optifine

### Other Mods

Resource Pack No Basalt Delta Sounds

**Comment by Tectonic4reaI** [comment]
*Didn't use Optifine*

**Comment by chorbintime** [comment]
Send a screenshot with F3 open while looking at a torch that has the white particles
