### ISSUE TITLE
Conflict with Dark Oak Board from Handcrafted and Chipped 

### ISSUE THREAD

**Issue by Fraonil** [LunaPixelStudios/SteamPunk#143]
### Describe the Bug

Hi, For make Board you can make board in mechanal saw of Create but it's dont work. It's always planks of Chipped on exit. I try with filter it same. I think it's the same for all boards of Handcrafted mod. Comm it's the only way to do them it's a bit annoying.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
report it to the developer of the problematic mod
