### ISSUE TITLE
Output problem when you choice Every Compat Glasse in Chipped's Glassblower's Worbench.

### ISSUE THREAD

**Issue by Fraonil** [LunaPixelStudios/SteamPunk#144]
### Describe the Bug

Every compat offers plenty of glass in Chipped's Glassblower's Workbench.
After a certain level if you go down the list in the workbench, the glass chosen is not the one that comes out.

### Reproduction Steps

1.Chose Frostbriht Ornate Barred Glass
2.Click to craft
3.Result Oak Diamond Bordered Glass
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
report it to the developers of the Chipped mod
