### ISSUE TITLE
Create Mod Reinforced Energizer crashing server

### ISSUE THREAD

**Issue by androoo06** [LunaPixelStudios/SteamPunk#145]
### Describe the Bug

Powering the Ad Astra Jet Suit with the Create Mod Energizer crashes the server repeatedly
- whenever the server renders the chunk with the energizer powering the jet suit it crashes

EDIT: any non-create item (such as an Immersive Engineering Railgun) that requires energy reproduces the same bug

### Reproduction Steps

1. Get Jet Suit
2. Put it on a depot that is under a Create Mod Reinforced Energizer

### Screenshots and Videos

N/A (can't get into the server anymore to replicate due to the bug, but could demonstrate in a new world if necessary)

### Crash Report or Log

https://pastebin.com/sPKrdiJj

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

N/A

**Comment by chorbintime** [comment]
Report it to the developers of the mod that adds the Energizer
