### ISSUE TITLE
Missing Quest Reward

### ISSUE THREAD

**Issue by BaalZebaoth** [LunaPixelStudios/SteamPunk#146]
### Describe the Bug

 One of the possible rewards from quests is a missing item: "iter_rpg:ocean_ingot". (See image)

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-02-21_23 40 21](https://github.com/LunaPixelStudios/SteamPunk/assets/160808761/ed3900f2-b113-4fd3-8f98-f1a640db9a06)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by Anan51** [comment]
I have the same issue with that mod's hell ingot.

**Comment by chorbintime** [comment]
Will be fixed in the next update
