### ISSUE TITLE
storage controller bug

### ISSUE THREAD

**Issue by waldmannl** [LunaPixelStudios/SteamPunk#147]
### Describe the Bug

First of all, the bug was on a server.

If we put a storage controller down and we link limited acacia barrels to it, the controller won't work with all the barrels.

But there is one more interesting thing.  Among the barrels, there is also a limited acacia barrel that can store four different items, but it is as if only half is connected to the controller.  In other words, every item has free space in the barrel, but if I want to load them through the controller, it loads 2 items in the barrel and ignores 2 and leaves it in the inventory.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v21.5

### Optifine

No

**Comment by chorbintime** [comment]
Report it to the developers of the mod that adds the storage controllers.
