### ISSUE TITLE
Immersive Engineering Refinery Gui is glitched

### ISSUE THREAD

**Issue by Anan51** [LunaPixelStudios/SteamPunk#148]
### Describe the Bug

I built a standard refinery from Immersive Engineering and provided it with power. I opened the UI for the refinery and it was all glitched, with fluid tanks overlapping with where input slots should have been. The only Item I am able to put in so far is Nitrate, but trying to shift click the Plant Oil or Ethanol buckets puts them in the outtake slot. This issue was there before and after I removed the faithless resource packs.

### Reproduction Steps

1. Construct a Refinery
2. Provide the Refinery with power
3. Open the GUI

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/74806654/5b4f3328-e3dd-47e7-9d3e-c4053f2a36c0)

The issue persists in JEI. Am I missing a mod or necessary texture pack? Does Steampunk require Optifine?

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/74806654/80431eba-236a-4287-ba90-9254fcfb65df)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

I did not add any mods.

**Comment by Anan51** [comment]
I should also say, none of the other Immersive Engineering machines have this issue. It is specifically the refinery that has this issue. I destroyed and rebuilt the refinery in case that was the issue, although that did not fix it.

**Comment by chorbintime** [comment]
Are you sure this happens with all resourcepacks disabled? I'd suggest re-enabling them after testing.
