### ISSUE TITLE
Quest Book > Spirit > Velocitas Rune, the tooltip there is wrong.

### ISSUE THREAD

**Issue by eaganlai** [LunaPixelStudios/SteamPunk#149]
### Describe the Bug

See below attached screenshot.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/74284983/c214be2a-064b-43e1-91e0-67b69fc6d372)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
will be fixed next update
