### ISSUE TITLE
Error while attempting to launch server

### ISSUE THREAD

**Issue by ArtofPixels** [LunaPixelStudios/SteamPunk#15]
### Describe the Bug

Despite uninstalling other Java versions and PC restarts, I seem to be encountering an error while attempting to boot up the server. Everything from its first launch works as intended, and I'm running on Java 18 as specified, but to no success.

### Reproduction Steps

1. Install Server Pack
2. Extract
3. Run start.ps1
...

### Screenshots and Videos

Refer to Pastebin

### Crash Report or Log

https://pastebin.com/gbnBQDWM

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v9 HF

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
OutOfMemoryError: Java heap space, running out of memory it says

**Comment by ArtofPixels** [comment]
> OutOfMemoryError: Java heap space, running out of memory it says

Ah, okay.
I'll give it a change when I get the chance,

How much extra memory would I have to allocate? Apologies, I assumed the .ps1 was predefined with enough memory allocated to not cause an error.

**Comment by SHXRKIIE** [comment]
The .ps1 works out of the box, its saying your system is running out of memory because I assume you dont have enough memory in your system? You can try allocating more but not sure if that fixes it.

**Comment by ArtofPixels** [comment]
Weird, I _should_ have more than enough to be able to run a server, unless its using much more than what I'm expecting. 
I'll let you know if changing the memory allocation helps.

**Comment by ArtofPixels** [comment]
I seem to have found the issue, it was cause I installed the wrong version of Java 18 last night. So what should've been 64x was 86x, causing the errors, my bad.

Everything works as intended, thanks for the help regardless.
