### ISSUE TITLE
phantom blocks following you when using shaders.

### ISSUE THREAD

**Issue by GungarTheWise** [LunaPixelStudios/SteamPunk#150]
### Describe the Bug

When using shaders some textures for mainly create blocks go missing or are offset to your general location and will teleport to you as you explore.

### Reproduction Steps

1. enter a world and place down a bunch of create blocks, looks like a mechanical press or mixer and a toolbox lid as well as some chest lids
2. turn on a shader (currently using the complimentary reimagined + euphoria patches)
3. you should have some phantom blocks that teleport you your general location when you move far enough away.
...

### Screenshots and Videos

![image_2024-02-24_164402669](https://github.com/LunaPixelStudios/SteamPunk/assets/134067449/32635001-bd9a-4f29-9154-b8f53d9b044c)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

I did not add any mods but I did remove one of the crayfish gun mods as it was causing basalt delta ambiance to occur constantly

**Comment by chorbintime** [comment]
update your GPU drivers - if the issue persists, report it to the shaderpack creators
