### ISSUE TITLE
Immersive engineering ores not spawning  

### ISSUE THREAD

**Issue by pr0c0** [LunaPixelStudios/SteamPunk#151]
### Describe the Bug

no IE ores have spawned in world

### Reproduction Steps

1.look at spawn location
2.mine
3.repeate
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
report it to the IE devs
