### ISSUE TITLE
chest compatibility issue

### ISSUE THREAD

**Issue by embii-wizboi** [LunaPixelStudios/SteamPunk#152]
### Describe the Bug

chests cannot be crafted out of many types of planks, as well as  specific wood chest types cannot be used to craft recipes that require chests

### Reproduction Steps

1.craft chest out of cypress planks
2.craft trading post using woodworks chest
3.neither of them work :)
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161245389/bf2bd520-74c8-49b5-851f-99dfec30c92a)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161245389/244216c3-b268-466d-895d-56bcdca56f15)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

I used Optifine

### Other Mods

simple voice chat, distant horizons

**Comment by chorbintime** [comment]
report it to the developers of the mod that adds those planks
