### ISSUE TITLE
Nothing loading in Nether, falling infinitely and commands don't work 

### ISSUE THREAD

**Issue by Thomas6589** [LunaPixelStudios/SteamPunk#153]
### Describe the Bug

When entering the nether for the first time, no blocks loaded properly, there were still outlines when i cursored over the blocks and the UI would tell me what block it was but no textures loaded no matter how long I waited and I couldn't go back through the portal.

At this point I saved and quit. Upon opening the world again I was in the nether but it was just an empty black void and I was just falling. My y coordinate fell into the negative thousands. At this point I loose all access to commands. No TP commands work nor does TPing from the map. I can't change my game mode or anything I am just stuck falling.

I quit again and now when loading it, it plays the Nether noises and music but just displays "loading Terrain" and nothing happens

Have created multiple other worlds and have run into the same issue every time. However this does not occur in other dimensions, only the Nether seems to be affected

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
please provide logs
