### ISSUE TITLE
Major performance issues for Servers!

### ISSUE THREAD

**Issue by Burchard36** [LunaPixelStudios/SteamPunk#155]
### Describe the Bug

1) Alex's Mobs "Underminers" NEED to be disabled via config (Set the weight to 0) - I currently do not havea  spark report wih me but its easy to reproduce, just get one to spawn naturally and check your TPS. Just 2 of these can cause ridiculous amounts of lag

2) Thin Air - Needs an actual update to address performance issues & configs being ignored, or just removed from the pack

#2 Explained:

Here is our spark report, this performance is absolutely unacceptable IMO: https://spark.lucko.me/QQo8iNzS4V - The hardware this server runs on on a dedi from hetzner so this error is 100% the modpack and not hardware related, we have 3 ATM9 servers with players on them and they are all 20TPS

It appears that thin air is CONSTANTLY doing checks on loaded entities in order to update them... however with this spark report i ENTIRELY disabled the dimensions & the entities arrays in the thing air configuration file and they are still being checked...

### Reproduction Steps

1. For alex's mobs just spawn in like 2-3 underminers or let them spawn naturally
2. For thin air you need a decent amount of players online, the lag happens at around 4 or more players even with lower render distance, and lowering the render distance shouldnt be the fix here, either thin air needs and update or should just be removed

### Operating System

Debian

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

Nope!

**Comment by Burchard36** [comment]
Seems my spark report link is broken, here you go: https://spark.lucko.me/FyM6F6BGmR

Wasn't sure whether to upload this to the thin air issues page or not but this seemed appropriate as its multiple point of issues

**Comment by chorbintime** [comment]
report the first issue to the alexs mobs devs

the 2nd issue will be fixed the next time the modpack updates
