### ISSUE TITLE
Fresh install wont launch

### ISSUE THREAD

**Issue by Swartzyck** [LunaPixelStudios/SteamPunk#157]
### Describe the Bug

Game wont launch, ive tried Curseforge and ATL. Reinstalled on both. My computer also has a fresh install. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/h9RT62T4

### Operating System

Windows 11 fresh install

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by Swartzyck** [comment]
https://gist.github.com/Swartzyck/41d5ed898e944c0344e3211f3f9c91f4

**Comment by chorbintime** [comment]
update your gpu drivers

**Comment by Swartzyck** [comment]
Same problem after GPU driver update, this is the crashlog post update from curseforge. ATL is the same.

https://gist.github.com/Swartzyck/b81a49cd558ea06e480491b2649d5a64
