### ISSUE TITLE
Porblems with playing on a server

### ISSUE THREAD

**Issue by Chri4221** [LunaPixelStudios/SteamPunk#158]
### Describe the Bug

I have been playing on a server with some of my friends for a couple of days and have noticed two major bugs.
Firstly none of the people on the server are able to see the quests as the quests book happens to be completely empty.
Secondly i have noticed that none of the custom crafting recipes are working.

I hope this is something you would be able to resolve, as it would make it a lot more enjoyable to play.

### Reproduction Steps

1. Open questbook in multiplayer

### Screenshots and Videos

Quest book bug:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161743165/c2f9f120-ee01-4c84-846f-7b23009084cb)

Customs recipes missing in multiplayer:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161743165/5bc59535-34bb-41ab-9653-23024a8a397d)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161743165/4e87f40a-7d91-46b0-b7f5-4fe5890fcd7b)

What it looks like in singlepayer for reference:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161743165/0d6833dc-6976-49d7-b27e-d38bef5e61e0)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/161743165/a88ce8fd-bbd6-4373-9c76-65208d50369f)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21,5

### Optifine

No

**Comment by chorbintime** [comment]
you do not have configs installed on the server. please use the serverpack files or use a server host such as bisect to host your server.
