### ISSUE TITLE
Chunk Load 

### ISSUE THREAD

**Issue by Marsshiii** [LunaPixelStudios/SteamPunk#16]
### Describe the Bug

Every TIme I want to explore (which is one of the mains things of this pack
I"ve got chunk bug, sometimes it could takes minutes to charge the chunk 
I've got the max RAM I could get for it, have a good computer like everything so I don't understand why it's always happening.......

### Reproduction Steps

1. Starting an exploration
2. With a Horse, a boat or by walking
3. At some point have a really bad chunk load and can't go foreward anymore, having roll back and freeze.......
...

### Operating System

Windowq 11 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10 

### Optifine

No

**Comment by SHXRKIIE** [comment]
How are you hosting the server, who s the server provider?

**Comment by Marsshiii** [comment]
It's okay I found the solution I was at 12 Render distance 
And now that I lower down at 6 I don't have problems anymore
