### ISSUE TITLE
There is an error in a particular ender region.

### ISSUE THREAD

**Issue by Luchi-kim** [LunaPixelStudios/SteamPunk#160]
### Describe the Bug

When I enter the ender area like the image below, the game crashes for unknown reasons such as certain monsters or environmental elements.

```
Generating PF sounds for entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.sounds.SoundEvent.m_11660_()" because the return value of "net.minecraft.world.level.block.SoundType.m_56776_()" is null
```

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/29831801/986ef7e1-a5d3-4f45-9cc0-8e3bfe5418b1)

### Operating System

Win 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk [LPS] - v21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
i cant help if you dont send the full crash report file
