### ISSUE TITLE
Create goggles not working

### ISSUE THREAD

**Issue by mangozjeb2115** [LunaPixelStudios/SteamPunk#161]
### Describe the Bug

When im looking at a create block I dont see the create hud like stress units. Hud just doesnt appear

### Reproduction Steps

1. Get create goggles
2. Look at create block (ex mechanical press)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
report it to the author of the mod, please
