### ISSUE TITLE
Cold Sweat crafting table, UI bugged

### ISSUE THREAD

**Issue by CommanderTso** [LunaPixelStudios/SteamPunk#162]
### Describe the Bug

Some elements of the Cold Sweat mod do not work in the current version of the Steampunk mod (21.5).

- Fur is not accepted by the Sewing Table, which it should be
- When hovering the mouse over items that have been given insulation (or previewing them in the Sewing Table before pulling the finished item from it), the UI bar with the current insulation value does not appear. Room is made in the tooltip for that element, but it is not visible.

### Reproduction Steps

Fur will not place
1. Create and place a Sewing Table from the Cold Sweat mod.
2. Place an iron chestpiece into the table.
3. Attempt to place Fur into the sewing table.

Result: Fur will not be accepted by the table.

Tooltip will not show up
1. Create and place a Sewing Table from the Cold Sweat mod.
2. Place an iron chestpiece into the table.
3. Place a piece of leather or hoglin hide into the table.
4. Hover over the finished product preview, or finish the item, place in inventory, then hover.

Result: Tooltip for the item has no insulation element on it.

Notes:
- Fur is the only insulation type I saw with this issue.  Successfully added leather and hoglin hide.
- Tested the tooltip issue with iron chest, boots, legs, and helmet.
- Checked the Cold Sweat configs as best I could, and didn't see anything different from a new curseforge modpack that used 1.19.2 and just Cold Sweat.
- Bugs are not present in a test curseforge modpack that only contains Cold Sweat.  Tested bug in creative mode, single player.

Happy to supply more info or do more testing.  Thanks!

### Operating System

MacOS Ventura 13.6.4

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk 21.5

### Optifine

No

**Comment by jack27121** [comment]
using leather is allowed. And will craft a new chest piece. BUT it doesn't show up as insulated, and doesn't seem to make a difference at all either

**Comment by CommanderTso** [comment]
I do think that leather works as an insulator, based on a test I did. I outfitted a full suit of iron armor with leather insulation and entered the Nether and saw how far my heat meter rose in 30 seconds. Repeated the test with a suit of non-insulated iron armor. With the insulation, my temp rose to only 12 in 30 seconds; with the uninsulated armor it rose to 22 or so.

**Comment by jack27121** [comment]
> I do think that leather works as an insulator, based on a test I did. I outfitted a full suit of iron armor with leather insulation and entered the Nether and saw how far my heat meter rose in 30 seconds. Repeated the test with a suit of non-insulated iron armor. With the insulation, my temp rose to only 12 in 30 seconds; with the uninsulated armor it rose to 22 or so.

okay, so it is only the "insulated" text that is missing, i'm guessing because of one of the other mods

**Comment by chorbintime** [comment]
report it to the author of the mod, please

**Comment by CommanderTso** [comment]
Hi @chorbintime. My assumption was that, since the modpack works in 1.19.2 with nothing else included, that the issue lies somewhere in Steampunk's configurations or the combination of modpacks it includes.  

Which means I expect the Cold Sweat author to turn right around and tell me it's a problem with the modpack. :)

**Comment by CommanderTso** [comment]
Additional info.  Just did a test where I:
* Took the Steampunk modpack and turned off every mod except Cold Sweat
* Created a new map in creative mode
* Dropped a sewing table and tried to stitch a piece of fur into it.  The bug repros, can't do it.
* The insulation bar does NOT disappear though - my assumption is that it's an issue with some other mod interaction.

In my original report, the fur bug does not repro if you create a clean profile and only add Cold Sweat to it.  Since the difference between these two tests (I assume) is that the test I just did has all of Steampunk's custom configs, etc., that the fur bug lies in the modpack somewhere.

If you folks are willing to look at this, I'm happy to redo the bug just to be about the fur, and see if I can nail down the issue a bit more cleanly regarding the UI element disappearing, and log that separately if I can.

**Comment by chorbintime** [comment]
The latest Cold Sweat update had a lot of changes and fixes - Could you try updating? If that doesn't resolve the issue, we can look into it for the next update. Thank you for the report.

**Comment by CommanderTso** [comment]
Very welcome! Happy to do so, I'll report back.
