### ISSUE TITLE
Intense fluctuating server lag

### ISSUE THREAD

**Issue by jack27121** [LunaPixelStudios/SteamPunk#164]
### Describe the Bug

Really bad server lag fluctuating at random times, checking with spark mob entities seem to cause problems more than they normally would
https://spark.lucko.me/rzJEzuoF0c
I've been guided by pebblehost support guys to report this, as well as getting rid of unnecessary mobs
this is whilst cpu and ram isn't overloaded

### Reproduction Steps

Make a server, play with friends, at some point you should experience fluctuating server lag

### Screenshots and Videos

https://github.com/LunaPixelStudios/SteamPunk/assets/46312671/76473ced-96ff-4a73-a3c3-2bc6edab47cf

### Operating System

win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v2.1.5

### Optifine

I used Optifine

### Other Mods

Spark (to make report)

**Comment by chorbintime** [comment]
It's probably just because you had a lot of sheep in a small area constantly colliding
