### ISSUE TITLE
Crash on Load; Fatal Error generating Java Runtime Environment

### ISSUE THREAD

**Issue by TheQuilledCoon** [LunaPixelStudios/SteamPunk#165]
### Describe the Bug

For reference The same issue happens on a few other modpacks from FTB but I can run other packs like FTB Stoneblock 3 just fine.

### Reproduction Steps

1. Download modpack
2. Click Run
3. Wait for crash to occur
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/162075894/18307547-1234-470f-b048-af68b5e6fc5c)

### Crash Report or Log

https://pastebin.com/EmqMZf9w

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

none

**Comment by TheQuilledCoon** [comment]
For reference I have already attempted
> Reinstallation of both FTB app, the Modpack, and Java.
> Restarting my computer
> Running launcher in Administration Mode
> Adjusting RAM allocation

**Comment by Emanatnawtnodi** [comment]
I had the exact same issue (problems with atio6axx.dll), from an older forum post i found that you had to update your AMD Software Adrenaline edition. I recommend going to the website and downloading and installing it (it will take a bit of time), afterwards the issue should be fixed.

**Comment by TheQuilledCoon** [comment]
> I had the exact same issue (problems with atio6axx.dll), from an older forum post i found that you had to update your AMD Software Adrenaline edition. I recommend going to the website and downloading and installing it (it will take a bit of time), afterwards the issue should be fixed.

This Worked! thank you for the help. Everything seems to be running right as rain now. very much appreciated.
