### ISSUE TITLE
Missing textures for some of the blocks

### ISSUE THREAD

**Issue by Shadowaxel25** [LunaPixelStudios/SteamPunk#167]
### Describe the Bug

I downloaded the modpack and everything is installed but when i start a new world and load in some of the the blocks have missing texture. Mostly grass blocks and oak logs, i've uninstall and redownload the pack but it's still broken.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-03-04_20 32 51](https://github.com/LunaPixelStudios/SteamPunk/assets/162244691/285da2a2-eebd-4303-b383-a8ba75e07145)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v21.5

### Optifine

No

**Comment by qwek1** [comment]
do F3+T

**Comment by Shadowaxel25** [comment]
Still didn't fix it

**Comment by chorbintime** [comment]
you didnt install the modpack correctly. reinstall on ATLauncher
