### ISSUE TITLE
Enginner's goggles don't work

### ISSUE THREAD

**Issue by Subrodai** [LunaPixelStudios/SteamPunk#169]
### Describe the Bug

My engineer's goggles don't show me any stat of the su or speed

### Reproduction Steps

1.It's an in-game bug
2. just launch and equip goggles
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk [LPS] 21.5

### Optifine

No

### Other Mods

Valhyrien Sky 2.2.0
Eureka
Clockwork

**Comment by chorbintime** [comment]
report it to the developers of the mod that adds the goggles
