### ISSUE TITLE
Server not starting on ubuntu 22.04 canonical 

### ISSUE THREAD

**Issue by p1k1p1k1** [LunaPixelStudios/SteamPunk#17]
### Describe the Bug

The server startup .sh file doesn't seem to work?

### Reproduction Steps

1.Launch the .sh file
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/145812939/a05d8600-3220-4dd8-a03a-59cc730ceb27)

### Operating System

Ubuntu 22.04 Canonical Server

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

### Optifine

No

**Comment by Frontear** [comment]
Please run the script via `bash` instead, it uses bash syntax making it incompatible on `sh`
