### ISSUE TITLE
Modpack crash on startup

### ISSUE THREAD

**Issue by ToGoodToWork** [LunaPixelStudios/SteamPunk#170]
### Describe the Bug

Hello!

I wanted to play Steampunk modpack but for some reason I cant get it to start up on my laptop... I tried common methods like updating drivers. java, setting priority on my GPU. Nothing helped... Other modpacks for example better MC is working fine.

Maybe someone here can help me?

### Reproduction Steps

1. Start Minecraft
2. Wait
3. Crash

### Crash Report or Log

https://gist.github.com/ToGoodToWork/c91d9ac75bf976ce9bccff49b831fdb1

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by qwek1** [comment]
update your drivers directly from your vendors website
