### ISSUE TITLE
Failed to interact with the world

### ISSUE THREAD

**Issue by KelvinKingGod** [LunaPixelStudios/SteamPunk#171]
### Describe the Bug

When I tried to open the door, the door will not open but instead of immediately close
Also I can't switch my hotbar
Moreover I can't open the inventory
All the blocks can't interact

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2024-03-08 221154](https://github.com/LunaPixelStudios/Medieval-MC/assets/100290289/d69b7d51-04fd-482e-b27f-5d77ec10f53d)
![Screenshot 2024-03-08 221541](https://github.com/LunaPixelStudios/Medieval-MC/assets/100290289/7a8f87be-53ba-4f79-bdac-2495fe795f8d)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
how did you install client/serverside?

**Comment by KelvinKingGod** [comment]
> how did you install client/serverside?

I downloaded on curseforge.
I was playing in singleplayer.

**Comment by chorbintime** [comment]
Can you record a video of the issue, please?

**Comment by KelvinKingGod** [comment]
okok
