### ISSUE TITLE
Blocks in Ulterlands dimension not dropping when Mined.

### ISSUE THREAD

**Issue by sasasasamj** [LunaPixelStudios/SteamPunk#172]
### Describe the Bug

Blocks in Ulterlands dimension not dropping when Mined by a Tetra pickaxe. the blocks still drop when exploded and plants drop when punched.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

N/A

**Comment by qwek1** [comment]
try using a calorite pickaxe

**Comment by TheEntomoid** [comment]
you must use vanilla tools or tools from the mod.
