### ISSUE TITLE
Alex's Mobs Fly doesn't spawn

### ISSUE THREAD

**Issue by TheEntomoid** [LunaPixelStudios/SteamPunk#173]
Flies are supposed to spawn when you kill zombies, but only Botflies spawn, and they do not drop maggots which are used to breed and tame various animals from the Alex's Mobs mod.

**Comment by chorbintime** [comment]
Flies still spawn naturally. The botflies are likely overriding the fly spawn - if you'd like, you could report it to the developers of the mod that add botflies and have it be a 50/50 for either a fly or botfly to spawn. You could also disable botflies in the badmobs-common config file.

We'll look into if botflies are useful at all for gameplay, and may disable them in a future modpack update.
