### ISSUE TITLE
Can’t get ingots (Steampunk [LPS] mod pack)

### ISSUE THREAD

**Issue by PowerFurr** [LunaPixelStudios/SteamPunk#174]
### Describe the Bug

Whenever I get the reward from the random ingots quest reward it doesn’t give me the ingots?

### Reproduction Steps

1. Complete a quest with a random ingot as a reward
2. See what it gives you
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/155801725/838ec118-5290-4b33-ada5-d517ce77ec11)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

On forge it says it was last updated on 1/21/2024 so whatever that is😅

### Optifine

No

### Other Mods

Falling trees
Multi mine
And u team core is it is not already in it

**Comment by PowerFurr** [comment]
My bad it's version 21.5 btw

**Comment by chorbintime** [comment]
see https://github.com/LunaPixelStudios/SteamPunk/issues/175#issuecomment-1996239017
