### ISSUE TITLE
Unknown Possibly Bugged Item

### ISSUE THREAD

**Issue by Quindite** [LunaPixelStudios/SteamPunk#175]
### Describe the Bug

{context)I downloaded the Steampunk mdd pack via cursed forged and joined it together with 'Essential' along with a critters mod.

(problem) progressed a bit through the quest book and found a couple of the quest give you random ingots however these ingots show up as a weird purple question box along with its 'codes' name. Is this intentional or can i fix this? 

### Reproduction Steps

1. Complete any quest giving ingots from ITR_rpg mod
2. Claim reward
3. reward being weird box
...

### Screenshots and Videos

![2024-03-13_09 52 24](https://github.com/LunaPixelStudios/Medieval-MC/assets/146197604/151925f1-9995-49f8-8e67-eff0bc6201ef)

![2024-03-13_09 41 01](https://github.com/LunaPixelStudios/Medieval-MC/assets/146197604/99a996bf-b1b0-4605-aad0-d75282e1262e)

### Operating System

Windows 11 pro

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/essential-mod

https://www.curseforge.com/minecraft/mc-mods/critters-and-companions

**Comment by PowerFurr** [comment]
I get the same exact thing, idk what's happening😅

**Comment by chorbintime** [comment]
Essential is incompatible and causes world corruption. Do not use Essential.

The issue above is just due to a mod we removed that we didn't remove the quest for. It will be fixed in the modpack update, you can ignore the item you received or just throw it away.
