### ISSUE TITLE
Create items disappearing

### ISSUE THREAD

**Issue by MarceloFreitasx** [LunaPixelStudios/SteamPunk#176]
### Describe the Bug

It's happened to me a second time, I'm playing normally and out of nowhere the game closes, when I go back in and check the chest, all the Create items are gone.

### Reproduction Steps

1. I don't know how to reproduce it, the first time I was riding a boat and the second time I went to sleep in bed

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
please provide logs from when the game closes
