### ISSUE TITLE
Shield wood issue

### ISSUE THREAD

**Issue by Damalas75** [LunaPixelStudios/SteamPunk#177]
### Describe the Bug

Minecraft wood like Spruce and oak planks can not to be used to craft a shield

### Reproduction Steps

1.Craft a shield with oak plank and/or spruce planks
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79496641/3e398147-850c-4c26-a42b-72462fb64ae6)

### Operating System

Win 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

43.3.5

### Optifine

No

### Other Mods

unedited

**Comment by chorbintime** [comment]
Is there another recipe available in JEI for shields?

**Comment by Damalas75** [comment]
no but it does show it accepts all other woods including BoP woods but not spruce an oak.

**Comment by chorbintime** [comment]
will be fixed in the next update. updating mods may fix it, and, if not, we'll make a datapack to fix it
