### ISSUE TITLE
Server crashes when getting hit by wither skeleton with thorns enchantment on

### ISSUE THREAD

**Issue by manuelmolinaf** [LunaPixelStudios/SteamPunk#178]
### Describe the Bug

Hosting a server with friends, When getting hit by a wither skeleton spawned by a Spirit Soul Cage with the thorns enchantment on my armor, the server crashes.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/bVK31X27

### Operating System

Docker Image eclipse-temurin:17-jre-focal

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

Simple Voice Chat
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat

**Comment by chorbintime** [comment]
Could you try unclaiming the chunk that the wither skeleton spawner is in?

**Comment by manuelmolinaf** [comment]
The chunks weren't claimed

**Comment by chorbintime** [comment]
We'll look into it for the next modpack update - shouldn't be a difficult fix. My guess is that updating mods will fix it, or it could be an issue with the soul cage mod.
