### ISSUE TITLE
Some sound event in the end caused client crash with null pointer exception error thrown

### ISSUE THREAD

**Issue by ethosylar** [LunaPixelStudios/SteamPunk#179]
### Describe the Bug

I just exploring the outer end island after defeating the ender dragon. Then I near some kind of purple biome with some vent pillar. The enderman start attacking me because of the cursed ring and there's some other mob that I can't identify. When im busy attacking the enderman inside of water, I got hit with the crash.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/EsgbWPvr

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by qwek1** [comment]
Remove the Presence Footsteps mod

**Comment by ethosylar** [comment]
> Remove the Presence Footsteps mod

it seems to fix the crash. thanks

**Comment by chorbintime** [comment]
report it to the developers of the Presence Footsteps mod
