### ISSUE TITLE
Oxygen tank not filling on Ad_Astra spacesuit

### ISSUE THREAD

**Issue by BaMango** [LunaPixelStudios/SteamPunk#18]
### Describe the Bug

The space suit can only be filled once with any attempts to refill it afterwards result in the oxygen being deleted from the oxygen loader

### Reproduction Steps

1. place, power, and fill an oxygen loader
2. place a space suit or oxygen tank in the oxygen loader; It should work as intended
3. repeat the previous step and new oxygen will not be able to enter the space suit.
4. I've tested this in creative with all 3 space suits from Ad_Astra
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v10

### Optifine

No

**Comment by SHXRKIIE** [comment]
I will have a look

**Comment by SHXRKIIE** [comment]
Will be fixed in next version
