### ISSUE TITLE
Missing Reward Item: Forest Ingot - after quest completion

### ISSUE THREAD

**Issue by abenyc** [LunaPixelStudios/SteamPunk#180]
### Describe the Bug

Playing SteamPunk [LPS], received one Forest Ingot as a random quest reward from crafting the skill book but it is missing. I recieved a purple "?" box in my inventory and when I hover over it, it states: iter_rpg:forest_ingot Missing Item FTB Quests. Item is not in JEI either when searching. Not sure if it's the modpack or Iter RPG specifically but wanted to give you a heads up. You may want to remove it from the random reward pool. 

### Reproduction Steps

1.Complete the skills book quest
2.recieve random reward
3.random reward Forest Ingot missing
...

### Screenshots and Videos

![2024-03-16_16 47 06](https://github.com/LunaPixelStudios/SteamPunk/assets/119062321/13248f29-2608-4f10-ad14-ab671c125cbb)
![2024-03-16_16 47 33](https://github.com/LunaPixelStudios/SteamPunk/assets/119062321/aeecf74b-1ae3-437f-9d46-c3d7b2275e10)

### Crash Report or Log

n/a

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

Added Mods
Controllable (Forge) - (controllable-0.18.0-1.19.2.jar)
FTB Backups 2 - (ftbbackups2-forge-1.19.2-1.0.23.jar)

Removed Mods
Spyglass Improvements (incompatible with Controllable)

**Comment by qwek1** [comment]
fill be fixed next update
