### ISSUE TITLE
"Improvable skills 3" unobtainable skills (bugged)

### ISSUE THREAD

**Issue by izenynn** [LunaPixelStudios/SteamPunk#181]
### Describe the Bug

Steampunk v21.5

There are some skills of this mod that aren't possible to obtain.

I noticed that there were some skills of this mod that should be obtained via mob drops/chests but JEI didn't show anything, so I went to a creative world to test and indeed some skills are bugged and can't be obtained.
I tested the same version as the one in the modpack (19.2.9) in a standalone profile and they are obtainable, so my guess is that the issues is with the modpack.

Edit: I checked the mod config and there are some skills disabled, but these ones are enabled in the config.

The bugged skils are:
- sharp arrow: skeleton drop (2.5%)
- extra health: end city chests (11%,[1]%)
- soul speed: piglin trade (14.5%)
And these are not tested by me, but a discord user said they were unobtainable also:
- luck of the sea
- huckster

### Reproduction Steps

1. N/A (Just enter a world)
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

No.

**Comment by chorbintime** [comment]
If you use the improved skills config from steampunk in your test world, does it still happen? If so, this would be a bug with the mod itself, and you should report it on their end.

**Comment by izenynn** [comment]
If I use the mod on a standalone installation it works properly, the issue seems to be only with the steampunk modpack :(

**Comment by chorbintime** [comment]
I meant if you use both the mod and Steampunk's improved skills config file - not just the mod by itself

**Comment by Holbryt** [comment]
sharp arrow is unobtainable because "undead unleashed" subscript the skeleton loot table entirely

**Comment by izenynn** [comment]
On standalone it works properly with the steampunk mod config file. As far as I remember, your config file just disabled one skill (the furnace one), so the rest should be obtainable yeah. :(
@Holbryt I don't know if the same could happen with the other skills, I have near no experience with mods tbh.

**Comment by tracehuber** [comment]
Huckster is obtainable. I got it just as the quest book and JEI specify.

**Comment by chorbintime** [comment]
> sharp arrow is unobtainable because "undead unleashed" subscript the skeleton loot table entirely

This should be reported to the Undead Unleashed developers


Improvable Skills seems to be an abandoned mod, with the last Github commit over 9 months ago. I'll look into getting a fork of it made to fix some of its issues. Thank you for the report.
