### ISSUE TITLE
Trying to energize Ad Astra items with the Create: New Age energizer crashes the game

### ISSUE THREAD

**Issue by tremenmusic** [LunaPixelStudios/SteamPunk#182]
### Describe the Bug

I was trying to automate energizing with create: new age. I decided to try to energize my Ad Astra Jet Suit with the create: new age energizer setup and it permanently broke the save. I could not load into my world. I had to open the world in Amulet and delete the create: new age energizer manually in order to get back into my save.

### Reproduction Steps

1. charge and apply rotation to a create: new age energizer
2. place an ad astra jet suit under the energizer on a belt
3. game crashes

### Screenshots and Videos

![energizersetup](https://github.com/LunaPixelStudios/SteamPunk/assets/42550819/c997ae52-5a78-4447-bc36-f8a335e88834)

### Crash Report or Log

https://pastebin.com/TcAu4xz4

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
please report it to the create: new age developers
