### ISSUE TITLE
Friend getting teleported when others teleport to waypoint

### ISSUE THREAD

**Issue by FacelessMuppet** [LunaPixelStudios/SteamPunk#183]
### Describe the Bug

We're currently 7 players playing oa a server. but when we are in combat and one of us teleports back to our ''deathpoint'' the same friend is always teleported to where we teleport to unintentionally. any help with this?

### Reproduction Steps

1.enter combat
2.die and teleport back to point of death
3.same friend gets teleported to where we teleport every time
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by chorbintime** [comment]
I'm not sure I understand what you mean by step 3 in the reproduction steps. Could you be more specific?
