### ISSUE TITLE
Conflicting recipe

### ISSUE THREAD

**Issue by xigasa** [LunaPixelStudios/SteamPunk#184]
### Describe the Bug

Not sure if this is the right place, I'm playing steampunk modpack. Computercraft's Ender Modem is un-craftable, when you craft in the workbench it gives you get Gilded Pearl from Unusual End.

### Reproduction Steps

1.Craft item in workbench
2.Craft item in create Crafter
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Latest

### Optifine

No

### Other Mods

What comes in the pack

**Comment by chorbintime** [comment]
Is there a polymorph button to switch the recipe?
