### ISSUE TITLE
infinite sugar cane

### ISSUE THREAD

**Issue by Mrmemzey** [LunaPixelStudios/SteamPunk#185]
### Describe the Bug

when placing a sugar cane you can spam place and break to get infinite sugar cane. I used normal sugar cane and not anything with a quality star. 

### Reproduction Steps

1.mine sugar cane
2.place normal no star sugar cane down
3.spam place and break
...

### Screenshots and Videos

https://youtu.be/3eYBmarqSEY

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

21.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
will look into it for the next update, thank you for the report
