### ISSUE TITLE
SteamPunk [LPS] 3.3.2 - Prism Launcher error 255

### ISSUE THREAD

**Issue by Jacklb101** [LunaPixelStudios/SteamPunk#187]
### Describe the Bug

When i try to load the modpack using the Prism Launcher, it begins loading on the "mojang" screen and then will crash.

### Reproduction Steps

1.Launch Modpack
2.Wait to load
3.Crashes
...

### Crash Report or Log

https://pastebin.com/tL0im2wJ

### Operating System

Linux (amd64) version 6.1.52-valve16-1-neptune-61

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v.3.3.2

### Optifine

No

**Comment by chorbintime** [comment]
Do you have an hs_err_pid file in your game files?

Does the issue persist on ATLauncher?

**Comment by Jacklb101** [comment]
> Do you have an hs_err_pid file in your game files?
> 
> Does the issue persist on ATLauncher?

Thanks for that ATLauncher, works perfectly!
