### ISSUE TITLE
Spawn rate really low

### ISSUE THREAD

**Issue by brouettelover** [LunaPixelStudios/SteamPunk#188]
### Describe the Bug

Hi,

I've a "bug" on the linux server version of the mod.
the spawn rates is really different from the solo.

There are 5 times more mobs spawned in single player than in multiplayer.

I just want to change the spawn rate. 

Specifications : 
- debian 12 lxc container running the minecraft server 21.5 (on a proxmox cluster)

### Reproduction Steps

1.Just launch the server with the (10G of ram) using the start.sh

### Operating System

Debian 12

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk LPS

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
This is just due to how servers work in minecraft. Multiplayer servers with several players have a lower spawn cap, while singleplayer isn't affected by this.
