### ISSUE TITLE
Bug finding wooden hammer for the mod tetra

### ISSUE THREAD

**Issue by Merydias** [LunaPixelStudios/SteamPunk#189]
### Describe the Bug

I wanted to start Tetra mode, I first had to craft a wooden hammer to change the crafting table, until then we are ok.
Except that when I type wooden hammer in I'm impossible to find it, except if I use "mod search". Also when I try to look for a trace of this wooden hammer I don't find anything in the quests or others.

In the hope you will find out this litle bug, thx for that modpack.

### Reproduction Steps

1.Craft a wooden hammer
2.
3.
...

### Screenshots and Videos

![Capture](https://github.com/LunaPixelStudios/SteamPunk/assets/19560414/db6bcc1c-1984-4f86-bee7-9bb43d73820d)
![Capture2](https://github.com/LunaPixelStudios/SteamPunk/assets/19560414/f7564804-557c-4ecd-a82f-0f775b2f45f2)
![Capture3](https://github.com/LunaPixelStudios/SteamPunk/assets/19560414/fefb3c72-727f-4d1f-9459-90d97ad55157)

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by chorbintime** [comment]
Most Tetra items do not show up in JEI. Please follow https://breezewiki.com/tetra/wiki/Getting_Started
