### ISSUE TITLE
game have crashed just by entering the world

### ISSUE THREAD

**Issue by ZztuiozZ** [LunaPixelStudios/SteamPunk#19]
### Describe the Bug

i was just starting the modpack and it was fine but when i entered my world it simply crashed and appeared 

### Reproduction Steps

1. entered the launcher normaly
2. started de modpack normaly
3. tryed to enter the world and crashed

### Screenshots and Videos

![bug](https://github.com/LunaPixelStudios/SteamPunk/assets/145863941/149ca11a-da34-4d2d-8d95-bd2f76f1ac99)

### Crash Report or Log

The game crashed whilst ticking block entity Error: java.lang.NoClassDefFoundError: Could not initialize class plus.dragons.createenchantmentindustry.foundation.advancement.CeiAdvancements

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11

### Optifine

No

### Other Mods

i didn't add anything

**Comment by SHXRKIIE** [comment]
Need crash report

**Comment by ZztuiozZ** [comment]
[crash-2023-09-23_13.49.36-server.txt](https://github.com/LunaPixelStudios/SteamPunk/files/12706996/crash-2023-09-23_13.49.36-server.txt)

**Comment by SHXRKIIE** [comment]
Update Create Enchantment Industry client and server or wait for v11.5

**Comment by ZztuiozZ** [comment]
thanks :)
