### ISSUE TITLE
Why cant i have essential.gg mod

### ISSUE THREAD

**Issue by chromczyt** [LunaPixelStudios/SteamPunk#190]
### Describe the Bug

I want to add the mod [Essential.gg](https://essential.gg/), this modpack adds only visual things and friends can connect to me remotely without using external programs for example ([hamachi](https://vpn.net/)). I think it's unnecessary for the modpack to tell me to remove the mods I've added and forbid me to create a sigleplayer or multiplayer game. With essential I can bypass these (hidden buttons) easily, so I don't think the developers of this modpack have figured it out.

### Reproduction Steps

Enable the [essential.gg](https://essential.gg/) mod

### Screenshots and Videos

![Screenshot 2024-03-26 004524](https://github.com/LunaPixelStudios/SteamPunk/assets/42711115/b7aa1b98-bea8-4ea8-ac73-84d2c5f51a9b)

### Operating System

Win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

[Essential.gg](https://essential.gg/)

**Comment by chorbintime** [comment]
Essential is completely incompatible and will cause world corruption. The modpack already comes with free one-click world hosting - just go into a singleplayer world and press the host button in the escape menu
