### ISSUE TITLE
Missing Quest reward.

### ISSUE THREAD

**Issue by ImLazuli** [LunaPixelStudios/SteamPunk#191]
### Describe the Bug

I received a missing item from the FTB Quests mod with the name “iter_rpg:forest_ingot”, i looked around in the iter rog mod and it doesn’t contain a forest ingot. Only 7 ingots can be found being; Ametrine ingot, Earth ingot, Air ingot, Fire ingot, void ingot and Elemental ingot.

### Reproduction Steps

1. I can crafted the Book of Skills
2. I went to claim the quest item in the FTB quest book (its a randomized reward)
3. I claimed the quest and received a missing item
...

### Screenshots and Videos

![IMG_3152](https://github.com/LunaPixelStudios/SteamPunk/assets/164963588/f7c5f4d5-68d8-4784-b387-b3f4157b8381)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V21.5

### Optifine

No

### Other Mods

Essential mod (basically lets you play Java in multiplayer without a server or realm.)

**Comment by chorbintime** [comment]
Essential is incompatible with the modpack and will cause world corruption.
