### ISSUE TITLE
Magmablock Crushing Recipe Conflict 

### ISSUE THREAD

**Issue by RemoonHD** [LunaPixelStudios/SteamPunk#192]
### Describe the Bug

Hi Lunar Pixel Team,
there is a recipe from the create mod that you can get netherrack from crushing magmablocks but create misc and things has a different recipe for crushing netherrack. Which is pretty useless stuff. It would be nice if you could remove that recipe. So that you can get netherrack from crushing magma blocks.
Thx a lot
Best regards
Chris 

### Reproduction Steps

1. through magmablocks into crushing wheels
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Current 

### Optifine

No

**Comment by chorbintime** [comment]
i'd suggest asking the 'create misc and things' developers

**Comment by RemoonHD** [comment]
Isnt it possible to change the recipe for modpack creators?
