### ISSUE TITLE
Nether ambient noises in overworld

### ISSUE THREAD

**Issue by chinberb** [LunaPixelStudios/SteamPunk#193]
### Describe the Bug

i saw a bug report for this that was resolved in January that was fixed by removing the scorched bronze guns mod, i figured that the mod owner would've fixed that by now but the ambience bug is still going on. i actually loaded that mod (Haywire Robots, Bandits and Guns- A Scorched Bronze Addon) in a new profile and found that it wasn't making nether ambience happen by itself, so i think something in the modpack is conflicting with it to make the nether sounds occur.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by chorbintime** [comment]
will look into it, might make a fork if the developer has abandoned the mod

**Comment by chorbintime** [comment]
its supposedly caused by sound physics remastered - should be fixed soon as the mod is being forked
