### ISSUE TITLE
Replace FLAN with FTB Teams

### ISSUE THREAD

**Issue by Xzidental** [LunaPixelStudios/SteamPunk#194]
### Describe the Bug

The FLAN menu doesnt support chunkloading and when playing on a server i would love to keep some farms chunkloaded when im offline.
And Toms Storage needs chunkloading to keep the terminal loaded so for a one player base its almost impossible to keep that without making a specific machine for it. Therefore i would believe FTB chunkloading is a better man for the job

### Reproduction Steps

-

### Screenshots and Videos

-

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

FTB Teams inplace of FLAN.

**Comment by chorbintime** [comment]
The modpack uses OPAC, not FLAN. OPAC already has a chunk forceloading feature. You can check the mod's documentation or mod page for mod information.
