### ISSUE TITLE
STEAMPUNK Goat Fur/Fur

### ISSUE THREAD

**Issue by Shadow-player** [LunaPixelStudios/SteamPunk#195]
### Describe the Bug

The sewing table from Cold Sweat doesn't accept "FUR" which is sheared from goats.
Chameleon Molt and Hoglin skin work fine.

 

### Reproduction Steps

1. Shear Goat
2. Open Sewing table
3. Attempt to use "Fur"
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
report it to the cold sweat devs

**Comment by Shadow-player** [comment]
I did they told me - Please take this up with the modpack authors. Their config settings for fur stuff are broken-MikulDev

**Comment by chorbintime** [comment]
will be fixed in the next update, thank you for the report
