### ISSUE TITLE
Catfish performance issue

### ISSUE THREAD

**Issue by AlexCatze** [LunaPixelStudios/SteamPunk#196]
### Describe the Bug

Catfish mob from Alex`s Mobs creates performance issues on the server. 

### Reproduction Steps

1. Play Steampunk modpack on the dedicated server
2. Notice that you have mobs moving like slideshow
3. Run `/forge tps` and notice that you have 9-12tps
4. Run `/spark profiler --interval 100` and notice that `EntityCatfish.tick` tooks 10-30% of tick time. One of profiling results: https://spark.lucko.me/UDjq9YBFBi
5. Disable catfish spawn in alexsmobs config
6. Kill all catfishes using `/kill @e[type=alexsmobs:catfish]` and see that command killed around 200 catfishes
7. Profile again. Now all is OK! https://spark.lucko.me/dMy2vW7FaL
8. Encount these piles of ~trash~ catfish drop

### Screenshots and Videos

![изображение](https://github.com/LunaPixelStudios/SteamPunk/assets/28355814/257dae2e-3e32-43d5-952c-8bc46726c018)

### Operating System

Windows 10(client) / Ubuntu _some version_ server

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk 21.5

### Optifine

No

### Other Mods

No

**Comment by chorbintime** [comment]
report it to the alexs mobs developers, please.
