### ISSUE TITLE
Create Belt and Woodworks Chest Texture randomly bugged

### ISSUE THREAD

**Issue by Aramid** [LunaPixelStudios/SteamPunk#198]
### Describe the Bug

On a random basis when loading/reloading a chunk containing Belt from Create or Chest from Woodworks, texture may be replaced by another block/item texture. Or sometime, some part of the belt will not be animated at all. Sometime even the whole belt, but the shaft always rotate properly. 
Gameplay wise, everything work as intended.

### Reproduction Steps

1. Play Steampunk Modpack in a singleplayer world
2. Place Belt from the Create mod (preferably multiple of them)
3. Unload the chunk by going in the nether
4. Reload the chunk by coming back from the nether
5. Check belt texture
...

### Screenshots and Videos

![2024-03-31_17 09 37_2](https://github.com/LunaPixelStudios/SteamPunk/assets/5508368/85e3e82c-b363-4d0b-b47b-eaef9601bb33)
![2024-03-31_17 16 38](https://github.com/LunaPixelStudios/SteamPunk/assets/5508368/b9593ed3-12b1-4fec-ad97-6137b59192e8)

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v21.5

### Optifine

No

**Comment by tetra184** [comment]
i have no texture at all for chests and also no textures for cogs too

**Comment by Hamsterhill** [comment]
I have had a the same issue, also phantom belts after a belt has been destroyed still staying visually.

**Comment by chorbintime** [comment]
theres currently some bugginess with tile entities that should be fixed in the next update. if the issue persists next update then make a new issue
