### ISSUE TITLE
Steampunk LPS Cant open modpack

### ISSUE THREAD

**Issue by enigmo22** [LunaPixelStudios/SteamPunk#199]
### Describe the Bug

I cant open steampunk but i think i should have powerfull enough pc to open it I have 16gb ram rtx 3050ti and amd ryzen 5000 something :D. i am using ATLauncher so i am pasting screenshots of the errors in console, I dont know what to do with them so thanks for any help!

### Reproduction Steps

just installed the modpack allocated 9gb of ram and i cant even run it, didnt add any mod or anything

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/165596303/b7750a48-6a63-4766-8429-919cf9cdcf77)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/165596303/c08d30dc-6730-4f55-9398-d7d1dad9af37)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/165596303/5c1920c1-2c99-44cd-b9c9-cdb47dca591f)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

**Comment by qwek1** [comment]
please send the full log

**Comment by qwek1** [comment]
yes thats correct, please update your drivers directly from your vendors website

**Comment by enigmo22** [comment]
I already have all of the drivers updated also checked with some 3rd party app called "Driver Updater"

**Comment by qwek1** [comment]
are you on a laptop or have integrated graphics?

**Comment by enigmo22** [comment]
yes I am on a laptop

**Comment by qwek1** [comment]
Your game is most likely using your integrated graphics causing it to crash

If your on an Nvidia GPU, then open Nvidia Control Panel > Manage 3D settings > Preferred graphics processor: to your GPU. 
If your using an AMD GPU then search up a guide on google on how to swap from your integrated graphics to your GPU.
