### ISSUE TITLE
 Eidolon Patches X Rubidium Crash?

### ISSUE THREAD

**Issue by Inteprise** [LunaPixelStudios/SteamPunk#2]
### Describe the Bug

like it says in the title

apparently you can try fixing it by

"Eidolon crashes with rubidium, you can turn off Better Layering in Eidolon's client config and it should work."

tho also look at the crash log

also apparently chants are just not working (and if you do manage to unlock it crashes you anyways) and you need to use commands so theres that too. (according the mod comments)

prob can just remove the mod from the pack? cause what i remember you need to chant to even progress so..

### Reproduction Steps

1. Open the eidolon book and click on the ritual of purifying or click on other things in the book?
2. Crash

### Crash Report or Log

https://mclo.gs/URfLNiA

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V4.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
If you are on SP then update the eidolon mod to latest to fix, it doesnt work on server though, so will probs remove this mod if the dev does not fix it soon.
