### ISSUE TITLE
Still having bug chunk load

### ISSUE THREAD

**Issue by Marsshiii** [LunaPixelStudios/SteamPunk#20]
### Describe the Bug

SO i've already made a post. And I was thinking the bug was fixed but with all the new release it's even worse
I can't go on exploration anymore. The chunk and so long to load, not every chunk load proprely. 

### Reproduction Steps

1. RENDER DISTANCE 4 
2. Low graphic
3. 11Go RAM
4.
5.
...

### Operating System

Windows 11 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v11.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
I have no issues loading chunks and they load fast, can you give me a spark profiler. Use this command: /spark profiler --timeout 30 and send the link.

**Comment by Marsshiii** [comment]
![image_2023-09-25_013817678](https://github.com/LunaPixelStudios/SteamPunk/assets/126317289/3851e56d-903c-481a-a199-0fa60889c675)

**Comment by SHXRKIIE** [comment]
no i need the link

**Comment by Marsshiii** [comment]
https://spark.lucko.me/Hyvn7QP1xj

**Comment by Marsshiii** [comment]
Here sorry, I wasn't loading chunk on the last one 

https://spark.lucko.me/Io7x4xgIPW

**Comment by SHXRKIIE** [comment]
The TPS from the profiler doesnt seem to suggest that there is much lag, you can try removing Recruits mod and see if that helps
