### ISSUE TITLE
Error when creating server

### ISSUE THREAD

**Issue by jario5615** [LunaPixelStudios/SteamPunk#201]
### Describe the Bug

When launching the server.sh keep getting this error: 

`Start script generated by ServerPackCreator 5.1.11.
To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file.

Running Forge checks and setup...
Generating user_jvm_args.txt from variables...
Edit JAVA_ARGS in your variables.txt. Do not edit user_jvm_args.txt directly!
Manually made changes to user_jvm_args.txt will be lost in the nether!
libraries/net/minecraftforge/forge/1.19.2-43.3.5/forge-1.19.2-43.3.5-server.jar present.

libraries/net/minecraft/server/1.19.2/server-1.19.2.jar present.

Starting server...
Minecraft version: 1.19.2
Modloader:         Forge
Modloader version: 43.3.5

Java args:         -Xmx4G -Xms4G
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt nogui
Java version:
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Microsoft-8905927 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Microsoft-8905927 (build 21.0.2+13-LTS, mixed mode, sharing)

Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <:> at index 70: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar
`
Does this for both 21.5 and 22HF

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by chorbintime** [comment]
please send the log file

**Comment by Falconosky** [comment]
maybe i can help u bcs i have this same issue
where logs are stored?

i have windows 10
and tested on few jdk

```
Start script generated by ServerPackCreator 5.1.11.
To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file.

Running Forge checks and setup...
Generating user_jvm_args.txt from variables...
Edit JAVA_ARGS in your variables.txt. Do not edit user_jvm_args.txt directly!
Manually made changes to user_jvm_args.txt will be lost in the nether!
libraries/net/minecraftforge/forge/1.19.2-43.3.5/forge-1.19.2-43.3.5-server.jar present.

libraries/net/minecraft/server/1.19.2/server-1.19.2.jar present.


Starting server...
Minecraft version: 1.19.2
Modloader:         Forge
Modloader version: 43.3.5

Java args:         -Xmx4G -Xms4G
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt nogui
Java version:
Picked up _JAVA_OPTIONS: -Xmx8192M
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)

Picked up _JAVA_OPTIONS: -Xmx8192M
Error occurred during initialization of boot layer
java.nio.file.InvalidPathException: Illegal char <:> at index 70: libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:libraries/cpw/mods/securejarhandler/2.1.4/securejarhandler-2.1.4.jar:libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar:libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar:libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar:libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar:libraries/org/ow2/asm/asm/9.5/asm-9.5.jar:libraries/net/minecraftforge/JarJarFileSystems/0.3.16/JarJarFileSystems-0.3.16.jar

Exiting...
Press any key to continue

```
