### ISSUE TITLE
Basalt Delta sounds still playing indoors in 22HF

### ISSUE THREAD

**Issue by wardenplays** [LunaPixelStudios/SteamPunk#202]
### Describe the Bug

There was an on-going issue prior to 22HF where the Basalt Delta sounds were playing all the time. Apparently the update was supposed to fix it, and while I don't hear it all the time now, I still get the sounds inside my house. 

I re-added Extreme Sound Muffler and muted anything with Delta in the name, but I'm still hearing the clicking noises.

### Reproduction Steps

1. Go into an interior, I am living inside a tinker's mansion
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

22HF

### Optifine

No

### Other Mods

I am getting it without any added mods, and Extreme Sound Muffler doesn't do anything

**Comment by chorbintime** [comment]
qwek will look into it for the next update
