### ISSUE TITLE
Quality Crops Downgrading 

### ISSUE THREAD

**Issue by Hamsterhill** [LunaPixelStudios/SteamPunk#203]
### Describe the Bug

Several recipe issues around Quality food items from Quality crops & Quality Delights.

Foods from the Quality Crops mods can be downgraded from Blue -> gold -> slilver -> vanilla but the ones from Quality's Delights Cannot. 

Sugar cane from quality Crop's is also bugged where it will craft down to silver but then across to silver sugar and not to the vanilla sugar cane, there doesn't appear to be any way to get blue or gold ranked sugar.

None of the quality crops versions of foods can be composted which can complicate what would otherwise be simple automated farms. 

### Reproduction Steps

1. Try recipe chains with carrots, tomatos & sugar cane
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

21.5

### Optifine

No

**Comment by qwek1** [comment]
please report this to the mod author.
