### ISSUE TITLE
Vanilla mobs too rare - Balancing issue

### ISSUE THREAD

**Issue by Hamsterhill** [LunaPixelStudios/SteamPunk#204]
### Describe the Bug

Not a bug but a balancing issue.

between Alex's mobs, enemy expansion & several others there are so many non-vanilla hostile mobs that Endermen and by extension Enderpearls are very rare.

I've been out hunting 6 in game nights in a row finding only 2 Endermen and getting only 2 Enderpearl fragments from each. so 1 pearl... getting to the end would solve this problem but getting enough  pearls to get there is going to be hard. 

They are in the loot tables for Strongholds but without pearls in the first place finding the strongholds will be impossible without cheating using the cave mode on the map. 

Increasing the chance of Endermen spawning or adding Enderpearls to more of the dungeon chest loot tables would  be ideal.

### Reproduction Steps

1.run game as normal and try hunt for endermen in overworld.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

I used Optifine

**Comment by qwek1** [comment]
Endermen can be found commonly in Warped Forests from Vanilla

**Comment by Hamsterhill** [comment]
Good point, I think I've had the same issue with the nether as i have explored 2000x1000 block area and have not seen a crimson or warped forest. 

I did just now realize that natures compass is in the pack so at least i know how i will be able to find one.

Thanks for the help. and for putting together the pack I'm really enjoying it.
