### ISSUE TITLE
Client crashes while joining server

### ISSUE THREAD

**Issue by blakevelderman** [LunaPixelStudios/SteamPunk#205]
### Describe the Bug

Today for the first time we had 3/4 of our players start crashing out while trying to join my server. I originally thought it was an issue with the latest update so I downgraded the server and had all players downgrade as well but the issue persisted. I had someone do a full reinstall from the curse forge launcher and I restored my mods folder from a backup but still no luck. 

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/jDqLG2th

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v21.5

### Optifine

No

### Other Mods

shutdowner

**Comment by qwek1** [comment]
Its an issue with the April Fools Globes from the Supplementaries mod, you might have to use a mod like blockswap to remove the Globes from your World, changing the date might help too since its an issue with the Aprils Fools thing from that mod

**Comment by blakevelderman** [comment]
well what do you know April 2nd and it works fine again
