### ISSUE TITLE
World is not generating

### ISSUE THREAD

**Issue by Bazinga944** [LunaPixelStudios/SteamPunk#209]
### Describe the Bug

I started to play steampunk a month ago, but after a week, my world is started acting weird. When i went to an ungenerated biom, it just doesnt load. I tryed to set my settings to the minimal, and i tryed the ATlauncher, but the issue is stil exist.
My guess is that maybe one of the mod is buggy 

### Reproduction Steps

1.Go to the world edge
2.
3.
...

### Screenshots and Videos

![2024-04-05_13 25 55](https://github.com/LunaPixelStudios/SteamPunk/assets/166328741/7c06114a-d859-49a3-90a3-3839f8ff76ee)
![Képernyőkép 2024-04-04 190002](https://github.com/LunaPixelStudios/SteamPunk/assets/166328741/161c2ee5-c0fd-401c-8595-a13debff93d8)

### Crash Report or Log

none

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk [LPS] v22hs

### Optifine

No

### Other Mods

nope

**Comment by chorbintime** [comment]
Please follow the performance guide: https://rpg.prominence.wiki/performance-guide
If the issue persists, provide your world save and the coordinates where the issue is happening.

**Comment by trizmark** [comment]
I've got the same issue and it looks like a problem with v22.
v21.5 is working fine with the exact same hw/settings/java version/etc.

My simple test:
- install v21.5, create new creative world, fly north. No issues whatsoever, was able to move continuously and the world was generating fine
- install v22, create new creative world, fly north. Immediate issues when reaching the edge if the pre-generated spawn area. No new chunks generated for about 20-40 seconds. CPU usage is way up. Once chunks generated, keep moving. Exact same issue again. New chunks take forever to generate, while something is hogging the CPU.

Replicated the same issue on my debian server and my windows desktop.

**Comment by chorbintime** [comment]
I would still suggest following the performance guide. 

The next update will have performance improvements.

**Comment by InfinityDevTech** [comment]
> I've got the same issue and it looks like a problem with v22. v21.5 is working fine with the exact same hw/settings/java version/etc.
> 
> My simple test:
> 
>     * install v21.5, create new creative world, fly north. No issues whatsoever, was able to move continuously and the world was generating fine
> 
>     * install v22, create new creative world, fly north. Immediate issues when reaching the edge if the pre-generated spawn area. No new chunks generated for about 20-40 seconds. CPU usage is way up. Once chunks generated, keep moving. Exact same issue again. New chunks take forever to generate, while something is hogging the CPU.
> 
> 
> Replicated the same issue on my debian server and my windows desktop.

I too have replicated this issue, I used `/spark profiler start`, and flew around for a bit, after a did `/spark profiler stop`, followed the link, clicked the mods tab, and removed a few performance hogs. Here is what I concluded:

- Remove "Alex's Mobs" and there was one more mob one I forgot the name of
- CTRL+F in the mods folder for "chunk", delete everything that shows up
- Follow [this performance guide rather than the crap one reccomended by chorb](https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks)

This is for a dedicated server of course, you can do a lot of the same thing on singleplayer.
This gets me a chunky result of 8 chunks per second, which is atrocious, but its better.

@chorbintime You guys need to get on this, as this makes the game very difficult to play.

**Comment by chorbintime** [comment]
The performance guide you linked is barely even a performance guide. Its an outdated guide for suboptimal java args.

Yes, unsurprisingly, removing major content mods is going to improve performance. This does not help anything - you're just making the pack worse. You should instead update them, as I've been working personally with many of their developers to improve performance and get bugs in their mods fixed.
