### ISSUE TITLE
game crashes because of pickable health orbs mod

### ISSUE THREAD

**Issue by NumiSquid** [LunaPixelStudios/SteamPunk#21]
### Describe the Bug

it worked perfectly fine previously; the game crashed once from a memory issue, presumably, and then it started outputting "java.lang.reflect.InvocationTargetException: null", caused by pickableorbs. 
a friend of mine's server and client also had create big cannons, but his game works perfectly fine

### Reproduction Steps

1. opened the game normally
2. game crash because of lack of memory
3. try to open the game again
4. pickableorbs has failed to load correctly
5. remove bigcannons
6. error persists
7. remove pickableorbs
8. game works now
9. readd bigcannons
10. game still works

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/145980450/ae7b64e5-b626-4c9b-b08f-9bb69cf7494b)

### Crash Report or Log

https://pastebin.com/nDRkCEDq

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Optifine

No

### Other Mods

previously create big cannons, but the error persists even when deleted

**Comment by SHXRKIIE** [comment]
Reinstall the modpack or use another launcher, not a modpack issue.
