### ISSUE TITLE
Cats and dogs keep spawning in my house

### ISSUE THREAD

**Issue by Notyourdadormom** [LunaPixelStudios/SteamPunk#211]
### Describe the Bug

Dogs and cats keep spawning in my house. My house is underground.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

### Other Mods

Create: Power Loader, Create: Liquid Fuel, Create: Factory, Trade Cycling, Do a Barrel Roll, FramedBlocks, MineColonies and The Essential Mod

**Comment by chorbintime** [comment]
Essential is incompatible and will cause your world to corrupt.
