### ISSUE TITLE
Only chest crafting option is incompatible with Sophisticated Storage Basic Tier Chest Upgrade quest reward

### ISSUE THREAD

**Issue by Hallows387** [LunaPixelStudios/SteamPunk#212]
### Describe the Bug

The default crafting option for a wooden chest is from the _Woodworks_ mod.
This chest is incompatible with the _Sophisticated Storage_ mod's _Basic Tier Upgrade_ item that you receive as a Quest Reward for the _Overworld: Craft a Chest_ quest.

As you are also unable to craft the vanilla minecraft _Wooden Chest_, to be able to use the upgrade you must instead craft a _Sophisticated Storage_ chest directly. 
This renders the _Basic Tier Upgrade_ item pointless.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
will be fixed in the next update

**Comment by bradleydragon** [comment]
still not fixed

**Comment by InkyQuill** [comment]
Can confirm as NOT FIXED on v23.5.

The issue can be circumvented for oak chest as woodworks oak chest can be converted to vanilla chest by placing it in crafting grid, but no luck with spruce. 

Had to disable woodworks chests in config.
