### ISSUE TITLE
JEI search bar unresponsive

### ISSUE THREAD

**Issue by VallinEMCSQ** [LunaPixelStudios/SteamPunk#214]
### Describe the Bug

Unsure as to how it started, but the search bar in the JEI menu is completely unresponsive. I am unable to select it with my mouse or type anything into it. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
update the JEI mod - if issue persists then report it to their devs
