### ISSUE TITLE
Essentials Addon doesnt work

### ISSUE THREAD

**Issue by AntifaHippoPrime** [LunaPixelStudios/SteamPunk#216]
### Describe the Bug

I cant get essentials to work with my friends and its forcing me to buy a server

### Reproduction Steps

1. Download Steampunk
2. Add Essential 1.19.2
3. Open and cry
...

### Operating System

Windows

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

### Other Mods

Essential 1.19.2 Forge

**Comment by Elay2306** [comment]
you can just press on host world and create there a world

**Comment by chorbintime** [comment]
The Essential mod is completely incompatible, as it's known to corrupt worlds and cause many other issues. The modpack already comes with free server hosting as Elay said above.
