### ISSUE TITLE
Create Steam and Rail Trains Freeze when going through chunks

### ISSUE THREAD

**Issue by ShiningSummer04** [LunaPixelStudios/SteamPunk#217]
### Describe the Bug

When going at any speed even backwards I have found that my train freezes ever now and then on certain chunk borders leaving the seat of the train will let the train keep moving and you will be kicked off a train 
Which chunk border it seems to freeze on is consistent but there is no pattern that I have come across sometimes its super close or really far from the previous ones 
the train will also disappear 

### Reproduction Steps

1. Create a straight line path for a few hundred blocks 
2. pilot a train down the path at any speed
3. I believe it will occur at any point 
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/SteamPunk/assets/167818289/82894be5-fdaf-4f0e-81ee-15718f2f5693

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk V22HF

### Optifine

No

### Other Mods

no mods were turned off

**Comment by chorbintime** [comment]
Update the Create: Steam and Rail mod if an update is available - if not, or if updating doesn't fix it, then report it to the mod author.
