### ISSUE TITLE
Sophisticated Backpack Configuration Error

### ISSUE THREAD

**Issue by GivenFlesh** [LunaPixelStudios/SteamPunk#218]
### Describe the Bug

The copper backpack is 5 rows of items and 1 upgrade slot, iron backpack is 4 rows of items and 1 upgrade slot, and the gold backpack is 5 rows of items and 1 upgrade slot.

### Reproduction Steps

1.Make a copper backpack and examine space
2.Upgrade copper backpack to iron backpack using 4 iron ingot recipe with copper backpack and examine space
3.upgrade iron to gold backpack and examine space
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22

### Optifine

No

**Comment by parmleyhunt** [comment]
Also removes inventory in those missing rows. Changing config for SophisticatedBackpacks does not do anything.

**Comment by chorbintime** [comment]
update the mod, and if the issue persists report it to the Sophisticated Backpacks developers - if changing the config doesn't fix it then its an issue on their end
