### ISSUE TITLE
enigmatic legacy amulet deleted items

### ISSUE THREAD

**Issue by refraud** [LunaPixelStudios/SteamPunk#219]
### Describe the Bug

when you die with a full inventory and armor +any trinket slots filled when pickup of death orb from amulet items that do not fit into your inventory anymore because items do not return to their equipped state on pickup so any excess is deleted and can not be recovered

### Reproduction Steps

1.fill inventory (with enigmatic amulet equipped)
2.equip armor + shield +any amount of trinket slots filled
3.die and collect death orb and items have been deleted
...

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

steampunk {lps} v22hf

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
The amulet will be replaced with a proper grave mod at some point in the near future. Thank you for the report.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions at this point. Do not expect support from any mod developers when Optifine is installed.
