### ISSUE TITLE
Structure errors generating world

### ISSUE THREAD

**Issue by Kiwicast** [LunaPixelStudios/SteamPunk#22]
### Describe the Bug

Large number of structure errors coming up in console when server starting

### Reproduction Steps

1. Starting the server
2. console brings large number or errors regarding structures
3.
...

### Screenshots and Videos

wouldnt let me send full log was too big for pastebin. if you would like me to send it just let me know how and will do so. but sent all the errors where they cameup during world creation.

### Crash Report or Log

https://pastebin.com/XxbfB9F1

### Operating System

Linux Dedicated Server

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v12

### Optifine

I used built in shaders that came with the modpack

### Other Mods

added no other mods

**Comment by SHXRKIIE** [comment]
Either remove pyrologernfriends mod or wait for next update
