### ISSUE TITLE
trouble with resourse-packs

### ISSUE THREAD

**Issue by IlayGrosu** [LunaPixelStudios/SteamPunk#220]
### Describe the Bug

1.Issues with Iron's Spells effect display, a lot of spells doesn't show their effects.
2.Some mobs do not displaying correctly on a hints screen.

sorry, my English may be bad, hope you'll understand me.

### Reproduction Steps

1. Launch SteamPunk[LPS] on a "Intel(R) Xeon(R) CPU E5-2680 v4", 1660 super, 16gb RAM
2. Add all resource-packs in order of their displaying.
3. Enjoy issues

### Screenshots and Videos

1.fireball does not makes field burning.
![2024-04-26_02 28 35](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/d950b718-3e7e-44ae-8ea9-c0822ee2e1d8)
![2024-04-26_02 28 35_2](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/b919282f-8d61-4238-9412-9d22f5e207aa)

1.1.fire breath does not displaying at all
![2024-04-26_02 28 51](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/dece3985-c681-4ba9-8745-2e0302954ab1)
![2024-04-26_02 28 52](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/a57384ae-f580-4af0-ad3d-3f0efd17d017)

(All of that spells work correctly, but does not displaying)
2.Chicken was invisible, but in game i can see it.
![2024-04-26_02 29 18](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/06854895-c376-4c95-8a36-c59e90538d42)
3.Added resourse-packs
![2024-04-26_02 38 07](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/d23eeb16-9fae-4b16-bc86-d93e3759e5c3)
![2024-04-26_02 38 21](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/af817e81-fef2-4364-806b-ac3c0605bd20)
![2024-04-26_02 38 26](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/5ecc94bc-92c2-4e83-90c5-a20e6a103275)

### Crash Report or Log

no

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

### Other Mods

MIneColonies
-BlockUI
-Struckurize
-Domum Ornamentum
![Снимок экрана 2024-04-26 025929](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/7374a71c-285c-4185-baad-bb2f27a4019c)
Chunkloaders
-supermartijn642corelib
-supermartijn642configlib
![Снимок экрана 2024-04-26 025257](https://github.com/LunaPixelStudios/SteamPunk/assets/168145151/578590fc-58e9-4d52-9d9b-efb0781063e9)
Light-overlay
Just-Zoom

**Comment by IlayGrosu** [comment]
I'm open to conversation in a Discord or Telegram "IlayGrosu".

**Comment by chorbintime** [comment]
Do not modify the resourcepack order ingame. Keep it as default.
