### ISSUE TITLE
Lead and Silver are not spawning

### ISSUE THREAD

**Issue by Dice2725** [LunaPixelStudios/SteamPunk#221]
### Describe the Bug

Lead and silver just aren’t spawning at any height

### Reproduction Steps

1. Start a world
2. Use advanced Xray to see for yourself
3. No silver and lead are found after hours of searching

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V22HF

### Optifine

No

### Other Mods

Advanced xray

**Comment by chorbintime** [comment]
what mods are these ores from?

**Comment by Dice2725** [comment]
Immersive engineering. Those ores spawn fine on an immersive engineering only world, so the issue lies in the modpack

**Comment by chorbintime** [comment]
will be looked into for next update. thank you for the report!
