### ISSUE TITLE
Thin Air Config Not Working

### ISSUE THREAD

**Issue by octobersgrave** [LunaPixelStudios/SteamPunk#223]
### Describe the Bug

So I had purchased a server through Bisect hosting, and I wanted to change the heights at which thinair began working, and I changed the thinair-common.toml and it simply didn't work. I didn't attempt to recreate this in singleplayer, but it may work there, not sure.

### Reproduction Steps

1. Change thinair-common.toml, the config for thinair
2. By default it is at 0 and 128, which is the safe Y levels for thinair. Change the values to whatever you wish, I did -12 and 148 respectively.
3. Then it simply doesn't change. I still suffocate above 128.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22hF

### Optifine

I used Optifine

### Other Mods

I didn't add any, just the base modpack.

**Comment by chorbintime** [comment]
Report it on the Thin Air github page
