### ISSUE TITLE
RyoamicLights (ryoamiclights) has failed to load correctly when starting up server

### ISSUE THREAD

**Issue by hflau99** [LunaPixelStudios/SteamPunk#224]
### Describe the Bug

Mod File: /data/mods/Ryoamiclights-0.1.5+1.19.2.jar
	Failure message: RyoamicLights (ryoamiclights) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
	Mod Version: 0.1.5+1.19.2
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER

### Reproduction Steps

1.
2.
3.
...

### Operating System

nas

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Are you using a server host? How are you hosting?

Did you use the serverpack files?
