### ISSUE TITLE
Chests Do Not Appear

### ISSUE THREAD

**Issue by CytricMoon** [LunaPixelStudios/SteamPunk#225]
### Describe the Bug

Chests do not appear in inventory or as a drop. Item is there and can be placed.

### Reproduction Steps

1. break chest
2. open inventory
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

22

### Optifine

No

### Other Mods

None

**Comment by CytricMoon** [comment]
it appears the Faithful texture pack has the issue as the chests can be seen after removing the texture pack

**Comment by chorbintime** [comment]
report it to the creator of the resourcepack please, they have a discord server im pretty sure

**Comment by stfy14** [comment]
you must be delete chest.jem from Fathless resource pack. he is located in the \assets\minecraft\optifine\cem direction. it worked for me
