### ISSUE TITLE
Netherite Space suit doesn't protect you in hot environments

### ISSUE THREAD

**Issue by BingusManLeftToenail** [LunaPixelStudios/SteamPunk#226]
### Describe the Bug

I had to entirely remove the temperature mod because a space suit designed for hot elements does not protect you from them. I've always disliked the temperature mod as its pretty unrealistic with how it tries to base its stats. I would like a huge buff to the netherite space suit as its just that, a netherite space suit forged from the literal depths of hell itself. Should probably not overheat in it. And its not like, a slow overheat overtime its just instant you're hot now.

### Reproduction Steps

1. Wear a netherite space suit
2. Go to a hot place (Nether, venus, mercury)
3.
...

### Operating System

W11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Latest

### Optifine

No

**Comment by BingusManLeftToenail** [comment]
I would like to add, the space suit ALSO does not apply to underground caves where O2 is low, which I understand isn't necessarily your fault but should be taken into account for sure. It kind of ruins the progression of the modpack and makes me feel like I can't really control what's happening to me. I would recommend either removing these 2 mods, or changing them to be more forgiving as at the moment the modpack feels like its coming to a hard stop. I can't solve any of the practical issues I have even though I'm at the point where I have netherite, plentiful resources, diamonds, etc. There isn't a clear direction in the quest books on where I'm supposed to proceed next to control my temperature/oxygen other than a rebreather which breaks over time. (I really do not want to be forced to craft rebreathers when I have advanced technology like a space suit)

**Comment by chorbintime** [comment]
will be looked into for the next modpack update, thank you for the reportZ!
