### ISSUE TITLE
Toms simple storage

### ISSUE THREAD

**Issue by Flyyinglotus** [LunaPixelStudios/SteamPunk#227]
### Describe the Bug

When doing anything involving the backpack the beacon buff doesnt work anymore

### Reproduction Steps

1.build a beacon within 8 blocks of the terminal
2.leave out of a 64 block range
3.move the wireless transmitter in youre inventory either to another slot or youre belt slot
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22

### Optifine

No

**Comment by chorbintime** [comment]
update toms simple storage - if issue persists then report it to their devs
