### ISSUE TITLE
Steampunk LPS Create Helmet and Backtank + Fireward Ring 

### ISSUE THREAD

**Issue by fstroobandt** [LunaPixelStudios/SteamPunk#229]
### Describe the Bug

I created a Netherite Diving Helmet and Netherite Backtank, thinking this would improve visibility underwater as it says it should in the tooltip.
I can not see any further underwater (even after adding Respiration).

Additionally, wearing Netherite pants from Iron's Spells is not compatible for the Lava immunity it should give.
When I do wear full Netherite base armour, the air drains properly in the lava.
Is it supposed to be drained if I have Lava Immunity (and Fire damage immunity) from the Spellstone "Blazing Core" and Fireward Ring?

Air is drained from the Backtank despite wearing a rebreather/using Air Bladders. 
Once the Backtank depletes, I have no ill effects from Thin Air. 
Having depleted air only has an effect when underwater (drowning).

The Fireward Ring gives immunity to Fire, but unlike the potion effect Fire resistance, it does not grant immunity to the nausea effects of ColdSweat from being too hot in temperature.

### Reproduction Steps

1.Craft a Copper Diving Helmet
2.Upgrade to a Netherite Diving Helmet
3.Add an Eternal Stellae
4.Enchant the helmet with Respiration 3 (Using a Blaze Enchanter)
5. Equip Netherite Boots, Netherite Leggings and Netherite Backtank (Enchanted with Capacity 3)
6. See no difference in visibility in Water, nor Lava.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
update the mods that add those items - if the issue persists then report it to their developers

**Comment by fstroobandt** [comment]
Chorbintime,

This is a cross-mod compatibility issue in the modpack, not an issue with the individual items. 
Thin Air, Create and Cold Sweat are not properly configured to take the other equipment from mods into account and I cannot find where I can add this compatibility in the config files. Cold Sweat does not take into account the fire and/or Ice immunity/resistance of Iron's Spells and I cannot find where to make it recognize this.

Could you assist with this?

**Comment by chorbintime** [comment]
Yes, its not something that can be configured. We would need to create a datapack ourselves to fix this, but thats not optimal as it's more of a compatibility issue with the mods themselves. It would be best if you reported it to the developers so it can be fixed for everyone that uses those mods.
