### ISSUE TITLE
Workbench no recipes

### ISSUE THREAD

**Issue by 59erzigi** [LunaPixelStudios/SteamPunk#23]
### Describe the Bug

I dont have recipes in the workbench when i search for a recipe

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot_6](https://github.com/LunaPixelStudios/SteamPunk/assets/146482353/f0306bbc-6a10-4c24-a61c-73c8fb2c048f)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V12

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
Use JEI to find recipes, not the recipe book.

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
