### ISSUE TITLE
Server crashes v22HF

### ISSUE THREAD

**Issue by SkyDuster16** [LunaPixelStudios/SteamPunk#230]
### Describe the Bug

Server crashes on start

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/SkyDuster16/f90c32bf5e32061b3467504954bd6e5b

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
How are you hosting the server?

Did you use the serverpack?

**Comment by SkyDuster16** [comment]
I just bought a server hosting for a month.
Not sure about the serverpack, there's just a whole section for installing modpacks so it's just downloading modpacks from CurseForge on its own.
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/165934322/6e6d9580-bc72-4d45-89af-c55f7f49eef0)

**Comment by chorbintime** [comment]
Its an issue with your server host. You get what you pay for, and you paid for a cheap host that doesn't work. You can contact their support team, but I doubt they'll do anything. 

My best suggestion is to ask for a refund and host a server on your PC using the serverpack, or just get a server from Bisect.
