### ISSUE TITLE
 Enginner's goggles don't work

### ISSUE THREAD

**Issue by kovalar20** [LunaPixelStudios/SteamPunk#231]
### Describe the Bug

The goggles of the create don't show any information about the create object It worked at the start of my world but now it don't work

### Reproduction Steps

1. install Steampunk mod pack  
2. launch the game and have nothing 

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk [LPS] v22HF

### Optifine

I used Optifine

### Other Mods

Valkyriens Sky 2.2.0
Eureka 
clockwork

**Comment by chorbintime** [comment]
Check keybinds - there may be a button you pressed to toggle it off
