### ISSUE TITLE
I can't start a linux server

### ISSUE THREAD

**Issue by VascoMartins01** [LunaPixelStudios/SteamPunk#232]
### Describe the Bug

Every time I try executing the .sh file, it doesn't execute properly.

### Reproduction Steps

1. Made  new user
2. Gave it sudo permissions
3. Downloaded modpack server files
4. Changed RAM at _variable.txt_ to 6 GB
5. Executed _start.sh_
6. It didn't work
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/72947542/767a49c1-9820-4448-aa83-a1f283e4ab91)

### Operating System

Raspberry Pi OS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by Frontear** [comment]
Hi, please run the script with `bash start.sh` instead. The syntax within the file uses bash syntax which `sh` cannot fully work with.
