### ISSUE TITLE
Basalt Delta ambient sounds heard in overworld

### ISSUE THREAD

**Issue by Jesse83005** [LunaPixelStudios/SteamPunk#233]
### Describe the Bug

Wherever I go in the overworld, I hear the geiger counter and explosion ambience from the basalt delta, I have not been to one yet, nor can I turn it down in the settings.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

steampunk v22HF

### Optifine

No

**Comment by qwek1** [comment]
this issue is being looked into, thanks for the report
