### ISSUE TITLE
Infinite rubber banding on server join

### ISSUE THREAD

**Issue by llAndrewll** [LunaPixelStudios/SteamPunk#234]
### Describe the Bug

After playing on a server for days with some friends, suddenly I am no longer able to move, I get rubber banded back to the same spot, and I can't break or place blocks

I've tried leaving and rejoining, restarting the server, restarting the server PC, and restarting my pc, 

1 other person has had this problem since she joined for the first time, and has been unable to play because of this, now, no longer can I

The only fix so far is to save the playerdata, remove it from the server, rejoin, and then replace the new playerdata with the old one. Which is tedious and has to be done at least once a day. 

Does anyone know what might cause this, or how one could fix it?

### Reproduction Steps

1. Join Server
2.????
3. Infinite rubber banding
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
How is the server hosted?

**Comment by llAndrewll** [comment]
it's hosted like a normal forge server on a machine running Debian
forge server with a bunch of mods
the normal linux script for steampunk didn't work
so i just had to make a forge server and replace the files with the ones from the server pack on curseforge

**Comment by chorbintime** [comment]
Please click this link and follow the guide. If you are using a server host such as Bisect, you may be limited in your options and instead have a checkbox to use Aikar's Flags, which will also work:
<https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks> 
If you can not launch your server/game after using these flags, then remove the word ``java`` from the start. Also, make sure you are using Java 18 on 1.18.2 / 1.19.2 and Java 11 on 1.16.5. These should be downloaded from Adoptium's website.

If lag persists, run the following command ingame:
``/spark profiler start --only-ticks-over 50``
Then, send the link in this channel. If the profiler command doesn't work, put [this mod](<https://www.curseforge.com/minecraft/mc-mods/spark>) in your servers mod folder
