### ISSUE TITLE
Opening Improvable Skills Blacksmith Ability Crashes Game

### ISSUE THREAD

**Issue by WilliamParoff** [LunaPixelStudios/SteamPunk#236]
### Describe the Bug

Every few times I open the Blacksmith ability from the book of skills in my inventory, the game freezes, only showing the lava in the background of the ability button then crashes the game and gives the following error:

Internal Exception: java.util.ConcurrentModificationException

From my experience, doing this 3-4 times will cause the error to occur.

### Reproduction Steps

1. Open Inventory
2. Open the Book of Skills through the inventory
3. Click on the Blacksmith ability
4. The game crashes
...

### Screenshots and Videos

https://github.com/LunaPixelStudios/SteamPunk/assets/95891491/3d63e9fc-0cdb-4ac3-951d-6d2e91f313d0

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
Please send the crash report file
