### ISSUE TITLE
Dragon has 92000 health this right?

### ISSUE THREAD

**Issue by Pultex** [LunaPixelStudios/SteamPunk#237]
### Describe the Bug

I feel this should not be on the first fight or EVER

### Reproduction Steps

1.Install update to newest version
2.play till you find all the EYES
3.open gate to end and just look at it's health
...

### Screenshots and Videos

Could not it killed me in one shot and the lightning with the fire

### Operating System

Widnwos 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v22HF

### Optifine

No

### Other Mods

Just what the packs adds

**Comment by qwek1** [comment]
92,000 is normal, the dragon was buffed. 

Make sure to find and level up the dense skin skill in the skillbook, it will help
