### ISSUE TITLE
Death screen showed twice & player model stuck dead

### ISSUE THREAD

**Issue by 08kingfisher08** [LunaPixelStudios/SteamPunk#238]
### Describe the Bug

Whenever I died, the death screen would show twice, so it would register that I died twice, and my player model would be stuck jittering and tinted red. This happened twice, and I don't know what's causing it.
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/68713631/f19abf7b-ac3a-4981-9a43-36c45f06df91)

### Reproduction Steps

1. Go into world
2. Die (I died both by a creeper and then by using /kill, both produced the bug)
3. Press respawn
4. Death screen pops up again
5. Press respawn
6. Player animation messed up
7. ?????

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

### Other Mods

No other mods used, and I launched through ATLauncher.

**Comment by qwek1** [comment]
it will fix if you relog, its a known issue thats being looked into
