### ISSUE TITLE
Mr.Craymans GunMod reload bug

### ISSUE THREAD

**Issue by LittleFuchsi** [LunaPixelStudios/SteamPunk#239]
### Describe the Bug

Double option, where 2 controls are for reload weapons. When u change one of them, the other switches too and they block each other out.

### Reproduction Steps

1.options
2.controls
3.key bind
4. Search for "reload"
5. set keybind
6. get a Mr.Crayfish weapon and try to reload

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

I used Optifine

**Comment by qwek1** [comment]
Thanks for reporting, will look into it.

**Comment by LittleFuchsi** [comment]
after some testing i found out what the problem was. I tried to reload while i had the ammuntion bags in inventory (not the ammunition itself). After i crafted them back to the bullets i was able to reload.
