### ISSUE TITLE
compatibility with Rubidium

### ISSUE THREAD

**Issue by Elorvex** [LunaPixelStudios/SteamPunk#24]
### Describe the Bug

When i add Rubidium to the pack it can't turn on the game

### Reproduction Steps

1.add Rubidium to pack
2.start the game
3.
...

### Crash Report or Log

https://paste.crystal-launcher.pl/v/43dd66b0ed693ae7a0e2935a1984aa03/30-09-2023/09.17.46.log

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v12

### Optifine

No

**Comment by SHXRKIIE** [comment]
Why are you adding it? It already uses a rubidium alternative
