### ISSUE TITLE
Tom´s Simple Storage Mod

### ISSUE THREAD

**Issue by LittleFuchsi** [LunaPixelStudios/SteamPunk#241]
### Describe the Bug

I made the "Tom´s Simple Storage Mod" system and it worked fine. But after i made more and more chests and connected all to the system with the Inventory Connector blocks the numbers in the system bugged. Like i put 1 dragon head into the system, its showing that i have 15. After i took out the 1 head, all 15 dissapeared. Like its a visual bug but its annoying bc u cant rly tell how much u got from 1 item.

### Reproduction Steps

1.Place like 10 Inventory Connecter
2.Place chests on them and connect everything with them system
3.Put Items into the system
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
Please send a screenshot of your storage setup

**Comment by LittleFuchsi** [comment]
![Bild_2024-05-09_103552535](https://github.com/LunaPixelStudios/SteamPunk/assets/168975647/82700751-e3fb-4e2a-bda8-cc0bdac6fd35)

this is only small for demonstration bc i broke the whole system down. But when im put 1 item in now the system say that i got 13

**Comment by nvb-uy** [comment]
You don't need to place 10 connectors. Only place one and then connect the chests between each other and the connector itself. Chests will connect between each
