### ISSUE TITLE
 When player dies, it happens 2 times and player model stuck in dying animation

### ISSUE THREAD

**Issue by Enkvaros** [LunaPixelStudios/SteamPunk#242]
### Describe the Bug

I died and press the respawn, character teleported to spawn point and died again in an instant "you died" screen appears again, character model stuck at dying animation, everything else fine just a visual (sorry for video quality first video was50mb GitHub wants max10mb, trimmed and compressed twice)

### Reproduction Steps

1.die
2.hit respawn
3.hit respawn again
... pray for bug to happen
I don't know sorry

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/119643840/d27d6a78-c380-4631-a005-35bc71e70f04)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/119643840/198cfce5-7724-4c43-a563-41219d390caf)

https://github.com/LunaPixelStudios/SteamPunk/assets/119643840/83dc1703-d0dc-484b-9723-63beec4e74cb

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V22HF

### Optifine

No

**Comment by chorbintime** [comment]
can probably be prevented by adding https://modrinth.com/mod/forcecloseworldloadingscreen/

relogging should fix it as well
