### ISSUE TITLE
Carryon cauldron bug

### ISSUE THREAD

**Issue by felipersol** [LunaPixelStudios/SteamPunk#243]
### Describe the Bug

When picking up the Alchemist Cauldron from Iron´s Spells ´n Spellbooks with the carryon mod you stay with it on your hand forever placing infinite cauldrons and you won´t be able to play the game, you won´t get rid of it dying or entering spectator mode the only way i got rid of it was to take the Carryon mod from the mod folder

### Reproduction Steps

1.Go to a Alchemist Cauldron from the Iron´s Spells ´n Spellbooks 
2.Press Shift Right Click 

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
You can use the /carryon clear command to remove the cauldron.

The item will be blacklisted from carryon in the next modpack update.
