### ISSUE TITLE
Invisible item in the inventory (chests)

### ISSUE THREAD

**Issue by FeyKin** [LunaPixelStudios/SteamPunk#244]
### Describe the Bug

After breaking a chest (or just getting one from the creative inventory) it becomes invisible as an item in both on the ground and in the inventory 

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

Cant send the video but i got a screenshot
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/63870310/4bd06ea3-d5aa-46bf-b312-470662001fda)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by Gost-GitL** [comment]
My game has the same issue at first. Try to remove a series of Faithless texture packs, they trigger the error. Meanwhile, you can remove Tetra GUI as well, it's initially covered by faithless GUI. Nonetheless, if you want to retain the texture, one approach is using previous version of modpack.

**Comment by chorbintime** [comment]
Do not use an older version of the modpack either. You're just going to experience more issues.
