### ISSUE TITLE
Aurum chest has texture bug

### ISSUE THREAD

**Issue by Gost-GitL** [LunaPixelStudios/SteamPunk#245]
### Describe the Bug

When I tried to craft it, I found that it is a chest with vanilla texture and the proper chest above (in JEI ) does not have recipe.

### Reproduction Steps

1.check it in JEI
2.
3.
...

### Screenshots and Videos

![2024-05-13_13 01 43](https://github.com/LunaPixelStudios/SteamPunk/assets/109933665/2affc73c-a12c-40bc-9e4f-b9ea137cc10e)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
Will be fixed in the next modpack update.

**Comment by Gost-GitL** [comment]
> Will be fixed in the next modpack update.

the texture remains wrong in latest version 23.5
