### ISSUE TITLE
chunk can t generate

### ISSUE THREAD

**Issue by CristianPetre12** [LunaPixelStudios/SteamPunk#246]
### Describe the Bug

I can t explore nothing because chunks doesn t load.

### Reproduction Steps

1. Enter the world
2. Fly with my gyrodine 
3. At one point the chunks doesn t load anymore.
4. I saw this problem is 3000-4000blocks away from spawn.

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/165014574/21a2e6c6-474d-4f9d-a6aa-57fbc2c296f8)
Every time i have to wait 5-10minutes to load 1/2 chunks. Or i have to quit the game and re-enter the world for loading near chunks and so on, every time. 

### Operating System

windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by Gost-GitL** [comment]
you can alter 'chunk update thread'

**Comment by CristianPetre12** [comment]
Chunks don't load no matter what I do. I played modpacks with 300+ mods, and the chunks loaded pretty quickly, even when flying with an elytra. In this modpack, I can't even explore because the chunks don't load, let alone flying with an elytra, which is impossible.
The only option I saw from Chosen Architect is to pre-generate the chunks with a mod, but that takes 4-5 days in real time. This seems a bit inconvenient to me, instead of exploring myself.

**Comment by Gost-GitL** [comment]
Actually I saw my method from Chosen as well.
![Screenshot_20240514_220215_com brave browser](https://github.com/LunaPixelStudios/SteamPunk/assets/109933665/12950e69-f903-4808-96ce-ba498b9e2ac8)
In this pack, I have been to 10000+blocks to discover a 'bazaar' on a map from wandering trader and I eventually gave up because it's too far from base. During exploring, I met the same case in several times but it can be dealt with via this particular setting.
So when you have to wait chunks, try to constantly alter this setting(apply new threads number) instead of quitting game. Each time you alter setting is supposed to make some progress.

**Comment by CristianPetre12** [comment]
I would have liked a complete solution, without having to change this in the settings every time.

**Comment by Gost-GitL** [comment]
Could you view Aurum chest issue which I opened and check out in your games? (My graphic card was physically broken in afternoon, which is extremely depressing for me. Now I am eager to find something to do by my phone😬)

**Comment by chorbintime** [comment]
Please click this link and follow the guide. If you are using a server host such as Bisect, you may be limited in your options and instead have a checkbox to use Aikar's Flags, which will also work:
<https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks> 
If you can not launch your server/game after using these flags, then remove the word ``java`` from the start. Also, make sure you are using Java 18 on 1.18.2 / 1.19.2 and Java 11 on 1.16.5. These should be downloaded from Adoptium's website.

If lag persists, run the following command ingame:
``/spark profiler start --only-ticks-over 50``
Then, send the link in this channel. If the profiler command doesn't work, put [this mod](<https://www.curseforge.com/minecraft/mc-mods/spark>) in your servers mod folder


> Could you view Aurum chest issue which I opened and check out in your games? (My graphic card was physically broken in afternoon, which is extremely depressing for me. Now I am eager to find something to do by my phone😬)

This has nothing to do with the original issue.

**Comment by CristianPetre12** [comment]
I already tried a few options from there as much as I could understand or find a tutorial. It didn't solve anything. I also tried with this spark command and it still doesn't work; in fact, this time I even got a crash. 
[hs_err_pid5500.log](https://github.com/LunaPixelStudios/SteamPunk/files/15366342/hs_err_pid5500.log)

**Comment by chorbintime** [comment]
You are still running Java 17, and you did not provide a spark profiler.

**Comment by CristianPetre12** [comment]
First of all, I'd like to say that it's not my job to install or watch all sorts of videos to see how to install a different Java for Minecraft. Secondly, other modpacks of the same version work for me without any problems. I tried what you suggested with the spark command and it crashed my game. I won't try anything else, I won't play until it's resolved because I can't do anything on the modpack. Thank you and have a nice day.

**Comment by chorbintime** [comment]
If you refuse to run a profiler or provide any kind of logs then I have no way of helping you. Please do not ask for support if you do not intend on accepting help.
