### ISSUE TITLE
Immersive Engineering Projector not displaying

### ISSUE THREAD

**Issue by P-024** [LunaPixelStudios/SteamPunk#247]
### Describe the Bug

Whenever I select what multiblock structure I want to use in the Immersive Engineering projector, it doesn't display the structure I am trying to build like it supposed to. 

### Reproduction Steps

1. get IE projector
2. select a structure to build (example metal press)
3. projection not being casted
...

### Screenshots and Videos

File was too big to put in this box so here is a google drive link to the video of the issue
https://drive.google.com/file/d/1Jrq9rW0VDqO7BfbLQzaHiQBnojved_tC/view?usp=sharing

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

**Comment by chorbintime** [comment]
Update IE, if the issue persists then report it to their developers
