### ISSUE TITLE
witch grinder issues

### ISSUE THREAD

**Issue by awses88** [LunaPixelStudios/SteamPunk#248]
### Describe the Bug

idk if its steam punk or minecraft but witches cant move from fans, water or belts they move by em and then they find a area and just stick to it and when i go see why there all huddled  ive tried being invisble when they spawn ive tried placing the soul crystal that spawns them and then teleporting out before they see me and then even the one that would spawn later stay frozen and then when i go up to check they are without a issue for them fighting the fans or water like it aint shit and they just dont move from them but than can still be agroed 

### Reproduction Steps

1.spawn or use soul crystal cage to spawn witch 
2.have fans  and water and belts to to push em to a collection area 
3.hopefully they drop for ya but they dont for me 
ps im using the create fan and immersive engineering belts have tried create belts and water is just plain old water idk its wierd 
ps thank you for the mod pack me and buddy havin fun :)  oh also there invisible for me but not my buddy when they spawn this applies to everything out of the soul spawner there invisible for me but not my buddy prolly my side or just server issues not modpack issues but thought id let ya know any ways
...

### Screenshots and Videos

:)

### Operating System

windows11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22hf

### Optifine

I used Optifine

### Other Mods

steampunk lps modpack we also have the mod spark for the server just to help perfomance and preloading chunk when were offline but it was not running at the time of me testing out the witch grinder

**Comment by chorbintime** [comment]
if the fans arent pushing a specific mob, it'd be an issue with the mod that adds the fans. i'd recommend reporting this to their developers instead
