### ISSUE TITLE
Sophisticated Storage chests missing quick insert/extract buttons

### ISSUE THREAD

**Issue by EntityinArray** [LunaPixelStudios/SteamPunk#249]
### Describe the Bug

Sophisticated Storage uses custom UI that does not work with any other mods

### Reproduction Steps

1. Open Sophisticated Storage chest
2. No insert/extract buttons from Quark Inventory
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/18554021/eedf2419-cdad-43d4-9cf2-afcb3d78f133)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/18554021/c5e22c54-3a56-432d-926e-5ed9453d11f0)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

### Other Mods

FTB Ultimine
AppleSkin

**Comment by chorbintime** [comment]
Should be fixed in the next modpack update
