### ISSUE TITLE
Game crashes when entering server address

### ISSUE THREAD

**Issue by fishikles** [LunaPixelStudios/SteamPunk#25]
### Describe the Bug

I'm running a steamPunk server on port 8082 as a machine on my local network, but whenever I try and connect to it the client crashes with the attached error.
It crashes just as I'm entering the ip/port into the connection dialog.

### Reproduction Steps

1. Run a SteamPunk server
2. Launch the game on local machine
3. click multiplayer
4. click direct connection
5. enter ip and port
6. game crashes

### Crash Report or Log

https://gist.github.com/fishikles/b993c596950f817415b872dd3cde101c

### Operating System

Win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V13

### Optifine

No

**Comment by chorbintime** [comment]
might be an issue with the placebo mod's patreon capes - ask their developer or try disabling the patreon capes in the placebo mod config

**Comment by SHXRKIIE** [comment]
Launch the game and try again

**Comment by fishikles** [comment]
> Launch the game and try again

Not sure I follow, are you struggling to reproduce?
