### ISSUE TITLE
Modpack Page still has Villager Comfort in mechanics

### ISSUE THREAD

**Issue by OminousDiscovery** [LunaPixelStudios/SteamPunk#250]
### Describe the Bug

It still says villager comfort on the modpack page

### Reproduction Steps

just go on the modpack page and its under features

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/150559423/cb04764e-d032-47dc-a148-a42147204200)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

22.5

### Optifine

No

**Comment by chorbintime** [comment]
will be fixed later today
