### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by TheDarKnight727** [LunaPixelStudios/SteamPunk#251]
### Describe the Bug

Everytime I try to launch the game I just get the exit code 1

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

# A fatal error has been detected by the Java Runtime Environment: # #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff1c3b6280, pid=8036, tid=13500 # # JRE version: OpenJDK Runtime Environment Microsoft-8035246 (17.0.8+7) (build 17.0.8+7-LTS) # Java VM: OpenJDK 64-Bit Server VM Microsoft-8035246 (17.0.8+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64) # Problematic frame: # C  [atio6axx.dll+0x196280] # # No core dump will be written. Minidumps are not enabled by default on client versions of Windows

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

22.5

### Optifine

No

**Comment by chorbintime** [comment]
Update your drivers

**Comment by TheDarKnight727** [comment]
both my graphics drivers are up to date, please don't close this out until it's actually resolved
