### ISSUE TITLE
Sewing table doesn't accept insulation ingredients

### ISSUE THREAD

**Issue by trizmark** [LunaPixelStudios/SteamPunk#253]
### Describe the Bug

Since upgrading to 22.5 the Sewing Table (from Cold Sweat) does not accept the following insulation items:
- chameleon molt
- goat fur
- wool
It continues to accept leather, rabbit hide and hoglin hide.

As a test, I have created a new instance with MC 1.19.2, Forge 43.3.5 and Cold Sweat 2.3-b03c (to match the versions in the modpack) and everything is working as expected.

### Reproduction Steps

1. Craft sewing table
2. Try to add wool/goat fur/chameleon molt to the insulation slot
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

22.5

### Optifine

No

### Other Mods

No other mods

**Comment by trizmark** [comment]
Interestingly, if I create a brand new world, everything works fine. The world I am playing in was created with modpack version 21.5. The sewing table was working as expected in v22, but after upgrading to v22.5 I am facing the issue decribed above.

**Comment by chorbintime** [comment]
If the issue doesn't occur on a fresh install on a fresh world, there's unfortunately not much we can do. You can try reporting this to the Cold Sweat mod developer, though.
