### ISSUE TITLE
ColdSweat FTBQuest UI image paths are mismatched with ColdSweat namespace

### ISSUE THREAD

**Issue by OnARiverMadeOfEyes** [LunaPixelStudios/SteamPunk#254]
### Describe the Bug

/config/ftbquests/quests/chapters/thin_air__cold_sweat.snbt images are set using 'blocks' but namespace is 'cold_sweat/textures/block'

image: "cold_sweat:blocks/boiler_front_lit"
Instead of:
image: "cold_sweat:block/boiler_front_lit"

### Screenshots and Videos

![Screenshot_20240517_131949](https://github.com/LunaPixelStudios/SteamPunk/assets/80232435/1b4005d5-aeea-46b1-8680-21e616791e1a)
The working images are ones I replaced with 'block'

### Operating System

Linux

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22.5

### Optifine

No

### Other Mods

[Remove Mouseover Highlight](https://www.curseforge.com/projects/257007)

**Comment by chorbintime** [comment]
will be fixed in the next modpack update
