### ISSUE TITLE
Lockbolt doesnt show up.

### ISSUE THREAD

**Issue by Calaheim** [LunaPixelStudios/SteamPunk#255]
### Describe the Bug

Lockbolt doesnt show up in Recipe browser or in workbench. 

(Solutions is to put the create guns resource pack below the create guns scorched resource pack)

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/17907748/c7bc6d2e-5945-4775-b861-65d31019b5e9)

### Operating System

W11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v23

### Optifine

No

**Comment by chorbintime** [comment]
will be fixed in the next modpack update
