### ISSUE TITLE
Glitch Text crashes game when viewed with Advanced Tooltips

### ISSUE THREAD

**Issue by SoftboyMC** [LunaPixelStudios/SteamPunk#257]
### Describe the Bug

It kept happening in my game so I looked at the crash log and the first couple lines said something about tooltips so I installed a fresh instance of the modpack without all of my other mods and it crashed with Adv. Tooltips on.

Fixed by turning them off.

### Reproduction Steps

0. [Optional] Fresh install Steampunk [LPS]
1. Create new world, must be survival.
2. F3+h to turn on advanced tooltips
3. Search the Enigmatic Legacy mod tag with the @ symbol
4. Mouse over any item with glitch text
5. Crash
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

23 and 22.5

### Optifine

No

**Comment by chorbintime** [comment]
Please send the log file or crash report
