### ISSUE TITLE
Issue with custom hunger bar not loading properly after eating Forbidden Fruit, then rejoining

### ISSUE THREAD

**Issue by etherest1** [LunaPixelStudios/SteamPunk#259]
description:
-eat forbidden fruit(enigmatic legacy): new hunger bar acquired 
-leave world/close game
-open game/rejoin world
-behold! no special hunger bar

i have made sure configs never changed and i played around with the texture packs to no avail
minecraft version 1.19.2, i have tried on modpack versions 22, 22.5, and 23

**Comment by chorbintime** [comment]
Update the Enigmatic Legacy mod, and if the issue persists please report it to the mod author
