### ISSUE TITLE
Crash when exploring.

### ISSUE THREAD

**Issue by rdwulfe** [LunaPixelStudios/SteamPunk#26]
### Describe the Bug

So I've tried removing spark and modernfix, so I can see the real error. I often find that pyrologenerandfriends is producing a ton of errors... but there's also entityhang errors. I'm unsure what's causing them exactly, and the errors shown are not always what's bringing down the actual server. This happens in single player and in the serverpack, seen in both v12 and v13.

### Reproduction Steps

Just explore for a bit, it happens a lot.

### Crash Report or Log

https://pastebin.com/ihpjWJF2

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

### Optifine

I used Optifine

### Other Mods

I added nomowanderer and Panda's Tree Chopper, but it happens with or without them.

**Comment by rdwulfe** [comment]
Not sure why it tagged optifine, thought I clicked 'I do not use optifine', apologies.

**Comment by chorbintime** [comment]
Do you mean 1.20.1?

1.19.2 BMC v13 is very old - you should update to the latest version.
If you mean 1.20, then try without the enemy expansion mod.
