### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by Almalong1** [LunaPixelStudios/SteamPunk#260]
### Describe the Bug

Server hosted through bisect crashed several times in the span of an hour, I have no idea what is causing this crash. server is 5 players, all were within the same couple chunk radius. 

server does have 8gb of ram 2 more then the recommended 

adding crash log, we did remove pyrologger as it was causing some world gen issues.

we also did not update versions as when we attempted the cold sweat mod broke causing crazy swings in temp from block to block.

[crash-2024-05-22_02.53.16-server.txt](https://github.com/LunaPixelStudios/SteamPunk/files/15397572/crash-2024-05-22_02.53.16-server.txt)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

22hf

### Optifine

No

**Comment by chorbintime** [comment]
We offer no support whatsoever for old versions of the modpack.
