### ISSUE TITLE
Rendering issues with create items

### ISSUE THREAD

**Issue by total-snarf** [LunaPixelStudios/SteamPunk#262]
### Describe the Bug

Both the create Toolbox and train wheels sometime display all or partially black. The toolbox is inconsistent and changes every time a new toolbox is placed. The train wheels only happen when the train is constructed as a contraption.

### Screenshots and Videos

![2024-05-25_02 31 38](https://github.com/LunaPixelStudios/SteamPunk/assets/119135318/e67d545e-6f15-4a38-a25a-f7b87e71ded1)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v23.5

### Optifine

No

**Comment by Gost-GitL** [comment]
Enabling shader can reduce the occurrence, albeit not radically.

**Comment by chorbintime** [comment]
Can you try updating your drivers? We're unable to reproduce this.

**Comment by total-snarf** [comment]
> Can you try updating your drivers? We're unable to reproduce this.

Drivers are fully up to date. The issue also happens to the lids of chests that spawn naturally in the world.

The visual issues go away when using shaders, which I find strange.

**Comment by chorbintime** [comment]
Yeah, this is specifically an issue with drivers as far as I'm aware. I think theres a command like `/flywheel backend` that you could try finicking with, or you can check the driver vendor's website for the latest drivers, as sometimes the app won't have the latest
