### ISSUE TITLE
Chunk loading takes a long time

### ISSUE THREAD

**Issue by EpicBode02** [LunaPixelStudios/SteamPunk#264]
### Describe the Bug

When exploring the world chunks take a very long time to load. My PC is more than capable of handling high demand resource loading and I cannot figure out a solution to make chunks load faster. I've tweaked settings and have added mods to help with chunk loading. Some mods did help slightly, but the issue still persists and it makes it impossible to explore without having to pause and wait 3-5minutes every 8 chunks rendered.

Any advice to what I can do to resolve this issue?

### Reproduction Steps

1. Create a game
2. Play long enough to explore various parts of the world and rack up a lot of data
3. Attempt to explore out of your already explored regions
4. Witness terrible chunk loading times
5. Tweak settings with chunk loading, rendering, and culling blocks
6. Notice no difference
7. Download a pregenerating chunk mod to help
8. Notice very slight difference, but issue still remains
9. Research until you give up and create a github post
10. Wait for help

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF

### Optifine

No

### Other Mods

https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator

**Comment by chorbintime** [comment]
v22 is old. We offer no support for old versions. Please update the modpack to the latest version.
