### ISSUE TITLE
crash while hovering over icon in JEI

### ISSUE THREAD

**Issue by Ivanator2** [LunaPixelStudios/SteamPunk#265]
### Describe the Bug

I went into my inventory to look at the JEI and started to type into the search bar to find a specific item I wanted to access. I started typing "Blood" because I wanted to find "The Blood Staff" item. When i went and hovered over some icons, my game left the server and crashed the game shortly after. This is a visual bug seeing as the game couldn't render in the UI for said item. The item that crashes the game seems to be the head of an Axe. 

P.S.
Any item that has the format code of "Obfuscated" or §k and \u00A7k as the word changer in its name, JEI will crash and in doing so crash the entire game. The Enigmatic legacy items are the main sources of this issue.

### Reproduction Steps

1.Press E to enter inventory
2.Use JEI Search
3.Type "The Blood Stained"
4.Hover over Icon
5.Crash Game
...

### Screenshots and Videos

![2024-05-27_16 22 44](https://github.com/LunaPixelStudios/SteamPunk/assets/170979416/618e673b-f479-4bfc-83e5-a9c4ed182ed3)

https://github.com/LunaPixelStudios/SteamPunk/assets/170979416/b9bf4788-5913-45f7-9a33-82f3f662e23e
[crash-2024-05-27_16.24.01-client.txt](https://github.com/LunaPixelStudios/SteamPunk/files/15461618/crash-2024-05-27_16.24.01-client.txt)

### Crash Report or Log

https://pastebin.com/N44XK4mb

### Operating System

windows 10

### Minecraft Version

1.19.2

### Modloader

Forge-43.3.5

### Modpack Version

V23.5

### Optifine

No

**Comment by qwek1** [comment]
will be fixed in the next update
