### ISSUE TITLE
Server crash loop of death

### ISSUE THREAD

**Issue by TheoSGGH** [LunaPixelStudios/SteamPunk#267]
### Describe the Bug

Server has begun to crash repeatedly when a player joins, has started lagging before anyone joins as well. This wasn't an issue up until about a day ago. Server has 6gb of ram and has been a little laggy here and there but nothing detrimental up until this point. Crash log is included, but says it isnt a memory issue. Help!

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/cz5yK6Mh

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v22HF and v23.5

### Optifine

No

### Other Mods

Just the default pack + any updates since 22HF (unsure if optifine is in there by default)

**Comment by chorbintime** [comment]
Set maxticktime to -1 in server.properties
