### ISSUE TITLE
Craft guns  RailWorker could crash game 

### ISSUE THREAD

**Issue by nnwduong** [LunaPixelStudios/SteamPunk#269]
### Describe the Bug

today i try to craft guns RainWorker, in workbench i try click at Assemble button  then the game save a get crash. 

### Reproduction Steps

1.n/a
2.
3.
...

### Screenshots and Videos

SteamPunk v23.5 -- Tlaucher v2.935

### Crash Report or Log

https://pastebin.com/pnwvTb4f

### Operating System

Window11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

LPS v23.5

### Optifine

I used Optifine

### Other Mods

n/a

**Comment by chorbintime** [comment]
Update the MrCrayfish Guns mod. If the issue perists, please report it to the mod's Github page.

**Comment by nnwduong** [comment]
ok i fixed it
