### ISSUE TITLE
Crash in Skeleton Farm

### ISSUE THREAD

**Issue by B4rc1** [LunaPixelStudios/SteamPunk#27]
### Describe the Bug

We played the pack in v10 upgraded to v13.
We have a skeleton mob and XP farm on our server and since the upgrade sometimes an entity spawns that crashes the server repeatedly until we kill all entities multiple times.

We have tried removing the enemy expansion mod to no avail.

### Reproduction Steps

This is how we can reproduce it semi regularly (happened two times already, not always when we use the mobfarm)

1. Build large skeleton Farm
2. Stand in the Farm for some times
3. Engage in Mob Combat
4. ???
5. Server crash

### Crash Report or Log

https://pastebin.com/3PrZ9m9J

### Operating System

NixOS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v13

### Optifine

No

**Comment by B4rc1** [comment]
After Downgrading to v10 again, this problem seems fixed (we copied the world over where the server crashes as soon as my friend joins and the mob is loaded)

**Comment by chorbintime** [comment]
Update to the newest version of the modpack again. You can run /kill @e[type=skeleton] to fix the issue temporarily.

To help us solve the issue, you can make a backup of your world and remove the following mods:
- Supplementaries
- Xaeros Minimap
- Open Parties & Claims

Tell us if this fixes it, and send new logs if the issue persists.

**Comment by B4rc1** [comment]
Without supplementary: (Had to remove idas-forge, integrated-stronghold as well since the game would'nt start otherwise) the server would not start because of datapacks. The `world/datapacks` folder is empty tho??.
log: https://pastebin.com/SRp78h8z

Without Xaerox Minimap: https://pastebin.com/73RvVYs3

Without Open Parties & Claims:  https://pastebin.com/e2A60WyV

Here is a full server download so you can test the issue locally: https://drive.google.com/file/d/1sQd4f5EmVnmP0YiFQcjw90uBMzzHEyMM/view?usp=sharing. 
The coordinate of the skeleton can be seen from the crash logs.

**Comment by chorbintime** [comment]
Make sure you removed any of Supplementaries' addon mods.

Datapacks are stored in config/paxi

**Comment by SHXRKIIE** [comment]
See if v14 fixed it for you

**Comment by B4rc1** [comment]
I cant reproduce it on `v14` although I did not thoroughly test it. We decided to just stay on `v10` and customize the pack to our liking.

Thanks for the great pack btw :)

**Comment by chorbintime** [comment]
do not use old versions of the modpack, you will experience major issues
