### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by DeathDasity** [LunaPixelStudios/SteamPunk#270]
### Describe the Bug

Whenever I try to launch the modpack, it tells me that the game crashed

### Reproduction Steps

1. Launch the modpack
2.
3.
...

### Screenshots and Videos

![image_2024-06-02_162011040](https://github.com/LunaPixelStudios/SteamPunk/assets/109002157/1ac1d184-fe1f-4d34-80a3-61552ef39539)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

23.5

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
you need to send the latest.log file, or the hs_err_pid file if present. we can not help without it

**Comment by DeathDasity** [comment]
My apologies, here is the latest.log file
[latest.log](https://github.com/user-attachments/files/15596471/latest.log)

**Comment by cageystorm818** [comment]
I have the same issue but for me its the incompatibility between create and flywheel saying it needs flywheel 6.10, but i cant find the download for it anywhere as curseforge only carries 6.8

**Comment by chorbintime** [comment]
This is not an issue with the modpack. The modpack launches completely fine, and if you're getting a dependency error its because of something you did.
