### ISSUE TITLE
Single Chest Texture Issue

### ISSUE THREAD

**Issue by rb19006** [LunaPixelStudios/SteamPunk#272]
### Describe the Bug

Every Wooden Single Chest has an odd texture, (see ss below) when as a single chest, the texture for a double chest is normal however. It doesn't happen every launch and I'm not sure what the factor is that determines if the bug will occur but it happens often enough to be a noticeable bug.

### Reproduction Steps

1. Place Single Chest
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/128544629/d77c3c61-7729-474b-aa9e-64ec37ed79e1)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/128544629/a718af36-b875-4d2c-ae28-fe4a1839d82b)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v23.5

### Optifine

I used Optifine

**Comment by qwek1** [comment]
reloading your game should fix the issue.

To reload textures and sounds, press F3 + T. If this doesn't bring up a loading screen, do the following:
1. Press escape and go to the Resourcepacks tab.
2. Move a Resourcepack on the left of the screen to the right. 
3. Move that SAME Resourcepack back to the left. 
4. Exit the menu. 
If step 4 does not bring up a loading screen, do step 2, then step 4, then step 3, and then step 4 again.

**Comment by mycroftjr** [comment]
This is not an Optifine issue as it also happened to me, but reloading did fix it.
