### ISSUE TITLE
MrCrayfish gun attachments not acting as intended

### ISSUE THREAD

**Issue by BungoDiggity** [LunaPixelStudios/SteamPunk#273]
### Describe the Bug

both medium and long scopes zoom in significantly more than expected making them unusable. 

### Reproduction Steps

1. attach a scope to a gun 
2. aim down sights
3.
...

### Screenshots and Videos

https://www.reddit.com/r/feedthebeast/comments/1d6sbm0/problems_with_mrcrayfishs_gun_mod_in_steampunk/

### Operating System

Windows 10 

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v23.5

### Optifine

No

### Other Mods

https://www.reddit.com/r/feedthebeast/comments/1d6sbm0/problems_with_mrcrayfishs_gun_mod_in_steampunk/

**Comment by qwek1** [comment]
try updating the create guns resourcepack
