### ISSUE TITLE
"Obtain a Different Sword" quest dependencies are wrong

### ISSUE THREAD

**Issue by mycroftjr** [LunaPixelStudios/SteamPunk#274]
### Describe the Bug

The quest to "Obtain a Different Sword" (0429C044EEC4798B) currently has the Horizonite Forge and Alchemy Table as required quests, but they have nothing to do with getting the sword.

The sword is found in the Spider Boss' uncommon loot bags (7.5% chance) or rare bags (15% chance), so the quest should be a dependent of 3D3E7DEDD472B497 ("Defeat the Arachnarch") instead.

ALSO, since the sword is so rare and probably not even that useful (I don't think you can even get rare bags on the pack's default Easy difficulty...) it should probably either be made more common, have a different way of getting it added (like the Alchemy Table) or the quest be removed.

### Screenshots and Videos

![2024-06-05_16 44 15](https://github.com/LunaPixelStudios/SteamPunk/assets/33704388/c95dd88c-6395-4779-835d-7bf08a285586)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

23.5

### Optifine

No

### Other Mods

OAuth

**Comment by chorbintime** [comment]
Will be fixed in the next update
