### ISSUE TITLE
JEI: Rendering Screen Crash

### ISSUE THREAD

**Issue by LilEggie** [LunaPixelStudios/SteamPunk#275]
### Describe the Bug

I was searching for `sack` in JEI to look up the recipe. All of sudden, both my game and Prism Launcher freezes, followed up by a crash.

### Reproduction Steps

1. Open inventory
2. Search for `sack` in JEI search bar
3. Hover over the `sack` item icon
4. Game freezes, then crashes

### Crash Report or Log

https://pastebin.com/CYkMWtCZ

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v23.5

### Optifine

No

**Comment by EggieVAL** [comment]
Just discovered that crafting a `sack` crashes the game as well.

1. Open crafting table
2. Place 7 flax and 1 string as per the `sack` recipe
3. Try to grab the `sack` from the output

**Comment by EggieVAL** [comment]
Another comment... hovering over a `sack` in your inventory also crashes the game. Safe to assume that hovering a `sack` anywhere is bad.

**Comment by chorbintime** [comment]
What mod is the item from?
