### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Ratra-Boy** [LunaPixelStudios/SteamPunk#277]
### Describe the Bug

My game was working fine for over 2 weeks but today i kept on crashing and regressing back in time and some items even disappeared after every crash.

### Reproduction Steps

1. I craft some gear boxes 
2. Connect a mixer
3. Make some Brass
4. Place down logs and strip them
5. Make some bass casing
6. Break the Brass casing
This is the point at which i crash; I rejoin and find myself back to the point before i crafted the gear boxes.
But at the last crash when i rejoined the items that i crafted the gear boxes with disappeared as if i already crafted them .
Btw i have done all this before and made many contraptions. 

### Crash Report or Log

https://mclo.gs/x16Hj33

### Operating System

windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v22HF

### Other Mods

Nature's compass but that was ages ago

**Comment by qwek1** [comment]
This is an issue with Create, should be reported to them instead
