### ISSUE TITLE
Items Disappearing 

### ISSUE THREAD

**Issue by Kxiiss** [LunaPixelStudios/SteamPunk#278]
### Describe the Bug

At first, I was worried I had lost my enchanted diamond pickaxe and axe, but then I found them in my toolbox stacked with my hammers. When I clicked the return all button, it stacked them. Then my Iron Backpack disappeared and I have no idea where it went.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v22HF

**Comment by chorbintime** [comment]
report it to the author of the backpack mod please
