### ISSUE TITLE
World's not showing ingame

### ISSUE THREAD

**Issue by PhillipDaPaster** [LunaPixelStudios/SteamPunk#279]
### Describe the Bug

i was playing perfectly fine last night now it doesn't show the world in my game this is the second time it has happened and i have no clue why i spent around 20 hours on this lastest world so im kind of upset if anyone knows any ways to fix this it would be great

im using curseforge 

### Reproduction Steps

1.i dont know how to reproduce this bug only thing i can think of is waypoints but that wouldn't cause the game to not show my world
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/49299203/cc918ee8-a527-4c32-b1b9-7773453af8fa)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/49299203/73cea672-496f-43a0-a5d1-2c64199c6711)
the second screenshot is all of my world saves porch was the original one which did not show and i thought it didnt matter that much i had only spent 5 hours in it and i made a new world hoping nothing would happen but the same bug occurred if you need the download for the worlds i will send that aswell 

### Operating System

windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v21.5

### Other Mods

i added tinkers construct on the second world on the first this happened on i added nothing its a issue inside of the pack

**Comment by chorbintime** [comment]
send a screenshot of the contents of your world save, or put it in a zip file and upload it somewhere

**Comment by PhillipDaPaster** [comment]
> send a screenshot of the contents of your world save, or put it in a zip file and upload it somewhere
i fixed it by doing this fix 
- https://youtu.be/e38az5N1coQ?si=0u2bbdpjg5kQGP8m

but i found out its from the waypoint system when i place a waypoint theres a chance it will corrupt saves no idea what its from but i just removed waypoints
