### ISSUE TITLE
Vanilla arrow recipe is missing

### ISSUE THREAD

**Issue by Gallichron** [LunaPixelStudios/SteamPunk#28]
### Describe the Bug

It is not possible to craft a vanilla arrow unless you use a Cockatrice Rib and Skyroot Stick from the Aether mods.

The normal recipe-- Flint, a stick, and a feather-- does not appear in the JEI panels, nor does function when you try to place these items into a crafting table manually.

I am concerned that there may be other recipes that I'm missing as well; that's the only one I tried using and realized was missing so far.

This issue occurred in V12 of the modpack, and is persisting in V13 as well.

### Reproduction Steps

1. Start a normal game.
2. Gather 1 flint, 1 stick, 1 feather.
3. Place in the crafting table such that it matches the vanilla formula for an arrow.
4. You SHOULD be given the option to craft arrows, but INSTEAD will see no option to craft anything.

Alternatively:
1. Start a normal game.
2. Go into the JEI menu from one's inventory.
3. Search 'arrow'. Click the arrow item.
4. You will not see the vanilla arrow recipe listed; only the Aether mod version.

### Screenshots and Videos

Recipe not in JEI:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/141687438/ffed1fda-7940-4400-88d4-1c392954c0d2)

Recipe not working in crafting table:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/141687438/e44aba45-cad0-4c44-bb99-f07cbe48a158)

### Operating System

Windows 10 Pro; Version 22H2; OS build 19045.3448

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V13

### Optifine

No

**Comment by chorbintime** [comment]
Will be fixed in the next update via aether mod config

**Comment by Gallichron** [comment]
@chorbintime I'm using V16 now and I'm still seeing this issue, despite it being closed. Any updates on this?
