### ISSUE TITLE
Some objects rendered in 3d when placed in Create filters and Sophisticated Storage barrels

### ISSUE THREAD

**Issue by Darxeagle** [LunaPixelStudios/SteamPunk#280]
### Describe the Bug

When some objects are placed in Create filters and Sophisticated Storage barrels, they appear as a 3d objects instead of as icons. This hides the quantity text and looks ugly. I think this is because of some interaction with a object-as-a-3d-model mod for frames.

### Reproduction Steps

1. Place object like block or armor to a Sophisticated Storage's barrel or Create's funnel as a filter

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/28861877/f4de2195-e82b-4221-8949-ea89f6228d28)

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v23.5

**Comment by SHXRKIEgg** [comment]
This is due to to the faithless resourcepack. We will see if we can fix this in next update.
