### ISSUE TITLE
recommendation

### ISSUE THREAD

**Issue by Gost-GitL** [LunaPixelStudios/SteamPunk#282]
### Describe the Bug

In my opinion, Iter RPG mod just makes the experience worse.
1. scallops constantly spawn in beach biome, and my base is enclosed and bright which still dose nothing with it
2. goblins have no audio effect which render the experience odd
3. loot chests in Iter RPG's nether structure are empty which make me depelet resourses but gain nothing
4. modded gears requiring rare materials aren't worth effort to obtian because there are better alternatives from other mods.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

None

**Comment by SHXRKIEgg** [comment]
Removing this mod will cause a lot of issues for users as its relatively a big mod, in our 1.20.1 update it wont be included.
