### ISSUE TITLE
error code 1

### ISSUE THREAD

**Issue by Natorange35** [LunaPixelStudios/SteamPunk#283]
### Describe the Bug

when i tried to lunch the modpack i cant the game crash i update my driver but Nothing seem to change

### Reproduction Steps

1.star the mod pack
2.crash
3.
...

### Crash Report or Log

https://paste.atlauncher.com/view/44650efe-6c8b-4822-b8cc-5b4e9212deb6

### Operating System

Windows 10

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v23.5

**Comment by chorbintime** [comment]
Update your GPU drivers directly through the vendor's website - dont use the app. The only reason this issue would ever happern is due to outdated drivers, so make sure you update both of your GPUs if you have more than one
