### ISSUE TITLE
Duplication bug - works on any item

### ISSUE THREAD

**Issue by K-Fitzpatrick** [LunaPixelStudios/SteamPunk#284]
### Describe the Bug

Using Sophisticated Storage's Stack Upgrade and Supplementaries' Sack, you can duplicate any item you have more than a stack of (including unstackables).

### Reproduction Steps

1. Put more than 1 full stack in a Sophisticated Backpack with a Stack Upgrade
2. Left click a Sack (to hold it)
3. Right click the overfull stack
4. **The Sack will contain the full amount of the Backpack stack, but the Backpack will have only lost 1 stack**

### Screenshots and Videos

Duplicating buckets of snow:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/1942774/d6c17b73-984e-4b1f-a9b4-0d274e58f4e5)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/1942774/f6421bfd-718f-4e2d-bfaf-b0f2e92ae6ec)

Duplicating emeralds:
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/1942774/74846b2b-28b0-4150-aaf8-40b67f5015e6)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/1942774/9ff09e7b-35dc-40fa-825c-1bfd78107f8d)

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

23.5

### Other Mods

- Vampirism
- Vampires Need Umbrellas
- Werewolves

**Comment by chorbintime** [comment]
report it to the Supplementaries developers please

**Comment by K-Fitzpatrick** [comment]
They say it shouldn't be an issue in later versions, does SteamPunk need to update the one it uses?

**Comment by chorbintime** [comment]
yes, it'll be updated in the next modpack update
