### ISSUE TITLE
Obsidian Armor is not craftable for quest

### ISSUE THREAD

**Issue by mycroftjr** [LunaPixelStudios/SteamPunk#286]
### Describe the Bug

JEI clearly shows (and is correct) that Obsidian Armor is not craftable in the current version of the Aether. The "recipe" with Phoenix Armor and "Icestone" is a future drop from "Icestone Ore", which is not in the public version yet. Please remove this quest or add an actual way to get Obsidian Armor.

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

24

**Comment by SHXRKIEgg** [comment]
Thank you will do.
