### ISSUE TITLE
Moving object = Can't use items/inventory

### ISSUE THREAD

**Issue by FlowerVirtual** [LunaPixelStudios/SteamPunk#287]
### Describe the Bug

I was on a server with my boyfriend. I went to shift click a painting to move it over a block and it disappears and my arms are stuck in the grab pose. I can move and jump, but I can not access my inventory, destroy blocks, open chests and doors, or use my scroll wheel to access different hot bar box. 

I killed my character 3 times, restarted the launcher, deleted and reloaded the server, and even uninstalled and deleted the mod pack then reinstalled. I joined again each time and was still stuck in that position unable to do anything but move around. Now I can't play on my boyfriends server he's paying for us to play on.

### Reproduction Steps

1. place painting on wall (mine was on oak planks and it was a1x2 or 2x1 painting)
2. hold shift and right click painting
3. 
...

### Screenshots and Videos

![InventoryScreenshot](https://github.com/LunaPixelStudios/SteamPunk/assets/174765595/ed3c192b-7363-4ba7-93ea-79180be86dd1)
![F5Screenshot](https://github.com/LunaPixelStudios/SteamPunk/assets/174765595/bde752a1-9d75-4b10-a825-bc426e206d11)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v24

### Other Mods

None

**Comment by SHXRKIEgg** [comment]
You need to break the painting to replace it not shift right click. We blacklist paintings from he carryon mod in the next update. /kill you reset your character or have someone do it.
