### ISSUE TITLE
Game crashes while looking up JEI

### ISSUE THREAD

**Issue by TDY2012** [LunaPixelStudios/SteamPunk#289]
### Describe the Bug

I looked up on certain items in JEI and the game just crashed. The error message mentioned about the Cold Sweat mod. I think this issue might relate to [this](https://github.com/Momo-Softworks/Cold-Sweat/issues/303#issuecomment-2138601624).

### Reproduction Steps

1. Open up JEI.
2. Look for items from Enigmatic Legacy mod.
3. Hover your mouse around and expect a crash.

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by muluxu** [comment]
I kinda found a solution, just copy the 'saves' and 'XaeroWaypoints' files (if you want all the waypoints) to your desktop, then reinstall the modpack, then put the 'saves' and 'XaeroWaypoints' file in the correct folder.

**Comment by muluxu** [comment]
Try disabling advanced tooltips

**Comment by SHXRKIEgg** [comment]
Need a crash report please
