### ISSUE TITLE
Scorched Guns and Scorched Bronze Guns have some incompatibilities

### ISSUE THREAD

**Issue by lynnpye** [LunaPixelStudios/SteamPunk#29]
### Describe the Bug

"Scorched Guns" (scorchedguns-1.12-1.19.2.jar) (https://www.curseforge.com/minecraft/mc-mods/scorched-guns) and "Haywire Robots, Bandits and Guns- A Scorched Bronze Addon" (scguns-1.10-1.19.2.jar) (https://www.curseforge.com/minecraft/mc-mods/haywire-robots-bandits-and-guns-a-scorched-bronze) both define the same set of guns, but with different recipes. Unfortunately they also define the same bullets but the bullets are not cross compatible. Additionally, some bullets have bulk recipes for one and not the other.

Since the Scorched Bronze Guns mod includes the mobs and other miscellaneity, I suspect that would be the version to keep. Alternatively, if there is a way to alter the gun definitions to be able to make use of the other mods bullet version, along with recipes to make the bulk bullets craftable for all ammo types, that would work too.

### Reproduction Steps

For example, the Gauss Rifle has two versions, one from Scorched Guns and one from Scorched Bronze Guns. Each takes EC Rounds from their respective mod and are not usable with the EC Rounds from the other mod, i.e. you cannot reload a Scorched Guns Gauss Rifle using Scorched Bronze Guns EC Rounds. However, there is only a EC Round Box defined for Scorched Bronze Guns.

The SC Lawbringer also has two versions, one from each mod. The Scorched Guns version, however, uses Scorched Shells, whereas the Scorched Bronze Guns version uses regular Shells. Both do the same damage.

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

13

### Optifine

No

**Comment by lynnpye** [comment]
I have attached a datapack that:
- uses the scguns_recipe_pack.zip datapack as a base, providing the recipes, including all of the ammo box/pouch items
- and also includes the rebalance specs from the ScorchedRebalanced.zip datapacck, under the assumption that you wanted to use those updated values (i.e. changes to component positioning, damage values, etc.)

To test, I did the following and got the results I was hoping for:

- Duplicated my curseforge instance
- In the duplicated instance, I removed the following files:
--- mods\scorchedguns-1.12-1.19.2.jar
--- config\paxi\datapacks\scguns_recipe_pack.zip
--- config\paxi\datapacks\ScorchedRebalanced.zip
- I then added the file I have attached:
--- config\paxi\datapacks\scguns_recipes_and_balance.zip

Upon starting the instance, I observed the following:
- expected entities added by scguns (woolmen and such) were still present
- the list of guns, ammo, and addons was no longer duplicated (i.e. there was only one Gauss Rifle, added by scguns)
- all ammo had bulk versions available


[scguns_recipes_and_balance.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12804394/scguns_recipes_and_balance.zip)

**Comment by SHXRKIIE** [comment]
Appreciate it thanks, haven't had proper time to balance the guns myself

**Comment by lynnpye** [comment]
Btw, I see in v14 the datapack was added. Thanks for the attribution, btw, though I wasn't expecting that. 🙂

Any plans to remove the "~SCORCHED GUNS~" mod now that there are recipes and balancing adjustments applied to the duplicate guns added in "Haywire Robots, Bandits and Guns - A Scorched Bronze Addon" mod?

I suppose that could potentially break worlds, so I understand if that's not something you'd want to do. Maybe just removing the recipes first to avoid confusion? It just clunks up the already annoying to navigate UI of the gun Workbench to have all the guns, ammo, and modifications duplicated between the two mods.

**Comment by lynnpye** [comment]
I've attached a data pack I'm using that removes the "SCORCHED GUNS" mod recipes. Along with the other datapack, it will remove the duplicate guns, ammo, and modifications from the Workbench, although the items will remain visible in JEI. This at least prevents you from having to remove the mod while still decluttering the Workbench UI.

[remove_scorched_guns_recipes.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12846961/remove_scorched_guns_recipes.zip)

**Comment by lynnpye** [comment]
I'm attaching one more file, a blacklist.cfg for JEI. It's located at '/config/jei/blacklist.cfg' and is currently empty. Placing the attached version will hide all of the "SCORCHED GUNS" mod recipes from JEI. The objects still exist as the mod isn't removed, so you can still /give them, but it should remove them from general consideration without having to break worlds by removing them outright. The worst case scenario is if someone has already built a gun from that mod and can no longer create ammo for it. In that case they would need to create a copy of the gun from "Haywire Robots..." and then carry on creating ammo for that.

Thankfully, you referenced the "Haywire Robots..." guns when you created your quests and such, so if folks were targeting those quests they should have been creating the correct items already.

I can't directly attach a '.cfg' file (thanks github!) so I'm going to just add the contents here in a code block. Copy the contents into the jei blacklist.cfg mentioned above to hide the recipes.

`
scorchedguns:advanced_silencer
scorchedguns:alfonz_repeating_punter
scorchedguns:alfonz_turnpike
scorchedguns:astella
scorchedguns:auto_crossbow
scorchedguns:basic_sight
scorchedguns:bastard_gun
scorchedguns:blasphemy
scorchedguns:blunderbuss
scorchedguns:carabine_44
scorchedguns:cogloader
scorchedguns:cosmic_blitzer
scorchedguns:cyclone
scorchedguns:diamond_steel
scorchedguns:diamond_steel_from_nugget
scorchedguns:diamond_steel_nugget
scorchedguns:earths_corpse
scorchedguns:ec_round
scorchedguns:encased_fire
scorchedguns:eoka_pistol
scorchedguns:ethereal_bullet
scorchedguns:ethereal_ec_round
scorchedguns:ethereal_heavy_bullet
scorchedguns:ethereal_shell
scorchedguns:experimental_round
scorchedguns:flechette
scorchedguns:flechette_jet
scorchedguns:flechette_round
scorchedguns:frontier_sidearm
scorchedguns:g19_director
scorchedguns:gauss_rifle
scorchedguns:gowza_32l
scorchedguns:hand_crossbow
scorchedguns:heavy_bullet
scorchedguns:heavy_crossbow
scorchedguns:heavy_pig_round
scorchedguns:hell_gunpowder
scorchedguns:huot_auto
scorchedguns:invis_nvr_63
scorchedguns:jackhammer
scorchedguns:jury_rigged_wrist_breaker
scorchedguns:kiln_gun
scorchedguns:krauser_conversion
scorchedguns:lg8_grenade_launcher
scorchedguns:lm_scoont
scorchedguns:lm_sekora
scorchedguns:lm_spear_ironport
scorchedguns:lm_spear_trough
scorchedguns:m12_waltz
scorchedguns:m19_waltz_dehann
scorchedguns:m99_krauser
scorchedguns:muzzle_brake
scorchedguns:nitro_dust
scorchedguns:noqq_gun
scorchedguns:officers_special
scorchedguns:ooz_96
scorchedguns:osborne_slug
scorchedguns:osgood_50
scorchedguns:pig_round
scorchedguns:pipe_musket
scorchedguns:powder_and_ball
scorchedguns:punt_gun
scorchedguns:pure_gunpowder
scorchedguns:quartz_shell
scorchedguns:r498_gauss_cannon
scorchedguns:railworker
scorchedguns:rivet
scorchedguns:riveter
scorchedguns:rustic_scope
scorchedguns:scattergun
scorchedguns:scatterstaff
scorchedguns:scorched_big_bullet
scorchedguns:scorched_bronze
scorchedguns:scorched_bronze_from_nugget
scorchedguns:scorched_bronze_nugget
scorchedguns:scorched_bullet
scorchedguns:scorched_obrez
scorchedguns:scorched_obrez_staff
scorchedguns:scorched_shell
scorchedguns:scorched_scatter_staff
scorchedguns:scorched_staff
scorchedguns:scorched_wand
scorchedguns:scrap_cannon
scorchedguns:scrap_pistol
scorchedguns:sc_dahka
scorchedguns:sc_deputy
scorchedguns:sc_fusilage
scorchedguns:sc_gowza
scorchedguns:sc_lawbringer
scorchedguns:shotbolt
scorchedguns:simple_bullet
scorchedguns:skellik_65
scorchedguns:soul_drummer
scorchedguns:spitfire
scorchedguns:steyr_smg
scorchedguns:sturdy_grip
scorchedguns:tactical_grip
scorchedguns:thumper
scorchedguns:thunderhead
scorchedguns:tin_bronze_ingot
scorchedguns:tt_jorm_keg
scorchedguns:tunck_37
scorchedguns:vidas_smg
scorchedguns:volatile_scrap
scorchedguns:volley_gun
scorchedguns:waltz_conversion
scorchedguns:wire_stock
scorchedguns:wooden_stock
scorchedguns:scorched_bronze_ingot
`

**Comment by lynnpye** [comment]
And one more datapack that adds recipes allowing you to convert "scorchedguns:" items to "scguns:" items in the crafting table as shapeless 1:1 recipes. It was a simple brute force method I used, scanning the existing scorchedguns recipe json files for their outputs, finding matches in the scguns recipe json, and creating the associated recipe.

I did find a few items added by scorchedguns: that had no analog in scguns:, which includes a few guns and their ammo:
Found scorchedguns:flechette but no corresponding scguns:flechette
Found scorchedguns:heavy_crossbow but no corresponding scguns:heavy_crossbow
Found scorchedguns:heavy_pig_round but no corresponding scguns:heavy_pig_round
Found scorchedguns:hell_gunpowder but no corresponding scguns:hell_gunpowder
Found scorchedguns:invis_nvr_63 but no corresponding scguns:invis_nvr_63
Found scorchedguns:noqq_gun but no corresponding scguns:noqq_gun
Found scorchedguns:pig_round but no corresponding scguns:pig_round
Found scorchedguns:quartz_shell but no corresponding scguns:quartz_shell
Found scorchedguns:rustic_scope but no corresponding scguns:rustic_scope
Found scorchedguns:skellik_65 but no corresponding scguns:skellik_65
Found scorchedguns:tin_bronze_ingot but no corresponding scguns:tin_bronze_ingot
Found scorchedguns:tt_jorm_keg but no corresponding scguns:tt_jorm_keg
Found scorchedguns:tunck_37 but no corresponding scguns:tunck_37
Found scorchedguns:vidas_smg but no corresponding scguns:vidas_smg

I don't think this would be too much of an issue, but wanted to mention it. It could be that my script missed something.

Anyhow, the datapack is attached.

[scguns_conversion_recipes.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12848682/scguns_conversion_recipes.zip)

**Comment by SHXRKIIE** [comment]
Sorry for late reply but I can just remove the mod due to it only adding recipes so it wont cause any sort of corruption or breaking and looking at it now, it should never have been added, I thought it was a addon for Haywire but I was mistaken.

**Comment by lynnpye** [comment]
Removal is the cleanest option. It's possible, even likely, that some folks have worlds with that mod's version of the items if only because they were often easier to craft, with fewer or easier ingredients. But as you can see, the effort to try to hide everything about the mod without actually removing it takes a bit of effort and still leaves open the possibility that something was missed and someone could possibly still end up with the wrong version of an item.
