### ISSUE TITLE
Soul speed page with skill is never dropped

### ISSUE THREAD

**Issue by konradrej** [LunaPixelStudios/SteamPunk#290]
### Describe the Bug

Page with skill
- Soul speed

says 14.29% change of drop when bartering with piglins when you hover over it in JEI menu but when you use hover and press R to get receipt it does not show the bartering as a option. Having bartered thousands of gold ingots I also haven't received it yet.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v23.5

**Comment by mycroftjr** [comment]
The latest modpack version is v24, is this still happening there?

**Comment by konradrej** [comment]
I upgraded server/client to v24 and tried another 3 stacks, still no skill page.

I did find [this](https://github.com/dragon-forge/ImprovableSkills/issues/15) issue for the mod itself however it seems to be 1.20.1 related so might not be useful. I'm not familar with minecraft mod development so not sure how to help more right now.

**Comment by SHXRKIEgg** [comment]
Yeah seems not to drop, will fix it

**Comment by mycroftjr** [comment]
> Yeah seems not to drop, will fix it

Out of curiosity, how are you planning to fix it?
