### ISSUE TITLE
Indexing Error/JEI Issue?

### ISSUE THREAD

**Issue by mspring25** [LunaPixelStudios/SteamPunk#291]
### Describe the Bug

Moving the cursor over certain items in JEI causes game to freeze and then crash. Continues to tell me that it is an indexing error.

### Reproduction Steps

1. Open JEI
2. Move cursor over random items (typically non-vanilla items)
3. Game should freeze and then crash
...

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

23.5

**Comment by SHXRKIEgg** [comment]
Need a crash report
