### ISSUE TITLE
Adding a mod 

### ISSUE THREAD

**Issue by Kasukasa** [LunaPixelStudios/SteamPunk#293]
### Describe the Bug

When i add the mod for the a server eg. TAB  mod the commands wont show 

### Reproduction Steps

1.  Making A server
2. Putting in the command
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

V24

### Other Mods

TAB
STYLIZED TEXT

**Comment by SHXRKIEgg** [comment]
Add mods at your own discretion
