### ISSUE TITLE
Problems with chunks and modification of Cold Sweat

### ISSUE THREAD

**Issue by TTpaTTop** [LunaPixelStudios/SteamPunk#294]
### Describe the Bug

I played quietly in the local world, practically without changing the graphics settings. After the file size reached more than 100 MB, the first performance problems began. Multiple microfreezes and the almost complete impossibility of being in the Hell dimension. Also, once every 3 launches, the loading of the world could be interrupted and Minecraft would crash.

Upon examination, it was discovered that the error was caused by the “Cold Sweat” mod, after removing which the game crash when loading the world completely disappeared. After testing around the world using creative flight, it was discovered how slow chunk loading is around the world. Changing rendering and performance settings did not change the situation. I didn’t find any problem with RAM, Video card or CPU.

Also in some regions, multiple spam messages with similar messages to the console were noticed, which presumably refers to “Entity Model Features”:

_[12/07/2024 23:37:53 PM] > EMF print: [1] = -55.09441
[12/07/2024 23:37:53 PM] > EMF print: [1] = 0.0015830994
[12/07/2024 23:37:54 PM] > EMF print: [1] = 0.009887695
[12/07/2024 23:37:54 PM] > EMF print: [1] = 0.006893158
[12/07/2024 23:37:54 PM] > EMF print: [1] = 0.02186203
[12/07/2024 23:37:54 PM] > EMF print: [1] = 0.008937836_

The build is certainly interesting and exciting, but such problems, to be honest, are off-putting...

### **PC components:**
AMD Ryzen 5 2600
GIGABYTE GeForce GTX 1660 Ti
16 GB RAM (2888 Hz)
Windows (11 build 26100)

### **Launch parameters:**
ATlauncher v.3.4.36.9
Java Version: Java 17 (17.0.3)
Java Parameters: _-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M_
Dedicated memory for work: 8192M

Spark profiler: https://spark.lucko.me/Dkw6Y3vMTW

_Translated using Google Translator_

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/a5a77a5a-0d35-4d38-9af5-28733c595f83)
![image](https://github.com/user-attachments/assets/162a9cd7-c425-4803-b53b-d6c9dcfdc527)
![image](https://github.com/user-attachments/assets/d5680493-8271-4e0e-a624-592c92d826f4)

### Crash Report or Log

https://gist.github.com/TTpaTTop/f75bd62a905dc54d41d44d71594b4994

### Operating System

Windows (11 build 26100)

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

Spark

**Comment by SHXRKIEgg** [comment]
Im my testing, the modpack chunk gen is super fast and your spark profiler tells me there isnt much lag, this is more that your pc is limiting its performance, check this guide if you need help with performance. https://rpg.prominence.wiki/performance-guide
