### ISSUE TITLE
Various Quest Issues

### ISSUE THREAD

**Issue by mycroftjr** [LunaPixelStudios/SteamPunk#296]
### Describe the Bug

1. In the Ulterlands chapter:
  a. Weather Tooths cannot be obtained in survival currently, as atm Aeglin do not drop anything
  b. A typo in at least one quest: It's Gyroc, not Kyroc
  c. It would be nice if you added a disclaimer that atm, most Tetra tools (most tools, actually, apart from the Infernal Forge - the drop from Cataclysm's Netherite Monstrosity boss) will not yield any drops from Ulterlands "tool-required-to-harvest" blocks
  d. Optimally you could make them actually spawn, but if not: For the "Kill a Fortross" and "Make an Oxy-Capsule" quests, please add a note that Fortross only appear when their Edge Wasteland islands **first generate** (since they are created as part of the structures), so hunting them should be first priority when finding an Edge Wastelands biome before they're replaced by other hostile mobs in the hostile mob cap (or better yet, abducting them via Quantum Catchers for the sake of speed, then killing them off-site later with a Soul Crystal and the Soul Reaper enchantment - Ulterlands mobs don't work in the Soul Revitalizer, but they should in the Soul Cage).
  e. "Make a Oxy-Capsule" should be "Make a**_n_** Oxy-Capsule"
2. Ad Astra:
  a. For the "Collect the Earth Globe" quest, only the Moon Globe is currently obtainable in survival (in-world at the end of the moon dungeon) (I painstakingly confirmed this via the mod files)
  b. In the Venus chapter, the questbook asks you to go to the Venus Bullet structure, even though nothing is there atm
3. For the "Find the Burning Arena" Nether quest, it would be useful to mention that the Eye of Flame item points the way there
4. For the root "Aether" quest, info on whether or not the same "outside tools/armors are less effective in this dimension" applies as on Blue Skies would be useful. Outside tools do indeed seem to harvest much slower than native ones, but I can't say for sure on the armor.
  b. The Golden dungeon boss takes way too long to beat for all those loot quests to be reasonable

Additional good pack feedback (mostly about quests) from another user on discord: https://discord.com/channels/790272037578473512/996250521465790514/1245658000232939590 - I'll let their post talk for itself

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

24

**Comment by SHXRKIEgg** [comment]
Will fix in next update thanks
