### ISSUE TITLE
I run "start.ps1" and it saying press any key to exit without running my server

### ISSUE THREAD

**Issue by Nm10011076166** [LunaPixelStudios/SteamPunk#297]
### Describe the Bug

I run "start.ps1" after I installed forge server and it's saying press any key to exit without running my server
[debug.log](https://github.com/user-attachments/files/16317338/debug.log)
[debug-1.log.gz](https://github.com/user-attachments/files/16317340/debug-1.log.gz)
[latest.log](https://github.com/user-attachments/files/16317341/latest.log)
[2024-07-20-1.log.gz](https://github.com/user-attachments/files/16317342/2024-07-20-1.log.gz)

### Reproduction Steps

1.install forge server
2.extract servermod
3.run start.ps1
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/18b434e7-1090-4d4b-9e75-33e40561bdaa)

### Operating System

Windows11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

1.19.2

**Comment by SHXRKIEgg** [comment]
Redownload the serverpack
