### ISSUE TITLE
Inconsistent storage capacity upgrades in the Sophisticated Storage mod

### ISSUE THREAD

**Issue by N30A** [LunaPixelStudios/SteamPunk#298]
### Describe the Bug

In the Sophisticated Storage mod, the storage capacities of chests and barrels are supposed to increase as you upgrade to higher tiers. However, the actual storage capacities seem to be inconsistent or not increasing as expected. Here's a breakdown of the observed storage capacities:

- Regular Chest & Barrel: 3x9 slots
- Copper Chest & Barrel: 5x9 slots
- Iron Chest & Barrel: 5x9 slots
- Gold Chest: 5x9 slots
- Gold Barrel: 6x9 slots
- Diamond Chest: 6x9 slots
- Diamond Barrel: 9x12 slots
- Netherite Chest: 6x9 slots
- Netherite Barrel: 9x12 slots

**Issues Noted:**

**1. Copper, Iron, and Gold Chest:** These all have the same capacity (5x9 slots), which is unexpected since each upgrade should ideally provide more storage.

**2. Gold Barrel vs. Diamond Chest:** The Gold Barrel has more slots (6x9) compared to the Diamond Chest (6x9). This is inconsistent because the Diamond tier is generally higher than the Gold tier.

**3. Diamond Chest vs. Netherite Chest:** Both have the same storage capacity (6x9), which is unexpected since Netherite is a higher tier than Diamond.

**4. Diamond and Netherite Barrels:** These both have significantly higher capacity (9x12 slots) compared to their chest counterparts, which is unexpected and seems disproportionate.

**Summary of the Problem:**

The maximum storage capacities of chests and barrels do not increase consistently or logically when upgrading to higher tiers. Some higher-tier chests have the same capacity as lower-tier ones, and in some cases, barrels offer more storage than their chest counterparts of the same tier. This inconsistency in storage capacity upgrades needs to be addressed to ensure a logical progression as players upgrade their storage solutions.

### Reproduction Steps

**1. Check Storage Capacities**

Place each chest and barrel in the game world. Open each chest and barrel and count the number of storage slots available.

**2. Compare Storage Capacities**

Note the storage capacity of each item and compare them across different tiers.

**3. Identify Inconsistencies**

Observe that some higher-tier chests have the same capacity as lower-tier ones. Notice that barrels often have more storage capacity than their chest counterparts at the same tier.

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
The capacity has been nerfed

**Comment by N30A** [comment]
Sure thing, but it still doesn’t make sense why a gold, diamond, and netherite barrel have more capacity than a chest made from the same materials, especially since two single chests cannot be combined. #299
