### ISSUE TITLE
Unable to combine two single chests in the Sophisticated Storage mod

### ISSUE THREAD

**Issue by N30A** [LunaPixelStudios/SteamPunk#299]
### Describe the Bug

In the Sophisticated Storage mod, players should be able to place two single chests adjacent to each other to form a double chest, similar to the vanilla Minecraft behavior. However, when attempting to do this with any tier of chests (e.g., Regular, Copper, Iron, etc.), the two single chests do not combine to form a double chest. This bug prevents players from expanding their storage space using double chests.

### Reproduction Steps

**1. Place the first chest**

Place the first single chest on the ground in your desired location.

**2. Attempt to combine with a second chest**

Place the second single chest adjacent to the first chest in an attempt to create a double chest.

**3. Observe behavior**

Notice that the two single chests do not combine to form a double chest as expected.

### Screenshots and Videos

![bild](https://github.com/user-attachments/assets/525c3611-d383-4da1-8621-5e17589652e5)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
Not sure why its not connecting, will have a look at this for next update

**Comment by qwek1** [comment]
This is intended behaviour, happens with a fresh installation of Sophisticated Storage as well.
