### ISSUE TITLE
JER and JER Integrations doesnt work on server or singleplayer

### ISSUE THREAD

**Issue by Inteprise** [LunaPixelStudios/SteamPunk#3]
### Describe the Bug

i dunno what to say it just doesnt work, Just Enough Immersive Multiblocks on the otherhand does work so theres that at least

it seems to be a known issue so i dunno if it can be fixed

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V4.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Could you elaborate more on what resources you are trying to look for as it works for me, If you are talking about some modded resources don't work then they just aren't integrated yet.
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/572363e1-c2ac-40d6-bd79-93827c9d2fc0)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/d85d23da-465c-4c4a-a718-7ef434de9213)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/2fab3131-dc7f-4575-90dc-9d6acc1fb568)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/06c07b0c-2f7c-47d5-bee4-33f43598e96d)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/65de2ab1-87c6-475d-922d-e3bdf28d1537)

**Comment by Inteprise** [comment]
I have tried to say look at gunpowder and it should show the mob drop page with creeper ghast etc but there is nothing when i join multiplayer server (seem to be known issue as i said) https://github.com/way2muchnoise/JustEnoughResources/issues/362

I looked at ores like diamond or coal and it works in singleplayer but not servers

Same for : Plant drop, dungeon chest, ore distribution/world gen. works on singleplayer but not servers

professions do work in singleplayer and multiplayer

JER integration V4.4.0
JER 1.2.2.2.00 (alpha)

**Comment by SHXRKIIE** [comment]
Oh wait i mustve misread, it works singleplayer but MP doesnt as the devs need to fix that on their end for JER.
