### ISSUE TITLE
Crash in End City

### ISSUE THREAD

**Issue by Trappeasouris** [LunaPixelStudios/SteamPunk#30]
### Describe the Bug

The game crashed whilst generating pf sounds for entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.sounds.SoundEvent.m_11660_()" because the return value of "net.minecraft.world.level.block.SoundType.m_56776_()" is null

### Reproduction Steps

1.Enter the End City
2.Explore the End City
3.???
4.Crash

Everytime and for everyone on server, that same crash and error we got.

We can't play anymore.

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V13

### Optifine

No

### Other Mods

No mods add

**Comment by SHXRKIIE** [comment]
Need crash report

**Comment by Trappeasouris** [comment]
[crash-2023-10-04_20.17.53-client.txt](https://github.com/LunaPixelStudios/SteamPunk/files/12813578/crash-2023-10-04_20.17.53-client.txt)

**Comment by SHXRKIIE** [comment]
Remove presencefootsteps mod

**Comment by mulhollandaf** [comment]
I saw this tonight with v21.5. It kept crashing until I disabled the presencefootsteps mod.
