### ISSUE TITLE
Inconsistent capacity when upgrading backpacks in Sophisticated Backpacks mod

### ISSUE THREAD

**Issue by N30A** [LunaPixelStudios/SteamPunk#300]
### Describe the Bug

In the Sophisticated Backpacks mod, the storage capacities of backpacks are supposed to increase as you upgrade to higher tiers. However, the actual storage capacities seem to be inconsistent or not increasing as expected.

- **Backpack:** 3x9 slots
- **Copper Backpack:** 5x9 slots
- **Iron Backpack:** 5x9 slots
- **Gold Backpack:** 5x9 slots
- **Diamond Backpack:** 6x9 slots
- **Netherite Backpack:** 6x9 slots

### Reproduction Steps

**1. Check Storage Capacities**

Open each backpack and count the number of storage slots available.

**2. Compare Storage Capacities**

Note the storage capacity of each item and compare them across different tiers.

**3. Identify Inconsistencies**

Observe that some higher-tier backpacks have the same capacity as lower-tier ones, which is unexpected.

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
The capacity has been nerfed. Each upgrade either gives extra space or extra upgrade slot.

**Comment by N30A** [comment]
Sure thing, but it still doesn’t make sense why a gold, diamond, and netherite barrel have more capacity than a chest made from the same materials, especially since two single chests cannot be combined. #299
