### ISSUE TITLE
Enigmatic Legacy crash

### ISSUE THREAD

**Issue by Bazinga944** [LunaPixelStudios/SteamPunk#302]
### Describe the Bug

When i try to review an item from enigmatic legacy on the JEI inetrface, my game instantly crash. This issue is only applies to those items that are only available in hardcore mode (I'm in easy mode)

### Reproduction Steps

1. Open inventory 
2. Slide your cursor onto an item that are only available in hardcore mode
3.
...

### Screenshots and Videos

https://github.com/user-attachments/assets/ad3de020-7e07-43fb-877e-6971080a41d7

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Fabric

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
No Crash for me, you also didnt provide a crash report so I need one to check whats going on,

**Comment by Bazinga944** [comment]
[crash-2024-07-24_20.55.28-client.txt](https://github.com/user-attachments/files/16399126/crash-2024-07-24_20.55.28-client.txt)

This is the crash report.

**Comment by SHXRKIEgg** [comment]
Crash looks fine, still cant recreate it, does it happen still after a restart?

**Comment by MasterofOak** [comment]
Turn off advanced tooltips by pressing "F3 + H", it should fix the issue. Had same problem not so long ago

**Comment by SHXRKIEgg** [comment]
i had advanced tooltips enabled and no crash

**Comment by Bazinga944** [comment]
> Turn off advanced tooltips by pressing "F3 + H", it should fix the issue. Had same problem not so long ago
Thank you, that solved it!

**Comment by mycroftjr** [comment]
this should also be fixable by updating Cold Sweat to at least ColdSweat-2.3-b03e (b03f should be safe as well)
