### ISSUE TITLE
Server Lag when crafting multiple stuff

### ISSUE THREAD

**Issue by Gaxmaster2K** [LunaPixelStudios/SteamPunk#305]
### Describe the Bug

Every time someone crafts multiple stacks of something at once, the server istantly drops in tps, and everyone in the server get stuck. 

Looks like it only happens on crafting table. in crafting terminal this problem doesn't happen.

### Reproduction Steps

1. go to crafting table
2. try to craft things (example, slabs from wood planks)
3. shiftclick to get multiple stacks 
4. lag (tps drop, server freeze)

### Screenshots and Videos

none

### Crash Report or Log

https://spark.lucko.me/a5IazX0Xvf   [spark profiler]

### Operating System

Ubuntu [Exaroton Server]

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

trashslot (added  after the problem occurred)
FTB Ultimine
Waystone

**Comment by chorbintime** [comment]
Make a backup of your world, and try without the Quark mod. If it persists, try without Polymorph. Let me know the results.

**Comment by batteryhun78** [comment]
Anyone using on your server a setup like this? I thought "this" was a feature, but realized it **lags a lot**, mainly when someone is crafting like a stack of sticks, etc, even the avaliable slot showed is probably a bug (or showing item count as slots?)

Basically, don't connect with the inventory connector like on these pictures, only with Inventory Cable Connector.

![kép](https://github.com/user-attachments/assets/e8a75bfc-e370-499d-9048-7158e2df7ad3)

![kép](https://github.com/user-attachments/assets/d03a7a7d-45e6-4662-b21b-b3bc11bfc983)

**Comment by SHXRKIEgg** [comment]
update to v25

**Comment by batatero4** [comment]
Hi!, actually im in the v25 (i guess, i download it from curseforge on mid october) and still with this lag issue while crafting, first i guess was the crafting table, but in my inventory have the same issue, and im playing alone so its weird to have "lag" haha

**Comment by batatero4** [comment]
> Please follow [the performance guide](https://rpg.prominence.wiki/performance-guide)

I already did it, I have v6 of the modpack, I use the recommended version of java on my launcher and I have more ram, but nevertheless, even though the game runs fine 99% of the time, when I craft a stack of things for example, the entire game freezes for a few seconds, either on the crafting table or in the inventory.

**Comment by chorbintime** [comment]
Send a screenshot with f3 open ingame please

**Comment by batatero4** [comment]
> Send a screenshot with f3 open ingame please

![SS01](https://github.com/user-attachments/assets/1e47d235-fc84-496f-8e2d-fa1ea67d860f)
![SS02](https://github.com/user-attachments/assets/2099ac0e-7988-469f-8b47-271fec5bf066)
![SS03](https://github.com/user-attachments/assets/ec4dd32d-297d-43d9-b309-81a1515efadf)
![SS04](https://github.com/user-attachments/assets/5a4e4e74-63a7-409d-9546-d17b3c0d74b7)
![SS05](https://github.com/user-attachments/assets/41e3507e-e3df-43fe-9c16-88ef4b1eac3b)
![SS06](https://github.com/user-attachments/assets/0bc43af3-42e4-48ca-9b94-82bcbbedb002)
![SS07](https://github.com/user-attachments/assets/5182b8d3-b113-412c-b60e-f42352fef09d)

1 - Start 40-50 fps (nice for me)
2 - I craft a half stack of logs to wood (down to 13 fps)
3 - I craft sticks on a crafting table AND SHIFT CLICK to craft all of them, but only give me like i craft "only one"
4 - I got 4 stick on my hand and the wood ""still"" in the crafting table
5 - The wood disappears, I still have "only 4 sticks"
6 - 4 sticks on my inventory
7 - I shift click the stick to move them and OH there they are! magically a stack of sticks! xD

**Comment by chorbintime** [comment]
Try disabling the recipe book via the recipeessentials mod config in the config folder

**Comment by batatero4** [comment]
![image](https://github.com/user-attachments/assets/c3571602-2b7b-426e-a6a6-f07c2ca0c79c)
Actually I tried this but the whole game keeps freezing when I craft

**Comment by chorbintime** [comment]
Keep disablerecipebook on false.

Please follow the guide [here](<https://github.com/chorbintime/LPS-readme/wiki/1.21#java-installation>) for changing the Java version your server uses. This will improve performance dramatically. If you are on a third party server host, you likely can not change the Java version your server uses. Bisect Hosting and a few VPS providers do allow changing Java version, though, which can usually be done through your server dashboard.

The method on Bisect is to simply go to the main dashboard page, and select "GraalVM 22" as the Java distribution. If it crashes, use 21 instead.

For further performance improvements, you can also follow [this](<https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks>) guide.

If lag persists, run the following command ingame:
/spark profiler start --only-ticks-over 50

**Comment by batatero4** [comment]
As I mentioned before, yes, leave the option at false.

Yes, I have had that version of Java for a long time now. 

And NO, I am not playing on a server, im playing aloooone, singleplaaaayer.

And YES, even with all this, I cannot manually convert a stack of iron ingots using nuggets on a crafting table because it slows down everything (sometimes it even feels like it's going to crash for a second) . But if for example I use a chest with the "auto compress" upgrade it does NOT slow down, it is only when crafting

**Comment by chorbintime** [comment]
You need to run the profiler and send the resulting link here.
