### ISSUE TITLE
Quest Issues

### ISSUE THREAD

**Issue by mycroftjr** [LunaPixelStudios/SteamPunk#306]
### Describe the Bug

1. Many of the Ad Astra quests give choice rewards between various amounts of XP, which I'm pretty sure are meant to be random
2. For Improvable Skills, the Sharp Arrow skill page still can't be obtained atm due to Undead Unleashed replacing the vanilla skeleton drop table just to add Grave Metal Scrap at data/minecraft/loot_tables/entities/skeleton.json inside the Undead Unleashed jar file. I've gotten it to drop twice after deleting said json, but obviously the pack might not be able to do that and it would prevent skeletons from dropping Grave Metal Scrap.
    1. The "Extra Health" skill is likely also not obtainable, as unlike all of the other loot-chest-only skill pages, it does not show a loot chest in JEI.
3. For the Enigmatic Legacy chapter, the Blazing Core quest should probably mention that it can also be found in Bastion and Ruined Portal chests.
4. For the Tetra chapter, the Cthonic Automation advancement and thus the "Automate a Cthonic Extractor" quest don't seem to be obtainable. See https://github.com/mickelus/tetra/issues/836.
4. Near the top of the Iron's Spells chapter, among the "Craft the [X Spell Book]" quests, 4 of them should say "Obtain" instead of "Craft", and list the method of acquisition:
    1. Blaze Instruction Manual (drops from Blazes)
    2. Villager Bible (???)
    4. Grimoire of Evokation (drops from Archevoker, an Iron's Spells mob found where???)
    5. Rotten Spell Book (???)

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
Will see what we can fix in new update
