### ISSUE TITLE
Blank Banners

### ISSUE THREAD

**Issue by Zukovsky911** [LunaPixelStudios/SteamPunk#307]
### Describe the Bug

Any banner not generated by the world is blank/invisible

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

**Comment by SHXRKIEgg** [comment]
Any screenshots?

**Comment by Zukovsky911** [comment]
I dont have any, but they are just straight up invisible, both when placed and in inventories.

**Comment by qwek1** [comment]
On a fresh installation of the modpack, it does not happen.

![image](https://github.com/user-attachments/assets/9b700aa2-45f3-40b6-a48c-f51dcee8c5d8)

**Comment by Nich-K** [comment]
![2024-08-18_13 28 02](https://github.com/user-attachments/assets/a4638d63-bf07-4f40-8ab4-5e782391e344)
![2024-08-18_23 15 20](https://github.com/user-attachments/assets/a843b0fd-572f-4b8d-ab89-e737c974d86a)

Very straightforward. Sometimes banners are invisible
