### ISSUE TITLE
Exploration Lag

### ISSUE THREAD

**Issue by ToLegitNames2023** [LunaPixelStudios/SteamPunk#308]
### Describe the Bug

Only tested on 2 Servers, but im sure its a modpack issue
When loading new chunks error messages appear in console that structures have old files
Chunks sometimes take minutes to load

### Reproduction Steps

1.Generate Chunks
2.Lag
3.Chunks dont load
...

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

None

**Comment by SHXRKIEgg** [comment]
Can you provide a spark profiler?

**Comment by ToLegitNames2023** [comment]
https://spark.lucko.me/jjRoCNHgE4
here i was flying a bit and it happened again
![Bild_2024-08-13_153639173](https://github.com/user-attachments/assets/5355deb1-c7a5-424a-8877-0a5fe019697d)

**Comment by batteryhun78** [comment]
Yes, I experienced this too, the only time the map would load the best and fast, when I was Pre-Gening the world with chunky, before our server started.

Now, If i want to expand the generated chunk area/border, even the pre-gen lags, most of the time only doing 1-4 chunks a second, and sometimes shows the outdated structure files error.

**Comment by SHXRKIEgg** [comment]
update to v25
