### ISSUE TITLE
Essentials Mod UI Trouble

### ISSUE THREAD

**Issue by Silentninja914** [LunaPixelStudios/SteamPunk#31]
### Describe the Bug

I just started this modpack for the first time with the Essentials mod that way I may play with others. After launching the game I am met with an error that I cannot read due to the message being hidden behind the logo.

When I removed the Essentials mod this was fixed, but as I stated I would like to play with others. The error message persists even after completely removing the Essentials UI from the title screen. This error removes the Play, Options, and Mods buttons making it impossible to do anything but quit.

### Reproduction Steps

1. Add the 1.19.2 Essentials mod
2. Boot up the pack
3. Observe error

### Screenshots and Videos

![UI off](https://github.com/LunaPixelStudios/SteamPunk/assets/147121280/771541a3-3bd0-4d3b-af2e-2ae984bb241b)
![UI on](https://github.com/LunaPixelStudios/SteamPunk/assets/147121280/d5119115-0cc0-40ee-9bda-4119fa16b133)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Version 13

### Optifine

No

### Other Mods

Just Zoom

**Comment by SHXRKIIE** [comment]
We dont support essentials, we already have a mod that does world hosting

**Comment by Silentninja914** [comment]
What world hosting mod would that be? I'm only familiar with Essentials.

**Comment by CapToad** [comment]
> What world hosting mod would that be? I'm only familiar with Essentials.

remove drippyloadingscreen and fancymenu and it should work (cant test because got no second person but the hosting should work properly)

**Comment by RainyNyte** [comment]
> We dont support essentials, we already have a mod that does world hosting

And it doesn't work, at least on the newest version. Tried to play with my fiance, we're in the same room, on the same internet and their world doesn't appear when hosted to lan and using the url it says the world is shared at in their chat as the server IP fails to connect, either remove the script you put into fancyMenu that does this or fix the broken world hosting mod you are currently using please

**Comment by CapToad** [comment]
> > We dont support essentials, we already have a mod that does world hosting
> 
> And it doesn't work, at least on the newest version. Tried to play with my fiance, we're in the same room, on the same internet and their world doesn't appear when hosted to lan and using the url it says the world is shared at in their chat as the server IP fails to connect, either remove the script you put into fancyMenu that does this or fix the broken world hosting mod you are currently using please

Try removing that script it's somewhere and it's called errors.txt I think

And no the modpack wont break (if essential will be too laggy then check if the modpack uses e4mc and if it doesn't then try that mod but make sure you only put the IP in and not the port because I thought it didn't work but apparently you don't need the port) glhf
