### ISSUE TITLE
controllable mod and spyglass_improvements mod

### ISSUE THREAD

**Issue by SultonMRP** [LunaPixelStudios/SteamPunk#313]
### Describe the Bug

my friend uses controller for all his games, we tried to use controllable mod with mod pack and it conflicts with "spyglass_improvements-1.5+mc1.19+forge.jar" seams both are fighting for Z key. also "spyglass_improvements". I notified MrCrayfish discord about it, will leave a message with spyglass guy too. just updating you :D

### Reproduction Steps

1. put controllable-0.18.0-1.19.2.jar into modpack mod folder
2. start Steampunk.
3. nothin

log file shows both mods fighting for Z onKeyDown. Question, is spyglass_improvements for forge or neoforge? what one is modpack using?

### Crash Report or Log

https://mclo.gs/i832p9d

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

controllable-0.18.0-1.19.2.jar

**Comment by qwek1** [comment]
Its been an issue for a while now, hopefully a fix soon from their end :p
