### ISSUE TITLE
Mods versions in the server pack dont match mod versions in the modpack

### ISSUE THREAD

**Issue by bluegamer22421** [LunaPixelStudios/SteamPunk#314]
### Describe the Bug

I launched v25 with Exaroton hosting using their modpack version update and it says me the mods version does not match

### Reproduction Steps

1. Update modpack to v25
2. Update Server pack to v25
3. Join the server
4. Fail to connect
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/74bb4870-5d50-4eaf-9cd9-94215e0ff562)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v25

### Other Mods

None

**Comment by qwek1** [comment]
Its an issue with their modpack installer, or an issue with how you installed the modpack. If this issue still happens could you provide your latest.log?

**Comment by SHXRKIEgg** [comment]
this is user error, we cant help other than telling you to use the correct versions and same mods
