### ISSUE TITLE
Server while initializing crashes: [Server] INFO Error: could not open `jar/unix_args.txt'

### ISSUE THREAD

**Issue by domeepc** [LunaPixelStudios/SteamPunk#315]
### Describe the Bug

When getting a new version of SteamPunk [LPS] (v25) on Apex Hosting mods are added fine but then it tries to open  `jar/unix_args.txt' which is not found in jar folder and SteamPunk.jar in jar folder has only 'placeholder' written in it.

### Reproduction Steps

1. Initiated the fresh server (Apex Hosting)
2. Modpack installed
3. Server crashed due to Error: could not open `jar/unix_args.txt'
...

### Screenshots and Videos

![image](https://github.com/user-attachments/assets/9f26ed0a-8f19-495a-bb40-0a8f9579860a)

Contents of JAR folder:
![image](https://github.com/user-attachments/assets/b3ef8f20-f188-4329-91db-f7ac1cce2fec)

Content of SteamPunk.jar:
![image](https://github.com/user-attachments/assets/535c67ed-fbb9-4b2c-9fc6-664ccbc705f5)

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v25

**Comment by SHXRKIEgg** [comment]
The steampunk.jar is not something we provide, thats on Apex Hosting
