### ISSUE TITLE
no oil coming out of the derrick

### ISSUE THREAD

**Issue by Hoekk22** [LunaPixelStudios/SteamPunk#316]
### Describe the Bug

Oil doesn't comes up from the derrick added by the "immersive petroleum mod". The derrick drilled down to the bedrock. There are the pipes that he installed and still the oil does not comes up...
I hope it gets fixed

### Reproduction Steps

1. in this case I don't know what to write here

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v25

### Other Mods

there is none

**Comment by qwek1** [comment]
please report this to the developer of the immersive petroleum mod
