### ISSUE TITLE
Says Broken Spawner on side of Screen

### ISSUE THREAD

**Issue by Arryx418** [LunaPixelStudios/SteamPunk#317]
### Describe the Bug

Constantly says Broken Spawner 100% on side of screen no matter what. Don't know where this came from or how to get rid of it, and couldn't find anything relating to it online.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-09-02_20 55 28](https://github.com/user-attachments/assets/97aa2493-6fbb-4b1e-99c9-6aa407ea1b28)

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v25

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by qwek1** [comment]
You pinned a quest, you can go into the questbook and unpin it
