### ISSUE TITLE
Server overload

### ISSUE THREAD

**Issue by JP-Show** [LunaPixelStudios/SteamPunk#318]
### Describe the Bug

I'm trying to create a server with Steampunk v25, but this modpack is overloading it too much.
I've tested it on 2 providers.
first machine:
2vcore - 8gb - 100gb nvme;
second machine:
2vcore - 10gb - 100gb nvme;
my local machine:
ryzen 5 5600x - 16gb - 500gb nvme

Both overload the server.
I would like to know the minimum to run this modpack on a server, and what I can improve to optimize this modpack, because I don't know how it can be so heavy.

### Reproduction Steps

[12:12:32] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 3876ms or 77 ticks behind

### Operating System

Windows 11

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v25

### Other Mods

I put refined storage

**Comment by DaBez** [comment]
Same here... 
Intel Xeon E3-1245 v5 (8) @ 3.900GHz, 
32GB RAM
2x2 TB HDD Soft RAID

Pelican Panel - following settings for the server:
Memory: Limited 12288MiB
Disk Space: Unlimited
CPU: Unlimited
Java 18


Highest i've seen was "Running 18269ms or 365 ticks behind" while using up to 10GB of RAM. Mean tick time and Mean TPS are OK (Oerall Mean TPS: 20.000)

**Comment by JP-Show** [comment]
Damn, 32gb Ram, this a expensive config for a server

**Comment by qwek1** [comment]
Please follow the guide [here](<https://github.com/chorbintime/LPS-readme/wiki/1.21#java-installation>) for changing the Java version your server uses. This will improve performance dramatically. If you are on a third party server host, you likely can not change the Java version your server uses. Bisect Hosting and a few VPS providers do allow changing Java version, though, which can usually be done through your server dashboard.

The method on Bisect is to simply go to the main dashboard page, and select "GraalVM 22" as the Java distribution. If it crashes, use 21 instead.

For further performance improvements, you can also follow [this](<https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks>) guide.

If lag persists, run the following command ingame:
``/spark profiler start --only-ticks-over 50``
Then, send the link here
