### ISSUE TITLE
Enigmatic Legacy causing severe latency and producing 70000+ DEBUG lines in just a couple seconds

### ISSUE THREAD

**Issue by ShyloS** [LunaPixelStudios/SteamPunk#319]
### Describe the Bug

Every time I am playing, 1-3 times an hour I will experience a several second period of latency, regardless of being in Singleplayer or Multiplayer. After looking into it as best as I can, I found that at the exact time the spikes are happening, EnigmaticLegacy is freezing and unfreezing thousands of entries related to LootTableLoadEvent.

I don't suffer any FPS drops at the time of the issue, it's just a massive ping spike on both the internal server in SP, or the actual server in MP. After it's over I'll rubberband back to where I was when it started, and it'll process the things I did in the time it was frozen. 

### Reproduction Steps

1. Load World
2. Play for unclear amount of time, usually within 10 minutes
3. Issue occurs naturally

### Crash Report or Log

https://gist.github.com/ShyloS/2439101ba8d35fe9ac0bde640b07b5c7

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

SteamPunk v25

### Other Mods

Storage Drawers 11.4.1 by Texelsaur
Trails&Tales Backport v0.1.1 by FrostBreker
JustZoom v2.0.0 by Keksuccino
BetterDays v3.1.0.6 by Wendall911

**Comment by qwek1** [comment]
Unable to reproduce the issue, please try removing the added mods and if that dosent fix it then report it to the author of the mod
