### ISSUE TITLE
Suggestion: Compatibility datapack for Cold Sweat and Iron's Spells and Spellbooks

### ISSUE THREAD

**Issue by lynnpye** [LunaPixelStudios/SteamPunk#32]
Summary: Cold Sweat adds an "Ice Resistance" effect, available only through potions. I have added a datapack that schedules a function to run every 30 seconds and add this effect to someone wearing the Frostward Ring from Iron's Spells and Spellbooks, to mimic similar heat protection granted by the Fireward Ring.

Details:
Iron's Spells and Spellbooks contains, among other things, two rings, Fireward Ring and Frostward Ring, which give protection from fire and cold spells respectively. The Fireward Ring, in particular, grants the "Fire Resistance" effect to the wearer. The Frostward Ring, however, simply grants "freezing immunity". In particular, while equipped, each tick it forcibly sets the player's "ticksFrozen" value to zero.

Wearing the Fireward Ring matches expectations by making you immune to the high temperate effects from Cold Sweat, specifically because it grants the "Fire Resistance" effect. The Frostward Ring, unintuitively in my opinion, does not protect you from the effects of low temperatures.

By adding this datapack, a Minecraft function will be created and loaded on server start. It calls a second function which runs the following commands:

	effect give @a[curios={item:{id:"irons_spellbooks:frostward_ring"}}] cold_sweat:ice_resistance 32 1 true
	schedule function steampunklps:scheduled_function 30s replace

Where "steampunklps:scheduled_function" is the fully qualified Minecraft function that is repeatedly scheduled.

I've tested this locally and it gives the expected result; you are granted immunity to the Cold Sweat low temperature effects based on the configuration of how the two resistance effects work. The only downside is that if you take the ring off, you will still get a few (up to 30 seconds or so) seconds of additional immunity. You could shorten this by reducing the delay between successive calls and also reducing the duration of the effect granted, but I was trying to not trigger the scheduled function too frequently. I added a two second overlap as a precaution.
[SteamPunkLPS.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12841271/SteamPunkLPS.zip)

**Comment by SHXRKIIE** [comment]
Thanks, will add next update

**Comment by SHXRKIIE** [comment]
v15 is out
