### ISSUE TITLE
Hearths from the Cold Sweat mod are no longer functional

### ISSUE THREAD

**Issue by SnowFoxGames** [LunaPixelStudios/SteamPunk#320]
### Describe the Bug

Hearths are no longer running and producing heat for enclosed rooms. Steam and smoke don't exit from the smokestacks anymore.

### Reproduction Steps

1.Place a Hearth
2.See that it doesn't work
3.
...

### Screenshots and Videos

Not necessary.

### Crash Report or Log

None

### Operating System

Windows 11

### Minecraft Version

1.16.5

### Modloader

Forge

### Modpack Version

v25

### Other Mods

None

**Comment by qwek1** [comment]
will be fixed next update
