### ISSUE TITLE
Changing old minecraft sounds

### ISSUE THREAD

**Issue by erdogndmn** [LunaPixelStudios/SteamPunk#322]
### Describe the Bug

Sorry for inaccurate label. I'm not that familiar with this site.
              I just wanna change sounds to originals but idk it's source. I couldn't find it's cause. ( resourcepack or mod)
              

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win 11 Pro

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

Latest

**Comment by qwek1** [comment]
Should be the Faithless resourcepack changing the sounds

**Comment by erdogndmn** [comment]
Yeah that was the Faithless resorucepack, but i only wanna change it's sounds. I tried deleting sound file from resourcepack but it doesn't work.

**Comment by erdogndmn** [comment]
Dumb me forgot there was a .json file, it's done.
