### ISSUE TITLE
Slow World Generation

### ISSUE THREAD

**Issue by Kynra** [LunaPixelStudios/SteamPunk#324]
### Describe the Bug

Specs:
AMD Ryzen 7 3700X
32G DDR4 RAM
AMD RX 7800XT

Server is V25 running on Windows 10 with 8G ram allocated

Hello! My chunk loading speed is extremely slow when exploring new areas. Issue seems to be in overworld only, nether chunk generation and other dimensions are all normal. When Exploring in the overworld, chunk seems to take multiple minutes to load, slowing down the entire server to  a crawl. This seems to only get worse as I explore more of the world. 

I have followed these two guides https://github.com/chorbintime/LPS-readme/wiki/1.21#java-installation
                                                      https://github.com/Mukul1127/Minecraft-Performance-Flags-Benchmarks

So Now I am using GraalVM 21 with the JVM arguments in the second guide. It seems to have made no difference in performance and chunk generation. 

I did a /spark profiler start --only-ticks-over 50 while exploring and trying to generate new chunks and here are the results:
https://spark.lucko.me/E5JH6N9mNq

### Reproduction Steps

1. start world
2. play
3. explore new area
4. world gen lag
...

### Operating System

Windows 10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v25

**Comment by qwek1** [comment]
will be fixed next update
