### ISSUE TITLE
Cannot update to 1.20.1

### ISSUE THREAD

**Issue by Bazinga944** [LunaPixelStudios/SteamPunk#325]
### Describe the Bug

I tried to update my 1.19.2 steampunk world to to the new 1.20.1 version, and its got corrupted.
i tryed to regenerate from seed, using different launcher, using the reapir tool, neighter of that worked.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

Steampunk [LPS] 1.20 Update

**Comment by SHXRKIEgg** [comment]
As said in the Changelog and Announcement, you cant update a 1.19.2 world to 1.20.1, thats just how mods are
