### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by erdogndmn** [LunaPixelStudios/SteamPunk#326]
### Describe the Bug

I've just downloaded pack and I've got bunch of crashes. 

### Crash Report or Log

https://mclo.gs/ZUfOSH6

### Operating System

Win 11 Pro

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

Latest

**Comment by qwek1** [comment]
caused by your device language, switching to another language will fix it or add `-Duser.language=en -Duser.region=US` to your Java Args
