### ISSUE TITLE
Props to the modpack devs for making it unplayable

### ISSUE THREAD

**Issue by UWOTM8ER** [LunaPixelStudios/SteamPunk#329]
### Describe the Bug

Constant ram spiking when i allocate 8192 mb (16GB total) with a fresh modpack install. Laptop 3050, Ryzen 7 4800H and it ran well before they updated the pack for "1.20"

### Reproduction Steps

1. Install Steampunk [LPS]
2. Run it smoothly until you boot up singleplayer
3. Deal with linear stuttering
...

### Operating System

W10

### Minecraft Version

1.19.2

### Modloader

Forge

### Modpack Version

v24

### Other Mods

None

**Comment by chorbintime** [comment]
Please follow the performance guide in full https://rpg.prominence.wiki/performance-guide
