### ISSUE TITLE
(Likely Unintended) Incredibly Easy Creative Recipes Added in V14

### ISSUE THREAD

**Issue by oitsjustjose** [LunaPixelStudios/SteamPunk#33]
### Describe the Bug

After updating to V14 today, my friend and I noticed that the `new_villagers` mod was added, and adds in `new_villagers:creative_compound` which can be used to make the following:

- Creative Worldshaper (Recipe ID: `new_villagers:creative_worldshaper`)
- Creative Crate (Recipe ID: `new_villagers:creative_crate`)
- Creative Motor (Recipe ID: `new_villagers:creative_motor`)
- Creative Fluid Tank (Recipe ID: `new_villagers:creative_fluid_tank`)
- Creative Blaze Cake (Recipe ID: `new_villagers:creative_blaze_cake`)

The recipe only requires an Allium & Andesite Alloy through Haunting & Mixing. 

### Reproduction Steps

1. Start up game
2. Set up a Haunting & Mixing set up with Create
3. Use Allium to haunt into Creative Essence
4. Mix Creative Essence with Andesite Alloy to create Creative Compound
5. Craft 5 progression-breaking devices

### Screenshots and Videos

![javaw_10-09-23 10-48-53-048](https://github.com/LunaPixelStudios/SteamPunk/assets/3887324/1d4a2fc2-f2a1-488b-b09f-258374c271f0)
![javaw_10-09-23 10-48-56-566](https://github.com/LunaPixelStudios/SteamPunk/assets/3887324/79bc957a-6f2a-421b-8319-76a1dc89def1)
![javaw_10-09-23 10-48-59-788](https://github.com/LunaPixelStudios/SteamPunk/assets/3887324/de874248-b3df-4d12-9828-5cf3a15920d0)
![javaw_10-09-23 10-49-02-968](https://github.com/LunaPixelStudios/SteamPunk/assets/3887324/d43a224d-b61e-4379-bfc4-0ed1ff90285a)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v14

### Optifine

No

**Comment by SHXRKIIE** [comment]
Thanks, did not realise it made recipe changes

**Comment by SHXRKIIE** [comment]
v15 is out
