### ISSUE TITLE
Cannot update from v3 to v4

### ISSUE THREAD

**Issue by Caua2003** [LunaPixelStudios/SteamPunk#330]
### Describe the Bug

When trying to update the mod from v3 to v4 the game breaks, the server loads but gets lot of warnings and I discovered is some issue with the scorched guns mod, so cant really play the new version, maybe I did something wrong while updating the server? or the versions are incompatible?

### Reproduction Steps

1.replace the server files with the new v4 ones
2.keep getting error about scorched guns mod
3.if you fire a musket you imediatly crash
...

### Screenshots and Videos

.

### Crash Report or Log

.

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v4

### Other Mods

.

**Comment by chorbintime** [comment]
You need to send logs, or I can not provide help

**Comment by Caua2003** [comment]
Fair, I've already rolled back to v3, when I have some time I'll try to update again and if the issue persists then I will open a new issue, but just so I know, v3 and v4 are compatible right? To update the server from v3 to v4 I just need to overwrite the server package with the new one right? Or is there anything else I need to do?

**Comment by Caua2003** [comment]
> You need to send logs, or I can not provide help
Fair, I've already rolled back to v3 so I don't have the logs right now, when I have some time I'll try to update again and if the issue persists then I will open a new issue, but just so I know, v3 and v4 are compatible right? To update the server from v3 to v4 I just need to overwrite the server package with the v4 one right? Or is there anything else I need to do?

**Comment by chorbintime** [comment]
> > You need to send logs, or I can not provide help
> 
> Fair enough, I've already rolled back to v3 so I don't have the logs right now, when I have some time I'll try to update again and if the issue persists then I will open a new issue, but just so I know, v3 and v4 are compatible right? To update the server from v3 to v4 I just need to overwrite the server package with the v4 one right? Or is there anything else I need to do?

You need to do a fresh install of the serverpack, and transfer ONLY the world folder. You can also transfer the server.properties file if you made any changes there, and you can transfer the opped_players file if you want the list of OPped players to transfer over.
