### ISSUE TITLE
Datapack issues on server side

### ISSUE THREAD

**Issue by Avalon2106** [LunaPixelStudios/SteamPunk#332]
### Describe the Bug

Issue with booting servers after most recent release for the 1.20 version of Steampunk LPS
Server cannot fully load due to issues with datapacks, as stated in the logs. Server was able to launch previously

### Reproduction Steps

1.Launch the server
2. wait a bit
3.
...

### Crash Report or Log

https://mclo.gs/MavmsdI

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v6

### Other Mods

N/A

**Comment by qwek1** [comment]
Please provide the full log
