### ISSUE TITLE
Creative Menu crashes minecraft

### ISSUE THREAD

**Issue by clarkkent67** [LunaPixelStudios/SteamPunk#333]
### Describe the Bug

When i go into creatve and the press E to open the creative menu minecraft crashes i dont know why and i dont get a descriptive log about why either.

### Reproduction Steps

1. Load into my server
2. Go into creative mode from survival or load in, in creative mode already
3. press E to open the creative menu
...

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

1.20 V6

### Other Mods

Endofherobrine
EyesInTheDark
Beware the rain (or the mod in the folder is just called Beware)

**Comment by qwek1** [comment]
Its an issue with one of the mods you added
