### ISSUE TITLE
The instant death from void type damage that bypass totem of undying

### ISSUE THREAD

**Issue by JustVtech** [LunaPixelStudios/SteamPunk#334]
### Describe the Bug

So i use "Tome of void" from enigmatic addon that add +1 arcane scroll and also give instant damage i didn't known it's "void type damage" because i happen to equip Angel's Blessing ? that make you vulnerable to wither and void damage then it's instant kill me BUT i have totem in my left hand and yea... it bypass the totem it's almost like you get /kill command and die.. because you can even jump into the void and make totem work!!! i also have a seven curses

### Reproduction Steps

1.use Seven Curses ring
2.use Angel's Blessing spellstone
3.have a totem of undying with either left hand, charm slot or both
4.use the tome of void

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v5

### Other Mods

BadMobs
citresewn
Chunky

**Comment by qwek1** [comment]
Report this to the developers of the Enigmatic Addons mod instead please
