### ISSUE TITLE
Helmet gets deleted when leaving The End through the End Portal

### ISSUE THREAD

**Issue by yerpNaut** [LunaPixelStudios/SteamPunk#337]
### Describe the Bug

Any kind of helmet in the player's helmet slot gets deleted after leaving The End dimension through the End Portal.

Notes:
- The Seven curses are active.
- only happens to the helmet, all the other armor pieces are fine.
- leaving The End with a Potion of Recall works just fine.

### Reproduction Steps

1. Put on a Helmet,
2. Go to The End through The Stronghold's Portal,
3. Beat Ender Dragon to spawn End Portal,
4. Go back through the End Portal,
5. Helmet is gone.

### Screenshots and Videos

https://github.com/user-attachments/assets/e441ee6b-266e-498d-adce-d0f4ed94e0ff

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v6

### Other Mods

Continuity

**Comment by chorbintime** [comment]
v6 is very old. Please update to the latest version of the modpack
