### ISSUE TITLE
Spikes in GPU usage, have allocated ram.

### ISSUE THREAD

**Issue by FevilGitHub** [LunaPixelStudios/SteamPunk#339]
### Describe the Bug

Noticing GPU spikes in this current build, and an inability to actually get into my first world as an "Invalid Player Data" error. I also have the latest drivers available. Just thought to let you know!

I also have allocated 8000 MB of ram, as a just in case.

### Reproduction Steps

1. play the modpack
2. play for a bit
3. gpu spikes and messes up computer's audio slightly every time it does so.

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v8

**Comment by chorbintime** [comment]
Please send logs for us to help, and to fix performance issues follow the [performance guide](https://rpg.prominence.wiki/performance-guide)
