### ISSUE TITLE
Suggestion: Add Create experience nuggets and blocks as Forbidden and Arcanus forge inputs

### ISSUE THREAD

**Issue by lynnpye** [LunaPixelStudios/SteamPunk#34]
The Hephaestus Forge in Forbidden and Arcanus has 4 inputs, one of which is experience. 

The attached datapack adds the experience nugget and experience block from Create as inputs, for 3 and 27 per item respectively, matching the amounts they provide in game.

[create_and_forbidden_xp.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12866100/create_and_forbidden_xp.zip)

**Comment by SHXRKIIE** [comment]
v15 is out
