### ISSUE TITLE
Post Newest Update V10 Crash Issue

### ISSUE THREAD

**Issue by Adriftsalem** [LunaPixelStudios/SteamPunk#342]
### Describe the Bug

When attempting to create a new world for the new modpack update, the game hard crashes to desktop. It passes loading chunks screen, and tries to load player visuals before hard crashing.

### Reproduction Steps

1.Create new world
2.Attempts to load, Succeeds.
3.Before loading player fully (Showing environment, HUD, etc), crashes to desktop.

### Screenshots and Videos

![image_2024-12-03_092048662](https://github.com/user-attachments/assets/cfda9d92-127a-4d7f-bb26-95b9795c6c45)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v10

**Comment by qwek1** [comment]
fixed on latest
