### ISSUE TITLE
Icebox won't take water bucket

### ISSUE THREAD

**Issue by Kitsune2375** [LunaPixelStudios/SteamPunk#344]
### Describe the Bug

The icebox from the mod cold sweat don't want to take the water bucket but the boiler accept to take the lava bucket.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v10HF

**Comment by qwek1** [comment]
Please report this to the developer of the cold sweat mod instead
