### ISSUE TITLE
Hot Springs biome counts as cold

### ISSUE THREAD

**Issue by Nyaa-rlathotep** [LunaPixelStudios/SteamPunk#348]
### Describe the Bug

The "Hot Springs" biome seems to count as still a cold place as far Cold Sweat is concerned. Even when in the water of the hot springs themselves, it's showing a temperature of around 0 degrees Fahrenheit (sub zero in Celsius).

### Reproduction Steps

Go to a hot springs biome.

### Operating System

Linux

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v11

### Other Mods

Light Overlay

**Comment by qwek1** [comment]
will check to see whether I can fix it on my end, if not then ill contact the mod developer. Thanks for reporting
