### ISSUE TITLE
Paintings++ UI deosn't apply Painting choice due to conflict with Fast Paintings

### ISSUE THREAD

**Issue by oitsjustjose** [LunaPixelStudios/SteamPunk#36]
### Describe the Bug

When using a painting against a wall, you're prompted to pick a painting (a convenience feature from Paintings++). However, because Fast Paintings replaces the Painting Entity with a Block Entity, the choice you select with the UI is entirely ignored.

### Reproduction Steps

1. Craft a painting
2. Use the painting on a flat surface
3. Select a painting
4. Notice that your selection was *entirely* ignored.

### Screenshots and Videos

https://github.com/LunaPixelStudios/SteamPunk/assets/3887324/7533c11e-2f63-4ef2-bc7a-1ba706b67d38

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15

### Optifine

No

**Comment by SHXRKIIE** [comment]
I see, they added Compatibility to 1.20.1 versions but not 1.19.2, will report to Meh.

**Comment by SHXRKIIE** [comment]
Fixed in v16
