### ISSUE TITLE
Sophisticated Storage settings causing UI issue with upgrades

### ISSUE THREAD

**Issue by lynnpye** [LunaPixelStudios/SteamPunk#37]
### Describe the Bug

The changes to sophisticatedstorage-server.toml to nerf the storage and upgrades are causing issues with the UI. Specifically, in the effort to reduce the available number of slots for things like the filter options on key upgrade, the slotsInRow values were reduced instead.

Here is what a sophisticated chest with the Auto-Smelting Upgrade (smelting tier 2) looks like:
![autosmeltupgradeuiissue](https://github.com/LunaPixelStudios/SteamPunk/assets/1483771/47dfa4df-3133-42c7-93a6-45e5fc8edd66)

Note that the input filter slots are still numbered at 8, but because the slots per row was reduced to 2, there are now 4 rows which is causing overlap with the actual smelting process. Likewise, the fuel input slots remains at 4, but at only 1 per row, it creates 4 rows.

Aside from the reductions in size for the storage containers, it seemed to me you wanted to:
- reduce the filter slots for tier 1 upgrades to 1 from the default of 3 (because you had set slotsInRow to 1)
- reduce the filter slots for tier 2 upgrades to 2 from the default of 6 (because you had set slotsInRow to 2)
- reduce the input filter slots for auto smelt/smoke/blast upgrades to 2 from the default of 8 (because you had set inputFilterSlotsInRow to 2)
- reduce the fuel filter slots for auto smelt/smoke/blast upgrades to 1 from the default of 4 (because you had set fuelFilterSlotsInRow to 1)

Based on this, I think the attached (zipped) copy of sophisicatedstorage-server.toml is probably what you wanted.

[sophisticatedstorage-server.toml.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12909364/sophisticatedstorage-server.toml.zip)

### Reproduction Steps

1. Place a sophisticated storage container with an upgrade slot
2. Add the auto smelter upgrade
3. Add iron ore as a filter item
4. Add coal as a fuel filter item
5. Change the upgrade to 'Allow'
6. Add iron ore and coal to the storage container
7. Note that the UI filter slots overlap the activity slots (i.e. the actual iron ore stack being smelted)
8. Note that you are unable to move the iron ore out of the smelting slot because the filter slot is covering it

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Fixed in v16
