### ISSUE TITLE
Errors in scguns_recipes_and_balance.zip datapack

### ISSUE THREAD

**Issue by lynnpye** [LunaPixelStudios/SteamPunk#38]
### Describe the Bug

I've attached a new copy of the datapack:

[scguns_recipes_and_balance.zip](https://github.com/LunaPixelStudios/SteamPunk/files/12909865/scguns_recipes_and_balance.zip)

The current version has several problems:
- the recipe for ethereal bullet used quantities of 128 for an ingredient and an output, causing problems in a dedicated server environment (reduced to 64 in, 64 out)
- the filename "scorched_staff _scatter.json" has a space in it; fixed
- rivet cast was referencing a scorchedguns:rivet instead of scguns:rivet
- shotbolt from quiver recipe was referencing a non-existent cgm:shotbolt; fixed

### Reproduction Steps

Ethereal bullets have no proper recipe on a dedicated server
Rivet casts can't be built without scorched guns rivets
The scorched scatter staff can't be built
Shotbolts can't be crafted from the quiver of shotbolts

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Fixed in v16
