### ISSUE TITLE
Unknown Crash

### ISSUE THREAD

**Issue by CHFrEnZy** [LunaPixelStudios/SteamPunk#39]
### Describe the Bug

I was just playing, then falled on a block and it crashed, it says something about a sound, idk much about bugs :(

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/LdetaBRf

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk 15.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Remove the presencefootsteps mod

**Comment by CHFrEnZy** [comment]
> Remove the presencefootsteps mod

it worked, thx a lot :)
