### ISSUE TITLE
Soul bead from quark not rendering

### ISSUE THREAD

**Issue by Inteprise** [LunaPixelStudios/SteamPunk#4]
### Describe the Bug

First pic shows the entity supposedly spawned on the map but you only see a tiny bit of smoke and nothing else

The second pic is just quark by itself and that it should spawn and look like that but it doesnt work on the pack for whatever reason

The third pack is what it looks like in the modpack, just a puff of smoke that goes away after a few second no swirl etc

### Reproduction Steps

1. Obtain soul bead
2. Right click
3. Hear sound and see the entity(?) on the map, purple squares, but it doesnt actually show the bead flying towards a fortress
...

### Screenshots and Videos

![soul1](https://github.com/LunaPixelStudios/SteamPunk/assets/30332315/28ef1deb-3c80-4674-b606-38fa9a36e256)
![soul2](https://github.com/LunaPixelStudios/SteamPunk/assets/30332315/33559114-ddb1-4fda-8e11-180a6a902b48)
![soul3](https://github.com/LunaPixelStudios/SteamPunk/assets/30332315/f9da2684-2535-4516-9f10-66f5c2ae91a1)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V4.5HF

### Optifine

No

**Comment by SHXRKIIE** [comment]
Soul bread locates fortresses? if so it could be that the fortress has been replaced by another its not working

**Comment by SHXRKIIE** [comment]
I dont think soul bead is compatible with Hex fortress
