### ISSUE TITLE
Server crashing potentially during chunk loading

### ISSUE THREAD

**Issue by lucasballr** [LunaPixelStudios/SteamPunk#40]
### Describe the Bug

The crashing started after about a week of playing. Just updated to 15.5 and it is still happening. It seems to happen whenever the players go to a certain place in the world.

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/raw/bWXPqGeq

### Operating System

Debian 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

### Other Mods

Performance improvement mods: 
AI-Improvements-1.19.2-0.5.2.jar
canary-mc1.19.2-0.2.8.jar
ItShallNotTick-1.0.11-build.35.jar

**Comment by SHXRKIIE** [comment]
Remove Canary, its not in the modpack due to it being incompatible with mods in this modpack
