### ISSUE TITLE
Sheep, cows and horses spawn only in few selected biomes

### ISSUE THREAD

**Issue by target-san** [LunaPixelStudios/SteamPunk#41]
### Describe the Bug

Sheep and cows are virtually impossible to find on the map, except in spawned ranch-like structures guarded by hostile mobs, which are quite rare themselves. Horses can be found, though extremely rare.
According to Spawn Balance Utility biome logs:

* minecraft:sheep spawns only in minecraft:plains, minecraft:sunflower_plains and minecraft:meadow
* minecraft:cow spawns only in minecraft:plains and minecraft:sunflower_plains
* minecraft:horse has 13 spawn entries in 13 biomes

For comparison:

* minecraft:pig has 75 spawn entries in 19 biomes, almost always having 4 spawn entries per biome

### Reproduction Steps

In-game:
1. Create new world
2. Wander around world, notice vanilla mob spawns

Expected:
Cows, sheep spawn roughly as often as pigs, horses are rare yet can be found

Actual
Sheep and cows are nonexistent, horses are very rare, pigs are more or less common

Using SBU mod:
1. Create and start new world
2. Check spawn logs in config/spawnbalanceutility/BiomeMobWeight.txt

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

### Other Mods

AppleSkin
Simply Tools
Spawn Balance Utility

**Comment by SHXRKIIE** [comment]
Boars, bulls and other mobs replace some of their spawns, disable them in the EE expansion if you prefer them to spawn more

**Comment by target-san** [comment]
I don't intend to argue. Just wanna clarify.
You're right about cows, they indeed can be partially replaced. But not sheep. They're the only fast source of the starter wool to get you a bed. The only other reliable source is industrial hemp, which grows quite slowly. Flax is much rarer. Is this intentional, to make player solve this at start?
