### ISSUE TITLE
Can't open the game anymore 

### ISSUE THREAD

**Issue by Rafafrontera** [LunaPixelStudios/SteamPunk#42]
### Describe the Bug

I was playing the modpack normal until the night of 16/10, and yesterday when i went to play, the modpack doesn't open anymore, when i try to start the game, the loading screen go all white, and crashs, giving the error 1 in Minecraft, and sometimes, it even made my pc screen go all black, and i have to restart the pc in the button, i have already checked all my drivers, win stalation and all, have even reinstaled the modpack, but didn't work.
Obs: Have tried 5 other modpacks, and all the others have worked normal. 
Obs 2: It's not by lack of RAM, i have allocated 16gb to the Minecraft (have 32gb, in the total)

![imagem_2023-10-18_111800275](https://github.com/LunaPixelStudios/SteamPunk/assets/86336382/9c9094c8-a404-4151-a5bd-756f08e54545)
 

### Reproduction Steps

1.I tried to launch the modpack
2.The screen go all white, and crash
3.The modpack close and appears error 1
...

### Operating System

Win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Dont allocate 16gb do like 10 also send the latest.log

**Comment by Rafafrontera** [comment]
Tried to alocate 10gb, but have the same error.
[latest.log](https://github.com/LunaPixelStudios/SteamPunk/files/13043377/latest.log)

**Comment by SHXRKIIE** [comment]
Doesnt show anything wrong, just reinstall, make sure to grab your save from the save folder

**Comment by Rafafrontera** [comment]
Thanks, have reinstalled and it worked, for 1 time... when i try to oper again, it didn't work...
