### ISSUE TITLE
Inception Upgrade settings for Sophisticated Backpack missing

### ISSUE THREAD

**Issue by BreagAlainn** [LunaPixelStudios/SteamPunk#43]
### Describe the Bug

Inception Mod when placed in a backpack doesn't show settings to allow mods in backpacks placed in primary backpack to be used.  Tested with: Tool Swapper upgrade, Pickup Upgrade, Refill Upgrade and Feeding Upgrade; however, once a backpack is placed in the Inception backpack the upgrade doesn't function as if in player inventory.

### Reproduction Steps

1. Created inception upgrade and placed in Backpack mod slot.
2. Noticed no settings tab added to backpack.
3. Tested Upgrades used in different backpacks.
4. Upgrades placed in backpack did not function as expected.
5. Tested Inception Upgrade in alternate backpacks and created a new backpack to test in case of strange coincidence.
6. No in game solution worked for me.

### Screenshots and Videos

![Inception 1](https://github.com/LunaPixelStudios/SteamPunk/assets/148372436/432a25f8-fe92-43fe-8bb0-002fb33cacff)
![Inception 2](https://github.com/LunaPixelStudios/SteamPunk/assets/148372436/c2dc1a26-fa94-4bc4-95ee-2ddee521e71e)

### Crash Report or Log

N/A

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v15.5

### Optifine

No

### Other Mods

N/A

**Comment by SHXRKIIE** [comment]
Inception Upgrade has been disabled
