### ISSUE TITLE
Clipping of some item icons on "sophisticated storage" limited barrels

### ISSUE THREAD

**Issue by Lodewolf** [LunaPixelStudios/SteamPunk#44]
### Describe the Bug

a minor problem, but might as well notify you guys.
the icons on the storage is so big that it covers the stack amount and also clips in the barrel itself, dunno if it has something to do with the 3d item icons

Things that clips i noticed:
- Blocks (building blocks, most of them)
- Potion (it becomes 3d and displays from top-down)
- Books (same with cubes)
- Redstone torches (hides behind the barrel and causes flickers/jittering)
- Create items

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/16514772/825130a0-9113-4d7b-be25-1a06925335a8)
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/16514772/e78713bb-b468-404e-8565-3c76fad0ddb5)

### Operating System

Win11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v15.5

### Optifine

I used Optifine

### Other Mods

none other than the modpack has provided

**Comment by SHXRKIIE** [comment]
Remove faithless resourcepacks

**Comment by Lodewolf** [comment]
tried removing the faithless resourcepack, but now the texture itself has disappeared. just updated to the lates version also

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/16514772/1de525e0-83cc-4906-964e-6d9f188c37ff)

**Comment by Myliak** [comment]
Problem is persisting on v21.5 version
