### ISSUE TITLE
Spawned Skeleton Horses cannot be ridden or tamed

### ISSUE THREAD

**Issue by Croat86** [LunaPixelStudios/SteamPunk#46]
### Describe the Bug

I tried everything, respawning them, hitting them with a lightningbolt etc. somehow i can not ride them.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

16.5

### Optifine

No

### Other Mods

Pipez, Mystical Aggriculture, Torchmaster, Immersive Patroleum, botany, botany pots

**Comment by chorbintime** [comment]
v16.5 is very old - we offer no support for old versions of the modpack. your world is safe to updateb

**Comment by SirHaxe** [comment]
> v16.5 is very old - we offer no support for old versions of the modpack. your world is safe to update

@chorbintime are you sure you've meant to reply here? V16.5 is the newest release of the Steampunk pack

**Comment by chorbintime** [comment]
shit my bad HAHAHA i thought this was the better mc github

**Comment by SHXRKIIE** [comment]
Honestly dont know how to fix this lol, gonna need to spend a lot of time testing which mod causes it
