### ISSUE TITLE
Creating a large biomes world crashes minecraft

### ISSUE THREAD

**Issue by SirHaxe** [LunaPixelStudios/SteamPunk#49]
### Describe the Bug

https://mclo.gs/Z3EBxUT
Creating a large biomes world crashes minecraft, can anyone confirm it or themselves, or is that just me? 
"net.minecraft.world.level.dimension.LevelStem.m63990()" because "levelStem" is null

### Reproduction Steps

1. create world set to large biomes

### Crash Report or Log

https://mclo.gs/Z3EBxUT

### Operating System

Win 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

16.5

### Optifine

No

**Comment by SirHaxe** [comment]
additional info: last version where they worked is v14, v15.5 already produces the crash
https://mclo.gs/NQvXcyn
heres the log for 15.5

**Comment by SirHaxe** [comment]
addition to the addition:
disabling the aether mods fixes the issue

**Comment by SHXRKIIE** [comment]
Will report it to the Aether Redux mod dev, but in testing it does work, maybe you think the biomes are larger than they should be? but with the same seed the maps look different but you can see that one has smaller biomes compared to the larger biome gen.
