### ISSUE TITLE
Conduit Power doesn't prevent drowning.

### ISSUE THREAD

**Issue by TheHeeli** [LunaPixelStudios/SteamPunk#5]
### Describe the Bug

Conduit Power from conduits or other sources does not prevent the player from drowning/dying due to lack of air. I presume this is an oversight due to the "Thin Air" mod changing the breathing system. Since Conduit Power is coded separately to Water Breathing, I guess it was just overlooked.

### Reproduction Steps

1. Make Conduit.
2. Don't get air.
3. Die. :/

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v4.5 HF

### Optifine

No

**Comment by SHXRKIIE** [comment]
reported to thin air
