### ISSUE TITLE
Game doesent start

### ISSUE THREAD

**Issue by Gergo3** [LunaPixelStudios/SteamPunk#50]
### Describe the Bug

I tried to play the modpack, but the game crashes while loading. I installed the modpack whit prismlauncher, and I've made shure that the modpack is up to date. I have tried reinstalling the modpack, but it didnt help.

### Reproduction Steps

1.launch the game
2.the game starts loading, but crashes

### Crash Report or Log

https://0x0.st/HyAn.txt

### Operating System

archlinux

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v16.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Can you send the crash report it made please

**Comment by Gergo3** [comment]
> Could you try ATLauncher?

I have triede atlaun cher but it failed to download the pack at all.

**Comment by Gergo3** [comment]
I have dound that my launcher did not  correctlydownload the pack, I tried whit its windows version and it worked.
I will write a bugreport to the launcher.
