### ISSUE TITLE
Error: Could not find or load main class @user_jvm_args.txt

### ISSUE THREAD

**Issue by minefactory69** [LunaPixelStudios/SteamPunk#52]
### Describe the Bug

I use SteamPunk_Server_Pack_v17.5 and when i click the stat.sh i get this error.

### Reproduction Steps

1. download the zip from Curseforge
2. extract the zip
3. click starth.sh
4. it starts the downloading
5. after finishing with the downloading i type I agree
6. It starts the server and i get this error: Error: Could not find or load main class @user_jvm_args.txt

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/58185159/6039b70f-8027-49fe-82d5-43ba9972bc08)

### Crash Report or Log

https://pastebin.com/wNvLbi1j

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk_Server_Pack_v17.5 

### Optifine

I used Optifine

**Comment by qwek1** [comment]
use Java18
