### ISSUE TITLE
GUI mod

### ISSUE THREAD

**Issue by Sa5hby** [LunaPixelStudios/SteamPunk#53]
Not really an issue but trying to find which mod is controlling the video settings change from vanilla so i can remove it. cant find it on the mods folder or the settings.

**Comment by SHXRKIIE** [comment]
You are not going to remove it because you will  mess up the modpack

**Comment by CapToad** [comment]
@Sa5hby its fancymenu and drippyloadingscreeen, from my experience it just messes up the minecraft logo and thats it
