### ISSUE TITLE
Server pack v17.5 CRASHES

### ISSUE THREAD

**Issue by zselybence** [LunaPixelStudios/SteamPunk#54]
### Describe the Bug

When I start the server it crashes with this error
Error: Could not find or load main class @user_jvm_args.txt

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Képernyőkép 2023-11-02 120654](https://github.com/LunaPixelStudios/SteamPunk/assets/91417838/6c647218-5074-4b08-8723-fa795d282750)
![Képernyőkép 2023-11-02 115920](https://github.com/LunaPixelStudios/SteamPunk/assets/91417838/0bfb4a74-5071-45a6-bcbd-cd85bb8b6579)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk Server Pack v17.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Need Java 17
