### ISSUE TITLE
NullPointerException - Multiplayer - 17.5

### ISSUE THREAD

**Issue by dakiba** [LunaPixelStudios/SteamPunk#55]
### Describe the Bug

Then I just try to enter a IP address in the multiplayer screen, the game crash with this message:

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.multiplayer.ClientPacketListener.m_6198_()" because the return value of "net.minecraft.client.Minecraft.m_91403_()" is null
```

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

17.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
See if removing Server Country Flag mod helps
