### ISSUE TITLE
Crash when click on a mod

### ISSUE THREAD

**Issue by David-Andrei1** [LunaPixelStudios/SteamPunk#56]
### Describe the Bug

If you serch the mod "Create: New Age" in the mod list (in-game) and click on it to see more detail the game crash

Crash reported by b24fun (If you need more info or a reply dm me at b24fun on discord)

### Reproduction Steps

1. Click on the anvil button in game menu or in a world press escape and mods
2. Serch the mod "Create: New Age"
3. Press on the mod to see more detail
4.  And done, you succesfuly crash minecraft =D

### Screenshots and Videos

https://github.com/LunaPixelStudios/SteamPunk/assets/125668821/3fc8d7ab-0c4b-4df7-92cb-4da7d1f053c9

### Crash Report or Log

https://pastebin.com/ATVBa3KF    Password: Crash

### Operating System

Windows 11 22H2

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

17.5

### Optifine

No

### Other Mods

I don't install any mod

**Comment by SHXRKIIE** [comment]
Will report to the dev
