### ISSUE TITLE
Camt join party

### ISSUE THREAD

**Issue by Ricsking** [LunaPixelStudios/SteamPunk#57]
### Describe the Bug

After latest update cant join in party it writes 
"Specific Team-Commands are disabled by recruits mod, use the team screen instead" but its not works there too.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

V17.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Check v18
