### ISSUE TITLE
Empty Tag for Quality Crops fish and Farmer's Delight cutting board

### ISSUE THREAD

**Issue by Boomerphish** [LunaPixelStudios/SteamPunk#59]
### Describe the Bug

I can't use the cutting board to make higher quality fish slices

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot (1)](https://github.com/LunaPixelStudios/SteamPunk/assets/150210642/636eb590-2314-4b65-9f3b-4a68a915dce4)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v17.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Waiting for a fix from the Dev

**Comment by Azamatbek001** [comment]
I become adventure mode while i was playing survival without cheats I'm confused how how that heppened

**Comment by SHXRKIIE** [comment]
Just waiting for the mod to update
