### ISSUE TITLE
Temperature bug on server

### ISSUE THREAD

**Issue by MichinYeoja** [LunaPixelStudios/SteamPunk#6]
### Describe the Bug

When playing with a group on a server temperature overlaps with all players causing it to fluctuate. If someone is in the overworld and one is in the nether, the overworld person begins to overheat and even can begin to die.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2023-07-15_12 10 22](https://github.com/LunaPixelStudios/SteamPunk/assets/22733178/9214c590-af94-4080-bcb6-e383b4eb3e47)
the fluctuation is rapid hard to catch with pic
![2023-07-15_12 14 43_2](https://github.com/LunaPixelStudios/SteamPunk/assets/22733178/8a95589a-1050-441e-be47-1d4e5f885164)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

4.5HF

### Optifine

No

**Comment by SHXRKIIE** [comment]
Reporting to Cold Sweat Mod

**Comment by SHXRKIIE** [comment]
Will be fixed in v5
