### ISSUE TITLE
The mod Create: Missions don't install in update v18

### ISSUE THREAD

**Issue by David-Andrei1** [LunaPixelStudios/SteamPunk#61]
### Describe the Bug

When I install the v18 update, the Create: Missions mod doesn't install as mentioned in the update note

### Reproduction Steps

1. Install the update v18
2. Enter the game and here we go, enjoy the non-existent mod =)

### Screenshots and Videos

![Captură de ecran 2023-11-08 190958](https://github.com/LunaPixelStudios/SteamPunk/assets/125668821/ed305292-101a-459c-8b7f-940c3224a58d)

### Crash Report or Log

No crash report

### Operating System

Windows 11 22H2

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

### Other Mods

I don't any mod

**Comment by SHXRKIIE** [comment]
It does and it works, you are not doing something right then
