### ISSUE TITLE
Tree Farm Create Contraption causing a Game Crash

### ISSUE THREAD

**Issue by Muddykat-tech** [LunaPixelStudios/SteamPunk#62]
### Describe the Bug

If you create a create contraption that is designed to cut down trees using a mechanical saw it will cause a game crash after a few rotations.

note: issue #60 seems to be the same crash

### Reproduction Steps

1. Create a create contraption using a mechanical saw, some storage and give it trees to cut down (further testing found that the storage interface was not required)
2. After a few rotations it will cause a game crash.

### Screenshots and Videos

![2023-11-10_14 54 17](https://github.com/LunaPixelStudios/SteamPunk/assets/17131200/c6685fcf-ce39-4066-9325-45460eac6d1e)

### Crash Report or Log

https://pastebin.com/gbx8LcAH

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

**Comment by SHXRKIIE** [comment]
Fixed in v18.5
