### ISSUE TITLE
new UI is realy ugly

### ISSUE THREAD

**Issue by dakiba** [LunaPixelStudios/SteamPunk#63]
### Describe the Bug

Sorry, but the new UI for toms storage in the V18 is very ugly ...

Can you maybe start a discord server and test your new versions with the community before you release it?
Like a Alpha / Beta? That would help a lot of.

![grafik](https://github.com/LunaPixelStudios/SteamPunk/assets/117845495/ce5cd341-95ae-4e06-822c-bd47dbf8106a)

### Reproduction Steps

1.
2.
3.
...

### Operating System

-

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

18

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/a47d896c-efb3-4366-9962-34f6fe94f2ef)
that is the correct one so you must have done something with the resourcepacks, delete your options.txt
