### ISSUE TITLE
Crash ServerHangWatchdog 

### ISSUE THREAD

**Issue by dakiba** [LunaPixelStudios/SteamPunk#64]
### Describe the Bug

Even with the missions-forge-0.1.6 mod the server crashes with version 18.
**Please add some alpha / beta testing with a discord community ...
And don't add things like vive craft / voice chat and so on ... that have only impact on the performence and 99% of the people don't use such mods.**

crash log:
[crash-2023-11-10_19.38.43-server.txt](https://github.com/LunaPixelStudios/SteamPunk/files/13322700/crash-2023-11-10_19.38.43-server.txt)

### Operating System

Linux Server

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

18

**Comment by SHXRKIIE** [comment]
Fixed in
