### ISSUE TITLE
Soul Revitalizer display bug on energy bar

### ISSUE THREAD

**Issue by Aathoss** [LunaPixelStudios/SteamPunk#66]
### Describe the Bug

Additionally on the server side there is a display bug on the energy bar which requires 16,960 energy.
In solo, it is well displayed 1,000,000 energy.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![javaw_YFNx9lBjks](https://github.com/LunaPixelStudios/SteamPunk/assets/33701752/82b88301-ee6e-4299-ba7b-6a925f43053f)
![javaw_4zqeKhHig0](https://github.com/LunaPixelStudios/SteamPunk/assets/33701752/ca137e0e-0f54-402a-881f-61beaf36e5b6)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v18

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Reported the bug to the Dev, wil be fixed in next update hopefully if they update
