### ISSUE TITLE
New chunk take forever to generate

### ISSUE THREAD

**Issue by David-Andrei1** [LunaPixelStudios/SteamPunk#67]
### Describe the Bug

When i explore new chunck is take ages to generate

### Operating System

Windows 11 22H2

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v18.5

### Optifine

No

### Other Mods

No other mods

**Comment by SHXRKIIE** [comment]
Doesnt help if you dont provide a log or spark profiler

**Comment by David-Andrei1** [comment]
And @SHXRKIIE how in the world i suppose to do that???? (Sorry for late comment)

**Comment by SHXRKIIE** [comment]
add the spark mod into the mods folder go into the world do /spark profiler --timeout 30 and and generate chunks and send link

**Comment by David-Andrei1** [comment]
Here we go the spark https://spark.lucko.me/o1W4DGg4sb

**Comment by SHXRKIIE** [comment]
Is this when the chuck take forever to generate because it doesnt seem like it because its at 20 tps

**Comment by SHXRKIIE** [comment]
Also your memory is being capped so there are many factors that could be causing it
![image](https://github.com/LunaPixelStudios/SteamPunk/assets/79353591/53f42140-3dad-4524-ad28-83f01e1dbd71)

**Comment by David-Andrei1** [comment]
I know, when i play steampunk my RAM go betwen 70 and 97

**Comment by SHXRKIIE** [comment]
yeah so if your ram is maxing out then it will perform worse and cause these issues
