### ISSUE TITLE
Exit code 1

### ISSUE THREAD

**Issue by Annie2205** [LunaPixelStudios/SteamPunk#69]
### Describe the Bug

I launched the game and every time I get exit code 1. I tried everything and I don't know what the problem is. I already tried ATLauncher but it doesn't work.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

18.5

### Optifine

No

### Other Mods

No

**Comment by SHXRKIIE** [comment]
Does not help if you provide no logs
