### ISSUE TITLE
Server is chrasing from The Aether mod

### ISSUE THREAD

**Issue by Corvusz** [LunaPixelStudios/SteamPunk#70]
### Describe the Bug

Our server is chrashing while entering The Aether dimension with more than 2 player. We tested with multipile version's of the modpack (exactly v.18 and v.18.5). Also tested if we enter the portal at the same time or just 1 by 1, and it's happend every time. At the whole time 4 players in the server.

### Reproduction Steps

1. Just enter the portal with 2 other player.

### Crash Report or Log

https://pastebin.com/rwwKf1U3

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v.18 and v18.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Update the aether mod or wait for new update
