### ISSUE TITLE
Low TPS

### ISSUE THREAD

**Issue by qwek1** [LunaPixelStudios/SteamPunk#72]
### Describe the Bug

low tps whenever the server runs for a while. Heres a spark profiler i took just now. https://spark.lucko.me/EATmP3sNJM

### Reproduction Steps

1.
2.
3.
...

### Operating System

Ubuntu? Bisect server idk

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

### Other Mods

spark + observable

**Comment by SHXRKIIE** [comment]
fixed v19.5
