### ISSUE TITLE
It say i do not have ctm where can i download it? 

### ISSUE THREAD

**Issue by D4RKhungary98** [LunaPixelStudios/SteamPunk#73]
### Describe the Bug

Pls help i dont know what to do

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v19.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
reinstall or use a proper launcher

**Comment by D4RKhungary98** [comment]
> reinstall or use a proper launcher

Wich launcher?
