### ISSUE TITLE
Visual bugs

### ISSUE THREAD

**Issue by Kyodai21** [LunaPixelStudios/SteamPunk#74]
### Describe the Bug

Some visual bugs i found :

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

Sophisticated Storage : Diamond Barrel (or any barrel) 
![1](https://github.com/LunaPixelStudios/SteamPunk/assets/76497224/ea070128-8ada-45ec-a718-a69a1c62d253)

Minecraft : Painting gives xray
![2](https://github.com/LunaPixelStudios/SteamPunk/assets/76497224/8a8b5393-1dbc-47b7-b9a2-5735a1517635)

Sophisticated Storage : Chest display option nearly fills the entire chest
![4](https://github.com/LunaPixelStudios/SteamPunk/assets/76497224/e9f22fd5-b291-4a30-81b9-1c9cd6f8fc09)
![3](https://github.com/LunaPixelStudios/SteamPunk/assets/76497224/77700e73-1608-433e-96ca-728a485c76f3)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19.5

### Optifine

No

**Comment by SHXRKIIE** [comment]
Reinstall the modpack
