### ISSUE TITLE
Questbook missing

### ISSUE THREAD

**Issue by D4RKhungary98** [LunaPixelStudios/SteamPunk#77]
### Describe the Bug

I use Tlauncher download steampunk from forge. ReDownload the modpack 2 times but when i create the world i do not have a questbook. Shuld i use an other launcher or what? If yes then wich one? Thank you

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v19.5

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
dont supported cracked
