### ISSUE TITLE
Can't start the game

### ISSUE THREAD

**Issue by Annie2205** [LunaPixelStudios/SteamPunk#78]
### Describe the Bug

So I already wrote a bugreport but i forgot to ad the logs. So first i tried through Forge but i always got exitcode 1, then I tried ATLauncher but it doesn't work and i don't know why.

### Reproduction Steps

1. download the pack
2. starting it
3. exitcode 1/ doesn't even start
...

### Crash Report or Log

<script src="https://gist.github.com/Annie2205/73305feecec37ccc3c10cca46dd99502.js"></script>

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by SHXRKIIE** [comment]
Whatever you gave me isnt a log

**Comment by Annie2205** [comment]
That I don't know. I copied the log and paste it into GitHub gist. Sorry

**Comment by SHXRKIIE** [comment]
Cant help with a proper log or crash
