### ISSUE TITLE
New Chunks take an abnormally long time to render 

### ISSUE THREAD

**Issue by Nend123** [LunaPixelStudios/SteamPunk#80]
### Describe the Bug

When exploring new chunks in the overworld the chunks that are being generated take around 20 seconds per new chunk. This only happens in the overworld. While generating my character is unable to interact with my inventory or any objects in the world.  During generation I get a stable 120 FPS. 

### Reproduction Steps

1. Render new chunks

### Screenshots and Videos

![2023-11-22_09 40 48](https://github.com/LunaPixelStudios/SteamPunk/assets/151776424/43dfb04e-1640-4d22-a6b0-bf154955681d)

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19.5

### Optifine

No

### Other Mods

Explorers Compass, Chunk Pregenerator

**Comment by SHXRKIIE** [comment]
Are you playing while using chunk pregenerator?

**Comment by Nend123** [comment]
No, I tried to run it and set the radius at 10000 blocks but it was gonna take 300 hrs. I stopped it and have left it off since.

**Comment by SHXRKIIE** [comment]
So the issue is happening after you added that mod? as it seems you have played for a while

**Comment by Nend123** [comment]
No it’s been happening since early on in my play through before I installed the mod. I have the mod at the suggestion of an admin. I also tried to run a LAN server with my friend and he experienced the same issues.

**Comment by SHXRKIIE** [comment]
Update to v20 and give me a spark profiler

**Comment by Nend123** [comment]
Not super familiar with spark but here is what I got 
![Capture1](https://github.com/LunaPixelStudios/SteamPunk/assets/151776424/f776c43a-8203-49f6-a9ed-24269f5cbbdf)
![Capture2](https://github.com/LunaPixelStudios/SteamPunk/assets/151776424/7087611d-4d34-48f5-b2e7-e6b7a778958e)

**Comment by SHXRKIIE** [comment]
The spark profiler has 20 TPS meaning there arent any issues, are you sure you are running it while the chunks wont load? and please send the link next time

**Comment by Nend123** [comment]
https://spark.lucko.me/faEmkP87gO Heres the link to the new one I ran. 
![2023-12-02_09 42 57](https://github.com/LunaPixelStudios/SteamPunk/assets/151776424/dc3cb8a3-a39d-4ae0-acb2-fcb4d006c3fd) and this is where I ran the profiler

**Comment by SHXRKIIE** [comment]
Could you remove All bark all bite and its datapack and see if it still occurs?
config and defaultconfig
> paxi > datapacks > remove
