### ISSUE TITLE
Treefarm crashes the server

### ISSUE THREAD

**Issue by Nurn3n** [LunaPixelStudios/SteamPunk#82]
### Describe the Bug

I'm hosting a Steampunk (v18) server for my friend and i, and made a Treefarm with Create, but it crashes the server every other minute. Might have to do something with the trees being next to each other in the classic circular fassion. 

### Reproduction Steps

1.Start the mechanical bearing
2.wait
3.server crashes
...

### Crash Report or Log

https://pastebin.com/1ekY3W9F

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v18

### Optifine

No

**Comment by SHXRKIIE** [comment]
Update to v20
