### ISSUE TITLE
Alex's Mobs overpowering spawn rates

### ISSUE THREAD

**Issue by HiddenTides** [LunaPixelStudios/SteamPunk#83]
### Describe the Bug

It seems some of the mobs from the mod are over populating in different areas. So far seeing a big problem with lobsters, catfish, flyfish, and terrapins. It's getting to the point of making it impossible to use beds and boats, the lag being so bad that mobs can over take you and kill before you even see it.

### Reproduction Steps

1. Go into server/ single player world
2. Play for a few hours, exploring, loading and unloading chunks.
3. Mobs start overpopulating 
4.  Lag spikes increase rapidly
5.  Lag continues to worsen till needing to leave and reenter numerous times. Entering and leaving beds and boats making this more likely to show.
6.  Wait anywhere from 30 seconds to 3 minutes for it to understand where you are or that you were killed.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SP v20

### Optifine

No

**Comment by SHXRKIIE** [comment]
Wil lsee what i can do when i update
