### ISSUE TITLE
Create: New Age power does not work as Immersive Engineering power source

### ISSUE THREAD

**Issue by JohannesKeck** [LunaPixelStudios/SteamPunk#84]
### Describe the Bug

When using Immersive Engineering to power a Create: New Age motor it works flawlessly, however if I try to use the Create: New Age Carbon brushes as a power source to power Immersive Engineering stuff it does not work.

What works: 
Using the Immersive Engineering (HV) Wire Connector on any Create or Create: New Age motor

What doesn't work:
Using Create: New Age Electrical Connector on any Immersive Engineering stuff
Using the Immersive Engineering (HV) Wire Connector on the Create: New Age Carbon brushes

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

version:3120 (from options.txt)

### Optifine

No

**Comment by SHXRKIIE** [comment]
I dont think Create new age is compatible with other tech mods due to botarium and they havent updated this fix
