### ISSUE TITLE
Crash when opening game

### ISSUE THREAD

**Issue by jexxmine** [LunaPixelStudios/SteamPunk#85]
### Describe the Bug

[hs_err_pid21788.log](https://github.com/LunaPixelStudios/SteamPunk/files/13599931/hs_err_pid21788.log)

### Reproduction Steps

1. Launcher is opened though curseforge
2. Play button pressed
3. No menu seen at all before crash.
...

### Crash Report or Log

https://github.com/LunaPixelStudios/SteamPunk/files/13599931/hs_err_pid21788.log

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

I used Optifine

**Comment by SHXRKIIE** [comment]
Update your drivers
