### ISSUE TITLE
I just installed the modpack and I can't play with it

### ISSUE THREAD

**Issue by KriszFan58** [LunaPixelStudios/SteamPunk#86]
### Describe the Bug

So i installed the modpack yesterday and when i today I woke up to see can i run the mod this tittle received me: You have installed a mod that is incompatible with our Modpack! Please remove any extra mods you added to the modpack until this warning disappears. When I JUST DOWNLOADED JUST THE MODPACK!?!?!? Anyway please help me  bc  i really wanna play with this modpack. Maybe the problem is I play with Tlauncer idk but this why i want somebody to respond. 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by SHXRKIIE** [comment]
We dont support tlauncher
