### ISSUE TITLE
Outdated Cold Sweat Configs Lead to Broken Item Functionality

### ISSUE THREAD

**Issue by MikulDev** [LunaPixelStudios/SteamPunk#88]
### Describe the Bug

Hello! Cold Sweat developer here.

I'd like to let you know that the config files for Cold Sweat are out-of-date as of 2.2. The "Goat Fur" item was renamed to just "Fur" within the last couple snapshots before the version's release. This means that the new `cold_sweat:fur` item now does not have an insulation value as it should, since the configs only define an insulation value for  `cold_sweat:goat_fur`.

This also applies to any other fur-related items, such as the fur armor set. I have gotten a couple of bug reports relating to this issue as your modpack has gotten pretty popular, so it'd save the hassle if the configs were updated.

Also, the latest versions of the mod have some bugfixes and new features that could benefit players of your pack. I'd appreciate if the mod could be updated as well. Thanks!

### Operating System

Arch Linux 6.6.6-arch1-1 x64

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v20

### Optifine

No

**Comment by chorbintime** [comment]
will be fixed in the next update, thank you for the report

**Comment by MikulDev** [comment]
Awesome! Thank you!
