### ISSUE TITLE
"Report Bugs" button on pause opens Medieval-MC pull requests.

### ISSUE THREAD

**Issue by tevaearai** [LunaPixelStudios/SteamPunk#89]
### Describe the Bug

As title reads, pausing the game and clicking on the "Report Bugs" option opens https://github.com/LunaPixelStudios/Medieval-MC/pulls

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

**Comment by SHXRKIEgg** [comment]
This is not the medieval github and if you read the wiki its closed for christmas

**Comment by tevaearai** [comment]
I meant that SteamPunk's "Report Bugs" button on pause sends to Medieval's github.
