### ISSUE TITLE
Area of map not working in steampunk v5.0

### ISSUE THREAD

**Issue by GrandadPaul** [LunaPixelStudios/SteamPunk#9]
### Describe the Bug

Steampunk v5.0
There is one area on the map around a desert biome with a desert village.
When entering this area the game stops working, can not doing anything like chopping blocks etc.. 
Can not open inventory or backpack.
We are playing multiplayer with two people playing. 
On the main map shows us in a previous location to where we both was.
On the minimap i can see i am in the right place , but the other player is at the previous location.
We have tried several times to enter this area from differant sides.
With the same results.
After restarting the server to solve this problem we are back to the previous place on the map before it fails.
Anything we can do to solve this?

Maybe not related to this bug the other player who runs the server has a problem with doors not showing that are open. Always has a closed door,but can exit them with no problem.

Thanks in advance.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Steampunk v5.0

### Optifine

No

### Other Mods

comforts-forge-6.0.5+1.19.2
ftb-ultimine-forge-1902.4.1-build.90

**Comment by GrandadPaul** [comment]
Have recreated this seed several times, but have the same problem everytime.

SEED: -3494606753782631410

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/140623332/9bb3bb73-7523-45d1-92a9-cfe54655e22b)

**Comment by SHXRKIIE** [comment]
v6 should fix it
