### ISSUE TITLE
RyoamicLights (ryoamiclights) has failed to load correctly

### ISSUE THREAD

**Issue by goliafrs** [LunaPixelStudios/SteamPunk#91]
### Describe the Bug

I'm using docker image itzg/docker-minecraft-server.
If necessary, I can provide the docker-compose.yml configuration file.

### Crash Report or Log

https://gist.github.com/goliafrs/9c2f868ab48e2fe73ed259d407428ea0

### Operating System

Linux (amd64) version 6.5.0-14-generic

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

### Other Mods

create_blue_skies_compat-1.0.1-1.19
create_compressed_1.0.1_forge_1.19.2
create_recycle_1.0.2_forge_1.19.2
design_decor-0.1a-1.19.2
PacketFixer-forge-1.2.0-1.19.2
tetraextrassro-0.0.9-1.19
Villager+Comfort-1.19.2-1.0.0
JustEnoughResources-1.19.2-1.1.0.179
spruceui-0.1.0+1.19

**Comment by SHXRKIEgg** [comment]
Remove Ryao or remove the mods you added

**Comment by goliafrs** [comment]
If I delete the mods that I added, the modpack will not start either, because I added these mods not on my whim, but according to the instructions.

**Comment by goliafrs** [comment]
Logs when starting the modpack clean, without adding anything:
https://gist.github.com/goliafrs/68696a1b543a99c3523df0b8b4217074
