### ISSUE TITLE
Quest discripton for sails is incorrect.

### ISSUE THREAD

**Issue by BOTFerris** [LunaPixelStudios/SteamPunk#92]
### Describe the Bug

The quest description of the sails shows the description of the blaze burner quest instead.

### Reproduction Steps

1. Open quest book
2. Go to the create tab and look for the sails quest

### Screenshots and Videos

![image](https://github.com/LunaPixelStudios/SteamPunk/assets/33546221/60547578-fdc8-42ef-93a7-76f36a5e8e83)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v20

### Optifine

No

### Other Mods

[Exposure by mortuusars](https://www.curseforge.com/minecraft/mc-mods/exposure)

**Comment by chorbintime** [comment]
will be fixed in next update, thanks
