### ISSUE TITLE
Ring of Seven Curses?

### ISSUE THREAD

**Issue by AssassinDude346** [LunaPixelStudios/SteamPunk#93]
### Describe the Bug

I'm unable to equip the Ring of Seven Curses and on further inspection can't find any slot for the rings in Curio or other mods. I managed to equip an iron ring just by interacting with it in my hotbar but can't find where it is equipped to.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v20

### Optifine

I used Optifine

**Comment by CapToad** [comment]
did you try removing optifine?

**Comment by chorbintime** [comment]
Check Controls for the "open curios inventory" keybind

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
