### ISSUE TITLE
SteamPunk [LPS] v20 Constant Nether Ambiance in the Overworld

### ISSUE THREAD

**Issue by vampireman135** [LunaPixelStudios/SteamPunk#94]
I am running a private SteamPunk [LPS] v20 server.  I downloaded and installed the v20 server file onto the server.  I installed and downloaded everything through CurseForge and have not added any mods or altered any files or configs.  I hear constant nether ambiance sounds, and I'm in the overworld, whilst on the server.  I point this out specifically because I tested it on a sinlgeplayer world, and the constant nether ambiance does not occur.  On the server it doesn't matter what biome I'm in.  I have found that the sounds are connected to the hostile mobs volume settings, so if I turn the hostile mobs volume all the way off the nether sounds cease.  Due to it not occuring on a singleplayer world but only on the server, I'd have a guess saying that it's something with the server pack and not the normal pack.  My friends and I love this pack, but it's almost unplayable with the constant noise.

**Comment by chorbintime** [comment]
Can you record a video of the glitch?

**Comment by vampireman135** [comment]
I recorded the glitch.  It's 5 minutes so I could show that it happens reguardless of height, location, or gamemode.

https://www.dropbox.com/scl/fi/akj6ebetqbtejxhpukm8t/Glitch-Recording.mp4?rlkey=ry6p2o1xblct1jefo4enxq8vz&dl=0

**Comment by SHXRKIEgg** [comment]
Its Incedium mod causing it

**Comment by vampireman135** [comment]
No, it was not Incedium.  I deleted the mod from both the server and mine and my players folders.  I even created a new world, much to the dismay of everyone's progress, just in case the world itself was corrupted somehow and it just needed a new world.  The sounds persist.  It is not solved, completed, or closed, unfortunately.

**Comment by vampireman135** [comment]
I restarted the server, wiped everything and installed the v21 server files.  I launched the game, and the sounds were still there.  I deleted the Incindium mod off of the server and client mods folders and, unfortunately, the nether sounds continue in the overworld on the server.  I have not added additional mods or changed any configs.

**Comment by TreyR9** [comment]
Having the same problem, it is not Incendium causing the ambience to play (fully disabled it). Disabling Scorched Bronze Guns seems to make the ambience stop playing.

**Comment by vampireman135** [comment]
Omg TreyR9, thank you so much!  I took it off the new (4th total) server and the sounds are gone!  We can finally play it!  XD You're a godsend.

**Comment by chorbintime** [comment]
please report it to the developers of Scorched Bronze Guns
