### ISSUE TITLE
Error: could not open `libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt'

### ISSUE THREAD

**Issue by Splatattat** [LunaPixelStudios/SteamPunk#95]
### Describe the Bug

start.sh it stops at
Error: could not open `libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt'

### Reproduction Steps

1../start.sh
2.I agree
3.
...

### Screenshots and Videos

Start script generated by ServerPackCreator 4.3.2.
To change the launch settings of this server, such as JVM args / flags, Minecraft version, modloader version etc., edit the variables.txt-file.

Running Forge checks and setup...
Generating user_jvm_args.txt from variables...
Edit JAVA_ARGS in your variables.txt. Do not edit user_jvm_args.txt directly!
Manually made changes to user_jvm_args.txt will be lost in the nether!
libraries/net/minecraftforge/forge/1.19.2-43.3.5/forge-1.19.2-43.3.5-server.jar could not be found.
Downloading forge-installer.jar
from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.19.2-43.3.5/forge-1.19.2-43.3.5-installer.jar
start.sh: line 40: curl: command not found

libraries/net/minecraft/server/1.19.2/server-1.19.2.jar could not be found.
Downloading libraries/net/minecraft/server/1.19.2/server-1.19.2.jar
from https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar
start.sh: line 40: curl: command not found

Starting server...
Minecraft version: 1.19.2
Modloader:         Forge
Modloader version: 43.3.5

Java args:
Java path:         java
Run Command:       java -Dlog4j2.formatMsgNoLookups=true @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt nogui
Java version:
openjdk version "18.0.2-ea" 2022-07-19
OpenJDK Runtime Environment (build 18.0.2-ea+9-Ubuntu-222.04)
OpenJDK 64-Bit Server VM (build 18.0.2-ea+9-Ubuntu-222.04, mixed mode, sharing)

Error: could not open `libraries/net/minecraftforge/forge/1.19.2-43.3.5/unix_args.txt'

Exiting...

### Operating System

Ubuntu 22.04.3 LTS

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk_Server_Pack_v20

### Optifine

No

**Comment by SHXRKIEgg** [comment]
Redownload the serverpack
