### ISSUE TITLE
cold and sweat does not with sewing table

### ISSUE THREAD

**Issue by mijke56** [LunaPixelStudios/SteamPunk#97]
### Describe the Bug

if you put hoglin hide with armor is does not do anything to the armor and stays the same so the server we have up cant go into the nether or ever dawn because its to hot or cold and no other ways to cool down or heat up but that so half the dimensions are locked for us.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

1.19.2

### Optifine

I used Optifine

**Comment by SHXRKIEgg** [comment]
Fixed
