### ISSUE TITLE
Curios Ring Slot Missing

### ISSUE THREAD

**Issue by AssassinDude346** [LunaPixelStudios/SteamPunk#98]
### Describe the Bug

I'm unable to equip the Ring of Seven Curses and on further inspection can't find any slot for the rings in Curio or other mods. I managed to equip an iron ring just by interacting with it in my hotbar but can't find where it is equipped to. I mistakenly said I was using Optifine last time but that was not the case.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![ring1](https://github.com/LunaPixelStudios/SteamPunk/assets/18109140/164ef6c6-e7a1-4a70-97cb-d5a7c04b9321)
![ring2](https://github.com/LunaPixelStudios/SteamPunk/assets/18109140/3e5dcea2-2c77-49e0-a81d-e00f814ee046)
![ring3](https://github.com/LunaPixelStudios/SteamPunk/assets/18109140/09603c99-6a16-40b1-a2c6-fcaf7e603a80)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

SteamPunk v20

### Optifine

No

**Comment by AssassinDude346** [comment]
The 3 missing texture slots in the curio inventory are Charm, curios.identifier.blue_trinket, and curios.indentifier.red_trinket. The second screenshot shows the 1 armor granted by an iron ring being equipped.

**Comment by AssassinDude346** [comment]
I'm using CurseForge.

**Comment by SHXRKIEgg** [comment]
Fixed
