### ISSUE TITLE
Chunk/block rendering takes a long time 

### ISSUE THREAD

**Issue by SaphiraSkulblaka** [LunaPixelStudios/SteamPunk#99]
### Describe the Bug
When I just play normally without changing the pack, I have the problem that blocks take a long time to update/disappear. Only when I press F3+A and reload the chunks does everything render correctly

###Reproduction Steps
1. Just Playing

![Bild_2024-01-15_110522219](https://github.com/LunaPixelStudios/SteamPunk/assets/146716914/62b90462-d7dc-40d4-bb53-c222763a9d6d)

### Crash Report or Log
No response

### Operating System
Windows 10

### Minecraft Version
1.19.5

### Modloader
Forge

### Modpack Version
v.20

Optifine
No

Other Mods

**Comment by SHXRKIEgg** [comment]
Follow performance guide
